/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* src = "/content/ISCAS89/s27.v:8.1-14.10" *)
module dff(CK, Q, D);
  (* src = "/content/ISCAS89/s27.v:9.7-9.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s27.v:9.10-9.11" *)
  input D;
  wire D;
  (* src = "/content/ISCAS89/s27.v:10.8-10.9" *)
  output Q;
  wire Q;
  (* src = "/content/ISCAS89/s27.v:12.1-13.10" *)
  DFFR _0_ (
    .C(CK),
    .D(D),
    .Q(Q),
    .R(1'h0)
  );
endmodule

(* top =  1  *)
(* src = "/content/ISCAS89/s27.v:16.1-36.10" *)
module s27(CK, G0, G1, G17, G2, G3);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "/content/ISCAS89/s27.v:17.7-17.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s27.v:17.10-17.12" *)
  input G0;
  wire G0;
  (* src = "/content/ISCAS89/s27.v:17.13-17.15" *)
  input G1;
  wire G1;
  (* src = "/content/ISCAS89/s27.v:20.11-20.14" *)
  wire G10;
  (* src = "/content/ISCAS89/s27.v:20.18-20.21" *)
  wire G11;
  (* src = "/content/ISCAS89/s27.v:20.25-20.28" *)
  wire G13;
  (* src = "/content/ISCAS89/s27.v:18.8-18.11" *)
  output G17;
  wire G17;
  (* src = "/content/ISCAS89/s27.v:17.16-17.18" *)
  input G2;
  wire G2;
  (* src = "/content/ISCAS89/s27.v:17.19-17.21" *)
  input G3;
  wire G3;
  (* src = "/content/ISCAS89/s27.v:20.8-20.10" *)
  wire G5;
  (* src = "/content/ISCAS89/s27.v:20.15-20.17" *)
  wire G6;
  (* src = "/content/ISCAS89/s27.v:20.22-20.24" *)
  wire G7;
  INV _3_ (
    .A(G0),
    .Y(_0_)
  );
  NOR2 _4_ (
    .A(G1),
    .B(G7),
    .Y(_1_)
  );
  AOI22 _5_ (
    .A0(_0_),
    .A1(G6),
    .B0(G3),
    .B1(_1_),
    .Y(_2_)
  );
  NOR2 _6_ (
    .A(G5),
    .B(_2_),
    .Y(G11)
  );
  INV _7_ (
    .A(G11),
    .Y(G17)
  );
  NOR2 _8_ (
    .A(_0_),
    .B(G11),
    .Y(G10)
  );
  NOR2 _9_ (
    .A(G2),
    .B(_1_),
    .Y(G13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s27.v:22.7-22.23" *)
  dff DFF_0 (
    .CK(CK),
    .D(G10),
    .Q(G5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s27.v:23.7-23.23" *)
  dff DFF_1 (
    .CK(CK),
    .D(G11),
    .Q(G6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s27.v:24.7-24.23" *)
  dff DFF_2 (
    .CK(CK),
    .D(G13),
    .Q(G7)
  );
endmodule
