/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* src = "/content/ISCAS89/s382.v:7.1-13.10" *)
module dff(CK, Q, D);
  (* src = "/content/ISCAS89/s382.v:8.7-8.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s382.v:8.10-8.11" *)
  input D;
  wire D;
  (* src = "/content/ISCAS89/s382.v:9.8-9.9" *)
  output Q;
  wire Q;
  (* src = "/content/ISCAS89/s382.v:11.1-12.10" *)
  DFFR _0_ (
    .C(CK),
    .D(D),
    .Q(Q),
    .R(1'h0)
  );
endmodule

(* top =  1  *)
(* src = "/content/ISCAS89/s382.v:15.1-229.10" *)
module s382(CK, CLR, FM, GRN1, GRN2, RED1, RED2, TEST, YLW1, YLW2);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  (* src = "/content/ISCAS89/s382.v:28.46-28.52" *)
  wire C1VCO0;
  (* src = "/content/ISCAS89/s382.v:22.19-22.24" *)
  wire C3_Q0;
  (* src = "/content/ISCAS89/s382.v:22.25-22.32" *)
  wire C3_Q0VD;
  (* src = "/content/ISCAS89/s382.v:22.5-22.10" *)
  wire C3_Q1;
  (* src = "/content/ISCAS89/s382.v:22.11-22.18" *)
  wire C3_Q1VD;
  (* src = "/content/ISCAS89/s382.v:21.63-21.68" *)
  wire C3_Q2;
  (* src = "/content/ISCAS89/s382.v:21.69-21.76" *)
  wire C3_Q2VD;
  (* src = "/content/ISCAS89/s382.v:21.49-21.54" *)
  wire C3_Q3;
  (* src = "/content/ISCAS89/s382.v:21.55-21.62" *)
  wire C3_Q3VD;
  (* src = "/content/ISCAS89/s382.v:16.7-16.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s382.v:16.18-16.21" *)
  input CLR;
  wire CLR;
  (* src = "/content/ISCAS89/s382.v:28.27-28.31" *)
  wire CLRB;
  (* src = "/content/ISCAS89/s382.v:16.10-16.12" *)
  input FM;
  wire FM;
  (* src = "/content/ISCAS89/s382.v:28.23-28.26" *)
  wire FMB;
  (* src = "/content/ISCAS89/s382.v:19.34-19.37" *)
  wire FML;
  (* src = "/content/ISCAS89/s382.v:19.38-19.55" *)
  wire FMLVIINLATCHVCDAD;
  (* src = "/content/ISCAS89/s382.v:17.8-17.12" *)
  output GRN1;
  wire GRN1;
  (* src = "/content/ISCAS89/s382.v:17.13-17.17" *)
  output GRN2;
  wire GRN2;
  (* src = "/content/ISCAS89/s382.v:20.21-20.32" *)
  wire OLATCHVUC_5;
  (* src = "/content/ISCAS89/s382.v:20.5-20.16" *)
  wire OLATCHVUC_6;
  (* src = "/content/ISCAS89/s382.v:21.26-21.36" *)
  wire OLATCH_FEL;
  (* src = "/content/ISCAS89/s382.v:21.5-21.15" *)
  wire OLATCH_G1L;
  (* src = "/content/ISCAS89/s382.v:20.58-20.68" *)
  wire OLATCH_G2L;
  (* src = "/content/ISCAS89/s382.v:20.37-20.47" *)
  wire OLATCH_R1L;
  (* src = "/content/ISCAS89/s382.v:24.46-24.56" *)
  wire OLATCH_R2L;
  (* src = "/content/ISCAS89/s382.v:24.35-24.45" *)
  wire OLATCH_Y1L;
  (* src = "/content/ISCAS89/s382.v:19.56-19.66" *)
  wire OLATCH_Y2L;
  (* src = "/content/ISCAS89/s382.v:28.53-28.70" *)
  wire OUTBUFVBUFR2VIIR1;
  (* src = "/content/ISCAS89/s382.v:29.5-29.22" *)
  wire OUTBUFVBUFY1VIIR1;
  (* src = "/content/ISCAS89/s382.v:20.33-20.36" *)
  wire R2C;
  (* src = "/content/ISCAS89/s382.v:17.18-17.22" *)
  output RED1;
  wire RED1;
  (* src = "/content/ISCAS89/s382.v:17.28-17.32" *)
  output RED2;
  wire RED2;
  (* src = "/content/ISCAS89/s382.v:31.66-31.74" *)
  wire TCOMB_FE;
  (* src = "/content/ISCAS89/s382.v:21.37-21.48" *)
  wire TCOMB_FE_BF;
  (* src = "/content/ISCAS89/s382.v:21.16-21.25" *)
  wire TCOMB_GA1;
  (* src = "/content/ISCAS89/s382.v:20.69-20.78" *)
  wire TCOMB_GA2;
  (* src = "/content/ISCAS89/s382.v:20.48-20.57" *)
  wire TCOMB_RA1;
  (* src = "/content/ISCAS89/s382.v:19.67-19.76" *)
  wire TCOMB_YA2;
  (* src = "/content/ISCAS89/s382.v:16.13-16.17" *)
  input TEST;
  wire TEST;
  (* src = "/content/ISCAS89/s382.v:28.32-28.37" *)
  wire TESTB;
  (* src = "/content/ISCAS89/s382.v:19.8-19.13" *)
  wire TESTL;
  (* src = "/content/ISCAS89/s382.v:19.14-19.33" *)
  wire TESTLVIINLATCHVCDAD;
  (* src = "/content/ISCAS89/s382.v:23.43-23.48" *)
  wire UC_10;
  (* src = "/content/ISCAS89/s382.v:23.49-23.56" *)
  wire UC_10VD;
  (* src = "/content/ISCAS89/s382.v:23.57-23.62" *)
  wire UC_11;
  (* src = "/content/ISCAS89/s382.v:23.63-23.70" *)
  wire UC_11VD;
  (* src = "/content/ISCAS89/s382.v:28.38-28.45" *)
  wire UC_11VZ;
  (* src = "/content/ISCAS89/s382.v:22.33-22.38" *)
  wire UC_16;
  (* src = "/content/ISCAS89/s382.v:22.39-22.46" *)
  wire UC_16VD;
  (* src = "/content/ISCAS89/s382.v:22.47-22.52" *)
  wire UC_17;
  (* src = "/content/ISCAS89/s382.v:22.53-22.60" *)
  wire UC_17VD;
  (* src = "/content/ISCAS89/s382.v:22.61-22.66" *)
  wire UC_18;
  (* src = "/content/ISCAS89/s382.v:22.67-22.74" *)
  wire UC_18VD;
  (* src = "/content/ISCAS89/s382.v:23.5-23.10" *)
  wire UC_19;
  (* src = "/content/ISCAS89/s382.v:23.11-23.18" *)
  wire UC_19VD;
  (* src = "/content/ISCAS89/s382.v:23.19-23.23" *)
  wire UC_8;
  (* src = "/content/ISCAS89/s382.v:23.24-23.30" *)
  wire UC_8VD;
  (* src = "/content/ISCAS89/s382.v:23.31-23.35" *)
  wire UC_9;
  (* src = "/content/ISCAS89/s382.v:23.36-23.42" *)
  wire UC_9VD;
  (* src = "/content/ISCAS89/s382.v:20.17-20.20" *)
  wire Y1C;
  (* src = "/content/ISCAS89/s382.v:17.33-17.37" *)
  output YLW1;
  wire YLW1;
  (* src = "/content/ISCAS89/s382.v:17.23-17.27" *)
  output YLW2;
  wire YLW2;
  INV _067_ (
    .A(TESTL),
    .Y(_023_)
  );
  INV _068_ (
    .A(UC_17),
    .Y(_024_)
  );
  INV _069_ (
    .A(UC_18),
    .Y(_025_)
  );
  INV _070_ (
    .A(UC_8),
    .Y(_026_)
  );
  INV _071_ (
    .A(FML),
    .Y(_027_)
  );
  INV _072_ (
    .A(C3_Q0),
    .Y(_028_)
  );
  INV _073_ (
    .A(C3_Q2),
    .Y(_029_)
  );
  INV _074_ (
    .A(OLATCH_FEL),
    .Y(_030_)
  );
  INV _075_ (
    .A(CLR),
    .Y(_031_)
  );
  INV _076_ (
    .A(OLATCHVUC_5),
    .Y(RED2)
  );
  INV _077_ (
    .A(OLATCHVUC_6),
    .Y(YLW1)
  );
  NOR2 _078_ (
    .A(_030_),
    .B(CLR),
    .Y(_032_)
  );
  NOR2 _079_ (
    .A(C3_Q1),
    .B(C3_Q2),
    .Y(_033_)
  );
  NAND2 _080_ (
    .A(C3_Q3),
    .B(_031_),
    .Y(_034_)
  );
  NOR2 _081_ (
    .A(_029_),
    .B(CLR),
    .Y(_035_)
  );
  NAND2 _082_ (
    .A(C3_Q2),
    .B(_031_),
    .Y(_036_)
  );
  AOI22 _083_ (
    .A0(C3_Q0),
    .A1(_033_),
    .B0(_034_),
    .B1(_036_),
    .Y(_037_)
  );
  NOR2 _084_ (
    .A(_032_),
    .B(_037_),
    .Y(TCOMB_RA1)
  );
  NOR2 _085_ (
    .A(UC_10),
    .B(C1VCO0),
    .Y(_038_)
  );
  NOR3 _086_ (
    .A(UC_9),
    .B(UC_10),
    .C(C1VCO0),
    .Y(_039_)
  );
  OAI21 _087_ (
    .A0(_026_),
    .A1(_039_),
    .B0(_031_),
    .Y(_040_)
  );
  NOR2 _088_ (
    .A(C1VCO0),
    .B(_040_),
    .Y(UC_11VD)
  );
  NAND2 _089_ (
    .A(C3_Q0),
    .B(C3_Q1),
    .Y(_041_)
  );
  OAI22 _090_ (
    .A0(C3_Q0),
    .A1(_034_),
    .B0(_041_),
    .B1(CLR),
    .Y(_042_)
  );
  NOR3 _091_ (
    .A(_032_),
    .B(_035_),
    .C(_042_),
    .Y(TCOMB_GA2)
  );
  NAND2 _092_ (
    .A(_029_),
    .B(_030_),
    .Y(_043_)
  );
  NOR3 _093_ (
    .A(CLR),
    .B(_041_),
    .C(_043_),
    .Y(TCOMB_YA2)
  );
  NOR2 _094_ (
    .A(C3_Q1),
    .B(C3_Q3),
    .Y(_044_)
  );
  AOI21 _095_ (
    .A0(_027_),
    .A1(C3_Q0),
    .B0(_044_),
    .Y(_045_)
  );
  NAND2 _096_ (
    .A(OLATCH_FEL),
    .B(_045_),
    .Y(_046_)
  );
  NOR2 _097_ (
    .A(C3_Q0),
    .B(C3_Q1),
    .Y(_047_)
  );
  OAI21 _098_ (
    .A0(C3_Q3),
    .A1(_047_),
    .B0(FML),
    .Y(_048_)
  );
  AOI21 _099_ (
    .A0(_035_),
    .A1(_046_),
    .B0(_048_),
    .Y(_049_)
  );
  INV _100_ (
    .A(_049_),
    .Y(TCOMB_GA1)
  );
  NAND2 _101_ (
    .A(UC_10),
    .B(C1VCO0),
    .Y(_050_)
  );
  INV _102_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND2 _103_ (
    .A(UC_9),
    .B(_051_),
    .Y(_052_)
  );
  INV _104_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR2 _105_ (
    .A(UC_8),
    .B(_053_),
    .Y(_054_)
  );
  NOR2 _106_ (
    .A(_040_),
    .B(_054_),
    .Y(UC_8VD)
  );
  NOR2 _107_ (
    .A(UC_9),
    .B(_051_),
    .Y(_055_)
  );
  NOR3 _108_ (
    .A(_040_),
    .B(_053_),
    .C(_055_),
    .Y(UC_9VD)
  );
  NOR3 _109_ (
    .A(_038_),
    .B(_040_),
    .C(_051_),
    .Y(UC_10VD)
  );
  OAI21 _110_ (
    .A0(_026_),
    .A1(_039_),
    .B0(_023_),
    .Y(_056_)
  );
  NAND2 _111_ (
    .A(UC_19),
    .B(_056_),
    .Y(_057_)
  );
  INV _112_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR2 _113_ (
    .A(_025_),
    .B(_057_),
    .Y(_059_)
  );
  NOR3 _114_ (
    .A(_024_),
    .B(_025_),
    .C(_057_),
    .Y(_060_)
  );
  NOR2 _115_ (
    .A(UC_16),
    .B(_060_),
    .Y(_061_)
  );
  NOR3 _116_ (
    .A(UC_17),
    .B(UC_18),
    .C(UC_19),
    .Y(_062_)
  );
  INV _117_ (
    .A(_062_),
    .Y(_063_)
  );
  AOI21 _118_ (
    .A0(UC_16),
    .A1(_056_),
    .B0(_063_),
    .Y(_064_)
  );
  NAND2 _119_ (
    .A(_031_),
    .B(_064_),
    .Y(_065_)
  );
  NOR2 _120_ (
    .A(_061_),
    .B(_065_),
    .Y(UC_16VD)
  );
  NOR2 _121_ (
    .A(UC_17),
    .B(_059_),
    .Y(_066_)
  );
  NOR3 _122_ (
    .A(_060_),
    .B(_065_),
    .C(_066_),
    .Y(UC_17VD)
  );
  NOR2 _123_ (
    .A(UC_18),
    .B(_058_),
    .Y(_000_)
  );
  NOR3 _124_ (
    .A(_059_),
    .B(_065_),
    .C(_000_),
    .Y(UC_18VD)
  );
  NOR2 _125_ (
    .A(UC_19),
    .B(_056_),
    .Y(_001_)
  );
  NOR3 _126_ (
    .A(_058_),
    .B(_065_),
    .C(_001_),
    .Y(UC_19VD)
  );
  OAI21 _127_ (
    .A0(_029_),
    .A1(_045_),
    .B0(_032_),
    .Y(_002_)
  );
  AOI21 _128_ (
    .A0(FML),
    .A1(_035_),
    .B0(_047_),
    .Y(_003_)
  );
  NAND2 _129_ (
    .A(_002_),
    .B(_003_),
    .Y(TCOMB_FE)
  );
  NAND2 _130_ (
    .A(UC_17),
    .B(TCOMB_FE),
    .Y(_004_)
  );
  AOI21 _131_ (
    .A0(C3_Q3),
    .A1(_031_),
    .B0(_047_),
    .Y(_005_)
  );
  NOR2 _132_ (
    .A(C3_Q2),
    .B(_005_),
    .Y(_006_)
  );
  NOR3 _133_ (
    .A(C3_Q0),
    .B(C3_Q1),
    .C(C3_Q3),
    .Y(_007_)
  );
  AOI21 _134_ (
    .A0(FML),
    .A1(_035_),
    .B0(_007_),
    .Y(_008_)
  );
  NAND2 _135_ (
    .A(_002_),
    .B(_008_),
    .Y(_009_)
  );
  OAI21 _136_ (
    .A0(_006_),
    .A1(_009_),
    .B0(_004_),
    .Y(Y1C)
  );
  AOI21 _137_ (
    .A0(_036_),
    .A1(_002_),
    .B0(_005_),
    .Y(_010_)
  );
  NAND2 _138_ (
    .A(_004_),
    .B(_010_),
    .Y(R2C)
  );
  NOR2 _139_ (
    .A(_041_),
    .B(_064_),
    .Y(_011_)
  );
  NOR3 _140_ (
    .A(_029_),
    .B(_041_),
    .C(_064_),
    .Y(_012_)
  );
  NOR2 _141_ (
    .A(C3_Q3),
    .B(_012_),
    .Y(_013_)
  );
  NAND2 _142_ (
    .A(_028_),
    .B(_033_),
    .Y(_014_)
  );
  NAND2 _143_ (
    .A(C3_Q3),
    .B(_014_),
    .Y(_015_)
  );
  OAI21 _144_ (
    .A0(_064_),
    .A1(_015_),
    .B0(_031_),
    .Y(_016_)
  );
  NOR2 _145_ (
    .A(_013_),
    .B(_016_),
    .Y(C3_Q3VD)
  );
  NOR2 _146_ (
    .A(C3_Q2),
    .B(_011_),
    .Y(_017_)
  );
  NOR3 _147_ (
    .A(_012_),
    .B(_016_),
    .C(_017_),
    .Y(C3_Q2VD)
  );
  NOR2 _148_ (
    .A(_028_),
    .B(_064_),
    .Y(_018_)
  );
  NOR2 _149_ (
    .A(C3_Q1),
    .B(_018_),
    .Y(_019_)
  );
  NOR3 _150_ (
    .A(_011_),
    .B(_016_),
    .C(_019_),
    .Y(C3_Q1VD)
  );
  XNOR2 _151_ (
    .A(_028_),
    .B(_064_),
    .Y(_020_)
  );
  NOR2 _152_ (
    .A(_016_),
    .B(_020_),
    .Y(C3_Q0VD)
  );
  XNOR2 _153_ (
    .A(FML),
    .B(FM),
    .Y(_021_)
  );
  NOR2 _154_ (
    .A(CLR),
    .B(_021_),
    .Y(FMLVIINLATCHVCDAD)
  );
  XNOR2 _155_ (
    .A(TESTL),
    .B(TEST),
    .Y(_022_)
  );
  NOR2 _156_ (
    .A(CLR),
    .B(_022_),
    .Y(TESTLVIINLATCHVCDAD)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:47.7-47.42" *)
  dff DFF_0 (
    .CK(CK),
    .D(TESTLVIINLATCHVCDAD),
    .Q(TESTL)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:48.7-48.38" *)
  dff DFF_1 (
    .CK(CK),
    .D(FMLVIINLATCHVCDAD),
    .Q(FML)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:57.7-57.31" *)
  dff DFF_10 (
    .CK(CK),
    .D(C3_Q2VD),
    .Q(C3_Q2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:58.7-58.31" *)
  dff DFF_11 (
    .CK(CK),
    .D(C3_Q1VD),
    .Q(C3_Q1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:59.7-59.31" *)
  dff DFF_12 (
    .CK(CK),
    .D(C3_Q0VD),
    .Q(C3_Q0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:60.7-60.31" *)
  dff DFF_13 (
    .CK(CK),
    .D(UC_16VD),
    .Q(UC_16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:61.7-61.31" *)
  dff DFF_14 (
    .CK(CK),
    .D(UC_17VD),
    .Q(UC_17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:62.7-62.31" *)
  dff DFF_15 (
    .CK(CK),
    .D(UC_18VD),
    .Q(UC_18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:63.7-63.31" *)
  dff DFF_16 (
    .CK(CK),
    .D(UC_19VD),
    .Q(UC_19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:64.7-64.29" *)
  dff DFF_17 (
    .CK(CK),
    .D(UC_8VD),
    .Q(UC_8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:65.7-65.29" *)
  dff DFF_18 (
    .CK(CK),
    .D(UC_9VD),
    .Q(UC_9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:66.7-66.31" *)
  dff DFF_19 (
    .CK(CK),
    .D(UC_10VD),
    .Q(UC_10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:49.7-49.37" *)
  dff DFF_2 (
    .CK(CK),
    .D(TCOMB_YA2),
    .Q(OLATCH_Y2L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:67.7-67.31" *)
  dff DFF_20 (
    .CK(CK),
    .D(UC_11VD),
    .Q(C1VCO0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:50.7-50.32" *)
  dff DFF_3 (
    .CK(CK),
    .D(Y1C),
    .Q(OLATCHVUC_6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:51.7-51.32" *)
  dff DFF_4 (
    .CK(CK),
    .D(R2C),
    .Q(OLATCHVUC_5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:52.7-52.37" *)
  dff DFF_5 (
    .CK(CK),
    .D(TCOMB_RA1),
    .Q(OLATCH_R1L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:53.7-53.37" *)
  dff DFF_6 (
    .CK(CK),
    .D(TCOMB_GA2),
    .Q(OLATCH_G2L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:54.7-54.37" *)
  dff DFF_7 (
    .CK(CK),
    .D(TCOMB_GA1),
    .Q(OLATCH_G1L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:55.7-55.39" *)
  dff DFF_8 (
    .CK(CK),
    .D(TCOMB_FE),
    .Q(OLATCH_FEL)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s382.v:56.7-56.30" *)
  dff DFF_9 (
    .CK(CK),
    .D(C3_Q3VD),
    .Q(C3_Q3)
  );
  assign GRN1 = OLATCH_G1L;
  assign GRN2 = OLATCH_G2L;
  assign OLATCH_R2L = RED2;
  assign OLATCH_Y1L = YLW1;
  assign OUTBUFVBUFR2VIIR1 = OLATCHVUC_5;
  assign OUTBUFVBUFY1VIIR1 = OLATCHVUC_6;
  assign RED1 = OLATCH_R1L;
  assign FMB = FM;
  assign TCOMB_FE_BF = TCOMB_FE;
  assign TESTB = TEST;
  assign UC_11 = C1VCO0;
  assign UC_11VZ = C1VCO0;
  assign CLRB = CLR;
  assign YLW2 = OLATCH_Y2L;
endmodule
