/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b03.blif (REQUEST1, REQUEST2, REQUEST3, REQUEST4, GRANT_O_3_, GRANT_O_2_, GRANT_O_1_, GRANT_O_0_);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  (* init = 1'h0 *)
  wire CODA0_REG_0_;
  (* init = 1'h0 *)
  wire CODA0_REG_1_;
  (* init = 1'h0 *)
  wire CODA0_REG_2_;
  (* init = 1'h0 *)
  wire CODA1_REG_0_;
  (* init = 1'h0 *)
  wire CODA1_REG_1_;
  (* init = 1'h0 *)
  wire CODA1_REG_2_;
  (* init = 1'h0 *)
  wire CODA2_REG_0_;
  (* init = 1'h0 *)
  wire CODA2_REG_1_;
  (* init = 1'h0 *)
  wire CODA2_REG_2_;
  (* init = 1'h0 *)
  wire CODA3_REG_0_;
  (* init = 1'h0 *)
  wire CODA3_REG_1_;
  (* init = 1'h0 *)
  wire CODA3_REG_2_;
  (* init = 1'h0 *)
  wire FU1_REG;
  (* init = 1'h0 *)
  wire FU2_REG;
  (* init = 1'h0 *)
  wire FU3_REG;
  (* init = 1'h0 *)
  wire FU4_REG;
  output GRANT_O_0_;
  wire GRANT_O_0_;
  output GRANT_O_1_;
  wire GRANT_O_1_;
  output GRANT_O_2_;
  wire GRANT_O_2_;
  output GRANT_O_3_;
  wire GRANT_O_3_;
  (* init = 1'h0 *)
  wire GRANT_O_REG_0_;
  (* init = 1'h0 *)
  wire GRANT_O_REG_1_;
  (* init = 1'h0 *)
  wire GRANT_O_REG_2_;
  (* init = 1'h0 *)
  wire GRANT_O_REG_3_;
  (* init = 1'h0 *)
  wire GRANT_REG_0_;
  (* init = 1'h0 *)
  wire GRANT_REG_1_;
  (* init = 1'h0 *)
  wire GRANT_REG_2_;
  (* init = 1'h0 *)
  wire GRANT_REG_3_;
  input REQUEST1;
  wire REQUEST1;
  input REQUEST2;
  wire REQUEST2;
  input REQUEST3;
  wire REQUEST3;
  input REQUEST4;
  wire REQUEST4;
  (* init = 1'h0 *)
  wire RU1_REG;
  (* init = 1'h0 *)
  wire RU2_REG;
  (* init = 1'h0 *)
  wire RU3_REG;
  (* init = 1'h0 *)
  wire RU4_REG;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  wire U203;
  wire U204;
  wire U205;
  wire U206;
  wire U207;
  wire U208;
  wire U209;
  wire U210;
  wire U211;
  wire U212;
  wire U213;
  wire U214;
  wire U215;
  wire U216;
  wire U217;
  wire U229;
  wire U230;
  wire U231;
  wire U232;
  wire U233;
  wire U234;
  wire U235;
  wire U236;
  wire U237;
  wire U238;
  wire U239;
  wire U240;
  wire U241;
  wire U242;
  AOI22 _079_ (
    .A0(CODA2_REG_0_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA3_REG_0_),
    .Y(_078_)
  );
  INV _080_ (
    .A(_078_),
    .Y(U206)
  );
  AOI22 _081_ (
    .A0(CODA2_REG_1_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA3_REG_1_),
    .Y(_000_)
  );
  INV _082_ (
    .A(_000_),
    .Y(U207)
  );
  AOI22 _083_ (
    .A0(CODA2_REG_2_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA3_REG_2_),
    .Y(_001_)
  );
  INV _084_ (
    .A(_001_),
    .Y(U208)
  );
  AOI21 _085_ (
    .A0(STATO_REG_1_),
    .A1(CODA3_REG_0_),
    .B0(_077_),
    .Y(_002_)
  );
  AOI22 _086_ (
    .A0(CODA1_REG_0_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA2_REG_0_),
    .Y(_003_)
  );
  NAND2 _087_ (
    .A(_002_),
    .B(_003_),
    .Y(U209)
  );
  AOI21 _088_ (
    .A0(STATO_REG_1_),
    .A1(CODA3_REG_1_),
    .B0(_077_),
    .Y(_004_)
  );
  AOI22 _089_ (
    .A0(CODA1_REG_1_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA2_REG_1_),
    .Y(_005_)
  );
  NAND2 _090_ (
    .A(_004_),
    .B(_005_),
    .Y(U210)
  );
  AOI21 _091_ (
    .A0(STATO_REG_1_),
    .A1(CODA3_REG_2_),
    .B0(_077_),
    .Y(_006_)
  );
  AOI22 _092_ (
    .A0(CODA1_REG_2_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA2_REG_2_),
    .Y(_007_)
  );
  NAND2 _093_ (
    .A(_006_),
    .B(_007_),
    .Y(U211)
  );
  AOI21 _094_ (
    .A0(STATO_REG_1_),
    .A1(CODA2_REG_0_),
    .B0(_077_),
    .Y(_008_)
  );
  AOI22 _095_ (
    .A0(CODA0_REG_0_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA1_REG_0_),
    .Y(_009_)
  );
  NAND2 _096_ (
    .A(_008_),
    .B(_009_),
    .Y(U212)
  );
  AOI21 _097_ (
    .A0(STATO_REG_1_),
    .A1(CODA2_REG_1_),
    .B0(_077_),
    .Y(_010_)
  );
  AOI22 _098_ (
    .A0(CODA0_REG_1_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA1_REG_1_),
    .Y(_011_)
  );
  NAND2 _099_ (
    .A(_010_),
    .B(_011_),
    .Y(U213)
  );
  AOI21 _100_ (
    .A0(STATO_REG_1_),
    .A1(CODA2_REG_2_),
    .B0(_077_),
    .Y(_012_)
  );
  AOI22 _101_ (
    .A0(CODA0_REG_2_),
    .A1(_072_),
    .B0(_076_),
    .B1(CODA1_REG_2_),
    .Y(_013_)
  );
  NAND2 _102_ (
    .A(_012_),
    .B(_013_),
    .Y(U214)
  );
  AOI21 _103_ (
    .A0(_047_),
    .A1(_048_),
    .B0(_072_),
    .Y(_014_)
  );
  NAND2 _104_ (
    .A(CODA0_REG_0_),
    .B(_076_),
    .Y(_015_)
  );
  AOI21 _105_ (
    .A0(STATO_REG_1_),
    .A1(CODA1_REG_0_),
    .B0(_077_),
    .Y(_016_)
  );
  AOI21 _106_ (
    .A0(_014_),
    .A1(_015_),
    .B0(_016_),
    .Y(U215)
  );
  AOI21 _107_ (
    .A0(STATO_REG_1_),
    .A1(CODA1_REG_1_),
    .B0(_077_),
    .Y(_017_)
  );
  NAND2 _108_ (
    .A(CODA0_REG_1_),
    .B(_076_),
    .Y(_018_)
  );
  AOI21 _109_ (
    .A0(_048_),
    .A1(_060_),
    .B0(_072_),
    .Y(_019_)
  );
  AOI21 _110_ (
    .A0(_017_),
    .A1(_018_),
    .B0(_019_),
    .Y(U216)
  );
  AOI21 _111_ (
    .A0(STATO_REG_1_),
    .A1(CODA1_REG_2_),
    .B0(_077_),
    .Y(_020_)
  );
  NAND2 _112_ (
    .A(CODA0_REG_2_),
    .B(_076_),
    .Y(_021_)
  );
  OAI21 _113_ (
    .A0(RU1_REG),
    .A1(_059_),
    .B0(_072_),
    .Y(_022_)
  );
  AOI21 _114_ (
    .A0(_020_),
    .A1(_021_),
    .B0(_022_),
    .Y(U217)
  );
  NOR2 _115_ (
    .A(CODA0_REG_0_),
    .B(CODA0_REG_1_),
    .Y(_023_)
  );
  NAND2 _116_ (
    .A(CODA0_REG_2_),
    .B(_023_),
    .Y(_024_)
  );
  NAND2 _117_ (
    .A(GRANT_REG_3_),
    .B(_075_),
    .Y(_025_)
  );
  OAI21 _118_ (
    .A0(_075_),
    .A1(_024_),
    .B0(_025_),
    .Y(U229)
  );
  NOR2 _119_ (
    .A(CODA0_REG_2_),
    .B(CODA0_REG_0_),
    .Y(_026_)
  );
  NAND2 _120_ (
    .A(CODA0_REG_1_),
    .B(_026_),
    .Y(_027_)
  );
  NAND2 _121_ (
    .A(GRANT_REG_2_),
    .B(_075_),
    .Y(_028_)
  );
  OAI21 _122_ (
    .A0(_075_),
    .A1(_027_),
    .B0(_028_),
    .Y(U230)
  );
  NOR2 _123_ (
    .A(CODA0_REG_2_),
    .B(CODA0_REG_1_),
    .Y(_029_)
  );
  NAND2 _124_ (
    .A(CODA0_REG_0_),
    .B(_029_),
    .Y(_030_)
  );
  NAND2 _125_ (
    .A(GRANT_REG_1_),
    .B(_075_),
    .Y(_031_)
  );
  OAI21 _126_ (
    .A0(_075_),
    .A1(_030_),
    .B0(_031_),
    .Y(U231)
  );
  AOI21 _127_ (
    .A0(CODA0_REG_2_),
    .A1(CODA0_REG_0_),
    .B0(CODA0_REG_1_),
    .Y(_032_)
  );
  NAND2 _128_ (
    .A(GRANT_REG_0_),
    .B(_075_),
    .Y(_033_)
  );
  OAI21 _129_ (
    .A0(_075_),
    .A1(_032_),
    .B0(_033_),
    .Y(U232)
  );
  NAND2 _130_ (
    .A(STATO_REG_0_),
    .B(GRANT_REG_3_),
    .Y(_034_)
  );
  OAI21 _131_ (
    .A0(STATO_REG_0_),
    .A1(_054_),
    .B0(_034_),
    .Y(U233)
  );
  NAND2 _132_ (
    .A(STATO_REG_0_),
    .B(GRANT_REG_2_),
    .Y(_035_)
  );
  OAI21 _133_ (
    .A0(STATO_REG_0_),
    .A1(_055_),
    .B0(_035_),
    .Y(U234)
  );
  NAND2 _134_ (
    .A(STATO_REG_0_),
    .B(GRANT_REG_1_),
    .Y(_036_)
  );
  OAI21 _135_ (
    .A0(STATO_REG_0_),
    .A1(_056_),
    .B0(_036_),
    .Y(U235)
  );
  NAND2 _136_ (
    .A(STATO_REG_0_),
    .B(GRANT_REG_0_),
    .Y(_037_)
  );
  OAI21 _137_ (
    .A0(STATO_REG_0_),
    .A1(_057_),
    .B0(_037_),
    .Y(U236)
  );
  NOR2 _138_ (
    .A(STATO_REG_0_),
    .B(REQUEST3),
    .Y(_038_)
  );
  NOR2 _139_ (
    .A(U203),
    .B(RU3_REG),
    .Y(_039_)
  );
  NOR2 _140_ (
    .A(_038_),
    .B(_039_),
    .Y(U237)
  );
  NOR2 _141_ (
    .A(STATO_REG_0_),
    .B(FU3_REG),
    .Y(_040_)
  );
  NOR2 _142_ (
    .A(_039_),
    .B(_040_),
    .Y(U238)
  );
  NOR2 _143_ (
    .A(STATO_REG_0_),
    .B(REQUEST4),
    .Y(_041_)
  );
  NOR2 _144_ (
    .A(U203),
    .B(RU4_REG),
    .Y(_042_)
  );
  NOR2 _145_ (
    .A(_041_),
    .B(_042_),
    .Y(U239)
  );
  NOR2 _146_ (
    .A(STATO_REG_0_),
    .B(FU2_REG),
    .Y(_043_)
  );
  NOR2 _147_ (
    .A(U203),
    .B(RU2_REG),
    .Y(_044_)
  );
  NOR2 _148_ (
    .A(_043_),
    .B(_044_),
    .Y(U240)
  );
  NOR2 _149_ (
    .A(STATO_REG_0_),
    .B(FU4_REG),
    .Y(_045_)
  );
  NOR2 _150_ (
    .A(_042_),
    .B(_045_),
    .Y(U241)
  );
  NOR2 _151_ (
    .A(STATO_REG_0_),
    .B(REQUEST2),
    .Y(_046_)
  );
  NOR2 _152_ (
    .A(_044_),
    .B(_046_),
    .Y(U242)
  );
  INV _153_ (
    .A(STATO_REG_0_),
    .Y(U203)
  );
  INV _154_ (
    .A(RU2_REG),
    .Y(_047_)
  );
  INV _155_ (
    .A(RU1_REG),
    .Y(_048_)
  );
  INV _156_ (
    .A(FU3_REG),
    .Y(_049_)
  );
  INV _157_ (
    .A(FU2_REG),
    .Y(_050_)
  );
  INV _158_ (
    .A(FU1_REG),
    .Y(_051_)
  );
  INV _159_ (
    .A(FU4_REG),
    .Y(_052_)
  );
  INV _160_ (
    .A(REQUEST1),
    .Y(_053_)
  );
  INV _161_ (
    .A(GRANT_O_REG_3_),
    .Y(_054_)
  );
  INV _162_ (
    .A(GRANT_O_REG_2_),
    .Y(_055_)
  );
  INV _163_ (
    .A(GRANT_O_REG_1_),
    .Y(_056_)
  );
  INV _164_ (
    .A(GRANT_O_REG_0_),
    .Y(_057_)
  );
  NAND2 _165_ (
    .A(STATO_REG_0_),
    .B(RU1_REG),
    .Y(_058_)
  );
  OAI21 _166_ (
    .A0(STATO_REG_0_),
    .A1(_053_),
    .B0(_058_),
    .Y(U204)
  );
  OAI21 _167_ (
    .A0(STATO_REG_0_),
    .A1(_051_),
    .B0(_058_),
    .Y(U205)
  );
  NOR2 _168_ (
    .A(RU2_REG),
    .B(RU3_REG),
    .Y(_059_)
  );
  NAND2 _169_ (
    .A(_047_),
    .B(RU3_REG),
    .Y(_060_)
  );
  AOI21 _170_ (
    .A0(_047_),
    .A1(_049_),
    .B0(RU3_REG),
    .Y(_061_)
  );
  AOI21 _171_ (
    .A0(_052_),
    .A1(RU4_REG),
    .B0(_059_),
    .Y(_062_)
  );
  NOR2 _172_ (
    .A(_047_),
    .B(FU2_REG),
    .Y(_063_)
  );
  NAND2 _173_ (
    .A(RU2_REG),
    .B(_050_),
    .Y(_064_)
  );
  NOR2 _174_ (
    .A(RU1_REG),
    .B(_063_),
    .Y(_065_)
  );
  AOI21 _175_ (
    .A0(_061_),
    .A1(_062_),
    .B0(_064_),
    .Y(_066_)
  );
  AOI21 _176_ (
    .A0(_061_),
    .A1(_062_),
    .B0(_065_),
    .Y(_067_)
  );
  NAND2 _177_ (
    .A(RU1_REG),
    .B(FU1_REG),
    .Y(_068_)
  );
  INV _178_ (
    .A(_068_),
    .Y(_069_)
  );
  NOR2 _179_ (
    .A(U203),
    .B(_069_),
    .Y(_070_)
  );
  OAI21 _180_ (
    .A0(RU1_REG),
    .A1(_066_),
    .B0(_070_),
    .Y(_071_)
  );
  NOR2 _181_ (
    .A(STATO_REG_1_),
    .B(_071_),
    .Y(_072_)
  );
  NOR3 _182_ (
    .A(FU3_REG),
    .B(FU2_REG),
    .C(FU1_REG),
    .Y(_073_)
  );
  NAND2 _183_ (
    .A(_052_),
    .B(_073_),
    .Y(_074_)
  );
  NAND2 _184_ (
    .A(STATO_REG_1_),
    .B(_074_),
    .Y(_075_)
  );
  AOI22 _185_ (
    .A0(_067_),
    .A1(_070_),
    .B0(_074_),
    .B1(STATO_REG_1_),
    .Y(_076_)
  );
  NAND2 _186_ (
    .A(_071_),
    .B(_075_),
    .Y(_077_)
  );
  \$_FF_  _187_ (
    .D(U203),
    .Q(STATO_REG_0_)
  );
  \$_FF_  _188_ (
    .D(U217),
    .Q(CODA0_REG_2_)
  );
  \$_FF_  _189_ (
    .D(U216),
    .Q(CODA0_REG_1_)
  );
  \$_FF_  _190_ (
    .D(U215),
    .Q(CODA0_REG_0_)
  );
  \$_FF_  _191_ (
    .D(U214),
    .Q(CODA1_REG_2_)
  );
  \$_FF_  _192_ (
    .D(U213),
    .Q(CODA1_REG_1_)
  );
  \$_FF_  _193_ (
    .D(U212),
    .Q(CODA1_REG_0_)
  );
  \$_FF_  _194_ (
    .D(U211),
    .Q(CODA2_REG_2_)
  );
  \$_FF_  _195_ (
    .D(U210),
    .Q(CODA2_REG_1_)
  );
  \$_FF_  _196_ (
    .D(U209),
    .Q(CODA2_REG_0_)
  );
  \$_FF_  _197_ (
    .D(U208),
    .Q(CODA3_REG_2_)
  );
  \$_FF_  _198_ (
    .D(U207),
    .Q(CODA3_REG_1_)
  );
  \$_FF_  _199_ (
    .D(U206),
    .Q(CODA3_REG_0_)
  );
  \$_FF_  _200_ (
    .D(U229),
    .Q(GRANT_REG_3_)
  );
  \$_FF_  _201_ (
    .D(U230),
    .Q(GRANT_REG_2_)
  );
  \$_FF_  _202_ (
    .D(U231),
    .Q(GRANT_REG_1_)
  );
  \$_FF_  _203_ (
    .D(U232),
    .Q(GRANT_REG_0_)
  );
  \$_FF_  _204_ (
    .D(U233),
    .Q(GRANT_O_REG_3_)
  );
  \$_FF_  _205_ (
    .D(U234),
    .Q(GRANT_O_REG_2_)
  );
  \$_FF_  _206_ (
    .D(U235),
    .Q(GRANT_O_REG_1_)
  );
  \$_FF_  _207_ (
    .D(U236),
    .Q(GRANT_O_REG_0_)
  );
  \$_FF_  _208_ (
    .D(U237),
    .Q(RU3_REG)
  );
  \$_FF_  _209_ (
    .D(U205),
    .Q(FU1_REG)
  );
  \$_FF_  _210_ (
    .D(U238),
    .Q(FU3_REG)
  );
  \$_FF_  _211_ (
    .D(U204),
    .Q(RU1_REG)
  );
  \$_FF_  _212_ (
    .D(U239),
    .Q(RU4_REG)
  );
  \$_FF_  _213_ (
    .D(U240),
    .Q(FU2_REG)
  );
  \$_FF_  _214_ (
    .D(U241),
    .Q(FU4_REG)
  );
  \$_FF_  _215_ (
    .D(U242),
    .Q(RU2_REG)
  );
  \$_FF_  _216_ (
    .D(STATO_REG_0_),
    .Q(STATO_REG_1_)
  );
  assign GRANT_O_0_ = GRANT_O_REG_0_;
  assign GRANT_O_1_ = GRANT_O_REG_1_;
  assign GRANT_O_2_ = GRANT_O_REG_2_;
  assign GRANT_O_3_ = GRANT_O_REG_3_;
endmodule
