/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b04.blif (RESTART, AVERAGE, ENABLE, DATA_IN_7_, DATA_IN_6_, DATA_IN_5_, DATA_IN_4_, DATA_IN_3_, DATA_IN_2_, DATA_IN_1_, DATA_IN_0_, DATA_OUT_7_, DATA_OUT_6_, DATA_OUT_5_, DATA_OUT_4_, DATA_OUT_3_, DATA_OUT_2_, DATA_OUT_1_, DATA_OUT_0_);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  input AVERAGE;
  wire AVERAGE;
  input DATA_IN_0_;
  wire DATA_IN_0_;
  input DATA_IN_1_;
  wire DATA_IN_1_;
  input DATA_IN_2_;
  wire DATA_IN_2_;
  input DATA_IN_3_;
  wire DATA_IN_3_;
  input DATA_IN_4_;
  wire DATA_IN_4_;
  input DATA_IN_5_;
  wire DATA_IN_5_;
  input DATA_IN_6_;
  wire DATA_IN_6_;
  input DATA_IN_7_;
  wire DATA_IN_7_;
  output DATA_OUT_0_;
  wire DATA_OUT_0_;
  output DATA_OUT_1_;
  wire DATA_OUT_1_;
  output DATA_OUT_2_;
  wire DATA_OUT_2_;
  output DATA_OUT_3_;
  wire DATA_OUT_3_;
  output DATA_OUT_4_;
  wire DATA_OUT_4_;
  output DATA_OUT_5_;
  wire DATA_OUT_5_;
  output DATA_OUT_6_;
  wire DATA_OUT_6_;
  output DATA_OUT_7_;
  wire DATA_OUT_7_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_0_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_1_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_2_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_3_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_4_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_5_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_6_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_7_;
  input ENABLE;
  wire ENABLE;
  (* init = 1'h0 *)
  wire REG1_REG_0_;
  (* init = 1'h0 *)
  wire REG1_REG_1_;
  (* init = 1'h0 *)
  wire REG1_REG_2_;
  (* init = 1'h0 *)
  wire REG1_REG_3_;
  (* init = 1'h0 *)
  wire REG1_REG_4_;
  (* init = 1'h0 *)
  wire REG1_REG_5_;
  (* init = 1'h0 *)
  wire REG1_REG_6_;
  (* init = 1'h0 *)
  wire REG1_REG_7_;
  (* init = 1'h0 *)
  wire REG2_REG_0_;
  (* init = 1'h0 *)
  wire REG2_REG_1_;
  (* init = 1'h0 *)
  wire REG2_REG_2_;
  (* init = 1'h0 *)
  wire REG2_REG_3_;
  (* init = 1'h0 *)
  wire REG2_REG_4_;
  (* init = 1'h0 *)
  wire REG2_REG_5_;
  (* init = 1'h0 *)
  wire REG2_REG_6_;
  (* init = 1'h0 *)
  wire REG2_REG_7_;
  (* init = 1'h0 *)
  wire REG3_REG_0_;
  (* init = 1'h0 *)
  wire REG3_REG_1_;
  (* init = 1'h0 *)
  wire REG3_REG_2_;
  (* init = 1'h0 *)
  wire REG3_REG_3_;
  (* init = 1'h0 *)
  wire REG3_REG_4_;
  (* init = 1'h0 *)
  wire REG3_REG_5_;
  (* init = 1'h0 *)
  wire REG3_REG_6_;
  (* init = 1'h0 *)
  wire REG3_REG_7_;
  (* init = 1'h0 *)
  wire REG4_REG_0_;
  (* init = 1'h0 *)
  wire REG4_REG_1_;
  (* init = 1'h0 *)
  wire REG4_REG_2_;
  (* init = 1'h0 *)
  wire REG4_REG_3_;
  (* init = 1'h0 *)
  wire REG4_REG_4_;
  (* init = 1'h0 *)
  wire REG4_REG_5_;
  (* init = 1'h0 *)
  wire REG4_REG_6_;
  (* init = 1'h0 *)
  wire REG4_REG_7_;
  input RESTART;
  wire RESTART;
  (* init = 1'h0 *)
  wire RLAST_REG_0_;
  (* init = 1'h0 *)
  wire RLAST_REG_1_;
  (* init = 1'h0 *)
  wire RLAST_REG_2_;
  (* init = 1'h0 *)
  wire RLAST_REG_3_;
  (* init = 1'h0 *)
  wire RLAST_REG_4_;
  (* init = 1'h0 *)
  wire RLAST_REG_5_;
  (* init = 1'h0 *)
  wire RLAST_REG_6_;
  (* init = 1'h0 *)
  wire RLAST_REG_7_;
  (* init = 1'h0 *)
  wire RMAX_REG_0_;
  (* init = 1'h0 *)
  wire RMAX_REG_1_;
  (* init = 1'h0 *)
  wire RMAX_REG_2_;
  (* init = 1'h0 *)
  wire RMAX_REG_3_;
  (* init = 1'h0 *)
  wire RMAX_REG_4_;
  (* init = 1'h0 *)
  wire RMAX_REG_5_;
  (* init = 1'h0 *)
  wire RMAX_REG_6_;
  (* init = 1'h0 *)
  wire RMAX_REG_7_;
  (* init = 1'h0 *)
  wire RMIN_REG_0_;
  (* init = 1'h0 *)
  wire RMIN_REG_1_;
  (* init = 1'h0 *)
  wire RMIN_REG_2_;
  (* init = 1'h0 *)
  wire RMIN_REG_3_;
  (* init = 1'h0 *)
  wire RMIN_REG_4_;
  (* init = 1'h0 *)
  wire RMIN_REG_5_;
  (* init = 1'h0 *)
  wire RMIN_REG_6_;
  (* init = 1'h0 *)
  wire RMIN_REG_7_;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  wire U280;
  wire U281;
  wire U282;
  wire U283;
  wire U284;
  wire U285;
  wire U286;
  wire U287;
  wire U288;
  wire U289;
  wire U290;
  wire U291;
  wire U292;
  wire U293;
  wire U294;
  wire U295;
  wire U296;
  wire U297;
  wire U298;
  wire U299;
  wire U300;
  wire U301;
  wire U302;
  wire U303;
  wire U304;
  wire U305;
  wire U306;
  wire U307;
  wire U308;
  wire U309;
  wire U310;
  wire U311;
  wire U312;
  wire U313;
  wire U314;
  wire U315;
  wire U316;
  wire U317;
  wire U318;
  wire U319;
  wire U320;
  wire U321;
  wire U322;
  wire U323;
  wire U324;
  wire U325;
  wire U326;
  wire U327;
  wire U328;
  wire U329;
  wire U330;
  wire U331;
  wire U332;
  wire U333;
  wire U334;
  wire U335;
  wire U336;
  wire U337;
  wire U338;
  wire U339;
  wire U340;
  wire U341;
  wire U342;
  wire U343;
  wire U344;
  wire U375;
  INV _286_ (
    .A(STATO_REG_0_),
    .Y(_000_)
  );
  INV _287_ (
    .A(STATO_REG_1_),
    .Y(_001_)
  );
  INV _288_ (
    .A(RMAX_REG_6_),
    .Y(_002_)
  );
  INV _289_ (
    .A(RMAX_REG_5_),
    .Y(_003_)
  );
  INV _290_ (
    .A(RMAX_REG_4_),
    .Y(_004_)
  );
  INV _291_ (
    .A(RMAX_REG_3_),
    .Y(_005_)
  );
  INV _292_ (
    .A(DATA_IN_3_),
    .Y(_006_)
  );
  INV _293_ (
    .A(RMAX_REG_2_),
    .Y(_007_)
  );
  INV _294_ (
    .A(RMAX_REG_1_),
    .Y(_008_)
  );
  INV _295_ (
    .A(DATA_IN_1_),
    .Y(_009_)
  );
  INV _296_ (
    .A(RMAX_REG_0_),
    .Y(_010_)
  );
  INV _297_ (
    .A(DATA_IN_0_),
    .Y(_011_)
  );
  INV _298_ (
    .A(DATA_IN_7_),
    .Y(_012_)
  );
  INV _299_ (
    .A(RMIN_REG_7_),
    .Y(_013_)
  );
  INV _300_ (
    .A(DATA_IN_6_),
    .Y(_014_)
  );
  INV _301_ (
    .A(RMIN_REG_6_),
    .Y(_015_)
  );
  INV _302_ (
    .A(DATA_IN_5_),
    .Y(_016_)
  );
  INV _303_ (
    .A(RMIN_REG_5_),
    .Y(_017_)
  );
  INV _304_ (
    .A(DATA_IN_4_),
    .Y(_018_)
  );
  INV _305_ (
    .A(RMIN_REG_4_),
    .Y(_019_)
  );
  INV _306_ (
    .A(RMIN_REG_3_),
    .Y(_020_)
  );
  INV _307_ (
    .A(DATA_IN_2_),
    .Y(_021_)
  );
  INV _308_ (
    .A(RMIN_REG_2_),
    .Y(_022_)
  );
  INV _309_ (
    .A(RMIN_REG_1_),
    .Y(_023_)
  );
  INV _310_ (
    .A(REG4_REG_0_),
    .Y(_024_)
  );
  INV _311_ (
    .A(DATA_OUT_REG_6_),
    .Y(_025_)
  );
  INV _312_ (
    .A(REG4_REG_2_),
    .Y(_026_)
  );
  INV _313_ (
    .A(REG4_REG_1_),
    .Y(_027_)
  );
  INV _314_ (
    .A(AVERAGE),
    .Y(_028_)
  );
  INV _315_ (
    .A(RESTART),
    .Y(_029_)
  );
  INV _316_ (
    .A(RMIN_REG_0_),
    .Y(_030_)
  );
  INV _317_ (
    .A(RMAX_REG_7_),
    .Y(_031_)
  );
  NAND2 _318_ (
    .A(RMAX_REG_2_),
    .B(RESTART),
    .Y(_032_)
  );
  OAI21 _319_ (
    .A0(_021_),
    .A1(RESTART),
    .B0(_032_),
    .Y(_033_)
  );
  NAND2 _320_ (
    .A(RMIN_REG_2_),
    .B(RESTART),
    .Y(_034_)
  );
  OAI21 _321_ (
    .A0(_026_),
    .A1(RESTART),
    .B0(_034_),
    .Y(_035_)
  );
  NOR2 _322_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  INV _323_ (
    .A(_036_),
    .Y(_037_)
  );
  NAND2 _324_ (
    .A(_033_),
    .B(_035_),
    .Y(_038_)
  );
  NAND2 _325_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND2 _326_ (
    .A(RMAX_REG_0_),
    .B(RESTART),
    .Y(_040_)
  );
  NAND2 _327_ (
    .A(DATA_IN_0_),
    .B(_029_),
    .Y(_041_)
  );
  OAI21 _328_ (
    .A0(_011_),
    .A1(RESTART),
    .B0(_040_),
    .Y(_042_)
  );
  NAND2 _329_ (
    .A(RESTART),
    .B(RMIN_REG_0_),
    .Y(_043_)
  );
  NAND2 _330_ (
    .A(REG4_REG_0_),
    .B(_029_),
    .Y(_044_)
  );
  OAI21 _331_ (
    .A0(_024_),
    .A1(RESTART),
    .B0(_043_),
    .Y(_045_)
  );
  AOI22 _332_ (
    .A0(_040_),
    .A1(_041_),
    .B0(_043_),
    .B1(_044_),
    .Y(_046_)
  );
  NAND2 _333_ (
    .A(_042_),
    .B(_045_),
    .Y(_047_)
  );
  NAND2 _334_ (
    .A(RMIN_REG_1_),
    .B(RESTART),
    .Y(_048_)
  );
  OAI21 _335_ (
    .A0(_027_),
    .A1(RESTART),
    .B0(_048_),
    .Y(_049_)
  );
  INV _336_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR2 _337_ (
    .A(_046_),
    .B(_049_),
    .Y(_051_)
  );
  NAND2 _338_ (
    .A(_047_),
    .B(_050_),
    .Y(_052_)
  );
  NAND2 _339_ (
    .A(_008_),
    .B(RESTART),
    .Y(_053_)
  );
  OAI21 _340_ (
    .A0(DATA_IN_1_),
    .A1(RESTART),
    .B0(_053_),
    .Y(_054_)
  );
  OAI21 _341_ (
    .A0(_047_),
    .A1(_050_),
    .B0(_054_),
    .Y(_055_)
  );
  NAND2 _342_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  XNOR2 _343_ (
    .A(_039_),
    .B(_056_),
    .Y(_057_)
  );
  INV _344_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR2 _345_ (
    .A(_042_),
    .B(_045_),
    .Y(_059_)
  );
  NOR2 _346_ (
    .A(_046_),
    .B(_059_),
    .Y(_060_)
  );
  XNOR2 _347_ (
    .A(_046_),
    .B(_050_),
    .Y(_061_)
  );
  OAI22 _348_ (
    .A0(_051_),
    .A1(_055_),
    .B0(_061_),
    .B1(_054_),
    .Y(_062_)
  );
  NAND2 _349_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  INV _350_ (
    .A(_063_),
    .Y(_064_)
  );
  NAND2 _351_ (
    .A(_057_),
    .B(_063_),
    .Y(_065_)
  );
  AOI22 _352_ (
    .A0(DATA_IN_0_),
    .A1(REG4_REG_0_),
    .B0(REG4_REG_1_),
    .B1(DATA_IN_1_),
    .Y(_066_)
  );
  OAI22 _353_ (
    .A0(DATA_IN_2_),
    .A1(REG4_REG_2_),
    .B0(REG4_REG_1_),
    .B1(DATA_IN_1_),
    .Y(_067_)
  );
  AOI22 _354_ (
    .A0(DATA_IN_3_),
    .A1(REG4_REG_3_),
    .B0(REG4_REG_2_),
    .B1(DATA_IN_2_),
    .Y(_068_)
  );
  OAI21 _355_ (
    .A0(_066_),
    .A1(_067_),
    .B0(_068_),
    .Y(_069_)
  );
  NOR2 _356_ (
    .A(DATA_IN_4_),
    .B(REG4_REG_4_),
    .Y(_070_)
  );
  OAI21 _357_ (
    .A0(DATA_IN_3_),
    .A1(REG4_REG_3_),
    .B0(_069_),
    .Y(_071_)
  );
  AOI22 _358_ (
    .A0(DATA_IN_4_),
    .A1(REG4_REG_4_),
    .B0(REG4_REG_5_),
    .B1(DATA_IN_5_),
    .Y(_072_)
  );
  OAI21 _359_ (
    .A0(_070_),
    .A1(_071_),
    .B0(_072_),
    .Y(_073_)
  );
  INV _360_ (
    .A(_073_),
    .Y(_074_)
  );
  NOR2 _361_ (
    .A(DATA_IN_6_),
    .B(REG4_REG_6_),
    .Y(_075_)
  );
  OAI22 _362_ (
    .A0(DATA_IN_6_),
    .A1(REG4_REG_6_),
    .B0(REG4_REG_5_),
    .B1(DATA_IN_5_),
    .Y(_076_)
  );
  NAND2 _363_ (
    .A(DATA_IN_6_),
    .B(REG4_REG_6_),
    .Y(_077_)
  );
  OAI22 _364_ (
    .A0(DATA_IN_7_),
    .A1(REG4_REG_7_),
    .B0(_074_),
    .B1(_076_),
    .Y(_078_)
  );
  INV _365_ (
    .A(_078_),
    .Y(_079_)
  );
  AOI22 _366_ (
    .A0(DATA_IN_7_),
    .A1(REG4_REG_7_),
    .B0(_077_),
    .B1(_079_),
    .Y(_080_)
  );
  NOR2 _367_ (
    .A(STATO_REG_0_),
    .B(STATO_REG_1_),
    .Y(U375)
  );
  INV _368_ (
    .A(U375),
    .Y(_081_)
  );
  NOR2 _369_ (
    .A(STATO_REG_0_),
    .B(_001_),
    .Y(_082_)
  );
  NAND2 _370_ (
    .A(_029_),
    .B(_082_),
    .Y(_083_)
  );
  AOI21 _371_ (
    .A0(ENABLE),
    .A1(_029_),
    .B0(_082_),
    .Y(_084_)
  );
  NOR2 _372_ (
    .A(AVERAGE),
    .B(_084_),
    .Y(_085_)
  );
  INV _373_ (
    .A(_085_),
    .Y(_086_)
  );
  AOI22 _374_ (
    .A0(RMAX_REG_1_),
    .A1(RMIN_REG_1_),
    .B0(RMIN_REG_0_),
    .B1(RMAX_REG_0_),
    .Y(_087_)
  );
  OAI22 _375_ (
    .A0(RMAX_REG_2_),
    .A1(RMIN_REG_2_),
    .B0(RMIN_REG_1_),
    .B1(RMAX_REG_1_),
    .Y(_088_)
  );
  AOI22 _376_ (
    .A0(RMAX_REG_3_),
    .A1(RMIN_REG_3_),
    .B0(RMIN_REG_2_),
    .B1(RMAX_REG_2_),
    .Y(_089_)
  );
  OAI21 _377_ (
    .A0(_087_),
    .A1(_088_),
    .B0(_089_),
    .Y(_090_)
  );
  INV _378_ (
    .A(_090_),
    .Y(_091_)
  );
  OAI22 _379_ (
    .A0(RMAX_REG_4_),
    .A1(RMIN_REG_4_),
    .B0(RMIN_REG_3_),
    .B1(RMAX_REG_3_),
    .Y(_092_)
  );
  AOI22 _380_ (
    .A0(RMAX_REG_5_),
    .A1(RMIN_REG_5_),
    .B0(RMIN_REG_4_),
    .B1(RMAX_REG_4_),
    .Y(_093_)
  );
  OAI21 _381_ (
    .A0(_091_),
    .A1(_092_),
    .B0(_093_),
    .Y(_094_)
  );
  INV _382_ (
    .A(_094_),
    .Y(_095_)
  );
  OAI22 _383_ (
    .A0(RMAX_REG_6_),
    .A1(RMIN_REG_6_),
    .B0(RMIN_REG_5_),
    .B1(RMAX_REG_5_),
    .Y(_096_)
  );
  NAND2 _384_ (
    .A(RMAX_REG_6_),
    .B(RMIN_REG_6_),
    .Y(_097_)
  );
  OAI22 _385_ (
    .A0(RMIN_REG_7_),
    .A1(RMAX_REG_7_),
    .B0(_095_),
    .B1(_096_),
    .Y(_098_)
  );
  INV _386_ (
    .A(_098_),
    .Y(_099_)
  );
  AOI22 _387_ (
    .A0(RMIN_REG_7_),
    .A1(RMAX_REG_7_),
    .B0(_097_),
    .B1(_099_),
    .Y(_100_)
  );
  NAND2 _388_ (
    .A(RESTART),
    .B(_082_),
    .Y(_101_)
  );
  INV _389_ (
    .A(_101_),
    .Y(_102_)
  );
  AOI22 _390_ (
    .A0(_080_),
    .A1(_085_),
    .B0(_100_),
    .B1(_102_),
    .Y(_103_)
  );
  INV _391_ (
    .A(_103_),
    .Y(_104_)
  );
  OAI22 _392_ (
    .A0(_080_),
    .A1(_086_),
    .B0(_100_),
    .B1(_101_),
    .Y(_105_)
  );
  INV _393_ (
    .A(_105_),
    .Y(_106_)
  );
  NAND2 _394_ (
    .A(_058_),
    .B(_064_),
    .Y(_107_)
  );
  NOR2 _395_ (
    .A(_028_),
    .B(_084_),
    .Y(_108_)
  );
  NOR2 _396_ (
    .A(_000_),
    .B(STATO_REG_1_),
    .Y(_109_)
  );
  NOR2 _397_ (
    .A(_082_),
    .B(_109_),
    .Y(_110_)
  );
  INV _398_ (
    .A(_110_),
    .Y(U280)
  );
  NAND2 _399_ (
    .A(DATA_OUT_REG_1_),
    .B(_110_),
    .Y(_111_)
  );
  NOR2 _400_ (
    .A(ENABLE),
    .B(_083_),
    .Y(_112_)
  );
  NOR2 _401_ (
    .A(_060_),
    .B(_062_),
    .Y(_113_)
  );
  AOI21 _402_ (
    .A0(_065_),
    .A1(_105_),
    .B0(_107_),
    .Y(_114_)
  );
  AOI22 _403_ (
    .A0(REG4_REG_1_),
    .A1(_108_),
    .B0(_112_),
    .B1(RLAST_REG_1_),
    .Y(_115_)
  );
  OAI21 _404_ (
    .A0(_057_),
    .A1(_103_),
    .B0(_115_),
    .Y(_116_)
  );
  INV _405_ (
    .A(_116_),
    .Y(_117_)
  );
  AOI21 _406_ (
    .A0(_111_),
    .A1(_114_),
    .B0(_117_),
    .Y(U282)
  );
  AOI22 _407_ (
    .A0(REG4_REG_2_),
    .A1(_108_),
    .B0(_110_),
    .B1(DATA_OUT_REG_2_),
    .Y(_118_)
  );
  AOI21 _408_ (
    .A0(_037_),
    .A1(_052_),
    .B0(_055_),
    .Y(_119_)
  );
  NAND2 _409_ (
    .A(_038_),
    .B(_119_),
    .Y(_120_)
  );
  NAND2 _410_ (
    .A(RMAX_REG_3_),
    .B(RESTART),
    .Y(_121_)
  );
  OAI21 _411_ (
    .A0(_006_),
    .A1(RESTART),
    .B0(_121_),
    .Y(_122_)
  );
  INV _412_ (
    .A(_122_),
    .Y(_123_)
  );
  NAND2 _413_ (
    .A(REG4_REG_3_),
    .B(_029_),
    .Y(_124_)
  );
  OAI21 _414_ (
    .A0(_020_),
    .A1(_029_),
    .B0(_124_),
    .Y(_125_)
  );
  INV _415_ (
    .A(_125_),
    .Y(_126_)
  );
  NOR2 _416_ (
    .A(_123_),
    .B(_126_),
    .Y(_127_)
  );
  NOR2 _417_ (
    .A(_122_),
    .B(_125_),
    .Y(_128_)
  );
  NOR2 _418_ (
    .A(_127_),
    .B(_128_),
    .Y(_129_)
  );
  AOI22 _419_ (
    .A0(_038_),
    .A1(_119_),
    .B0(_123_),
    .B1(_126_),
    .Y(_130_)
  );
  NOR2 _420_ (
    .A(_127_),
    .B(_130_),
    .Y(_131_)
  );
  XNOR2 _421_ (
    .A(_120_),
    .B(_129_),
    .Y(_132_)
  );
  NOR2 _422_ (
    .A(_103_),
    .B(_132_),
    .Y(_133_)
  );
  INV _423_ (
    .A(_133_),
    .Y(_134_)
  );
  AOI21 _424_ (
    .A0(_057_),
    .A1(_113_),
    .B0(_132_),
    .Y(_135_)
  );
  XOR2 _425_ (
    .A(_107_),
    .B(_132_),
    .Y(_136_)
  );
  AOI22 _426_ (
    .A0(RLAST_REG_2_),
    .A1(_112_),
    .B0(_136_),
    .B1(_105_),
    .Y(_137_)
  );
  AOI21 _427_ (
    .A0(_118_),
    .A1(_134_),
    .B0(_137_),
    .Y(U283)
  );
  NAND2 _428_ (
    .A(RLAST_REG_3_),
    .B(_112_),
    .Y(_138_)
  );
  AOI22 _429_ (
    .A0(REG4_REG_3_),
    .A1(_108_),
    .B0(_110_),
    .B1(DATA_OUT_REG_3_),
    .Y(_139_)
  );
  NAND2 _430_ (
    .A(RMAX_REG_4_),
    .B(RESTART),
    .Y(_140_)
  );
  OAI21 _431_ (
    .A0(_018_),
    .A1(RESTART),
    .B0(_140_),
    .Y(_141_)
  );
  NAND2 _432_ (
    .A(REG4_REG_4_),
    .B(_029_),
    .Y(_142_)
  );
  OAI21 _433_ (
    .A0(_019_),
    .A1(_029_),
    .B0(_142_),
    .Y(_143_)
  );
  NAND2 _434_ (
    .A(_141_),
    .B(_143_),
    .Y(_144_)
  );
  NOR2 _435_ (
    .A(_141_),
    .B(_143_),
    .Y(_145_)
  );
  XOR2 _436_ (
    .A(_141_),
    .B(_143_),
    .Y(_146_)
  );
  OAI21 _437_ (
    .A0(_131_),
    .A1(_145_),
    .B0(_144_),
    .Y(_147_)
  );
  XNOR2 _438_ (
    .A(_131_),
    .B(_146_),
    .Y(_148_)
  );
  XOR2 _439_ (
    .A(_131_),
    .B(_146_),
    .Y(_149_)
  );
  OAI21 _440_ (
    .A0(_107_),
    .A1(_132_),
    .B0(_149_),
    .Y(_150_)
  );
  NOR3 _441_ (
    .A(_107_),
    .B(_132_),
    .C(_149_),
    .Y(_151_)
  );
  OAI22 _442_ (
    .A0(_103_),
    .A1(_149_),
    .B0(_151_),
    .B1(_106_),
    .Y(_152_)
  );
  NAND2 _443_ (
    .A(_150_),
    .B(_152_),
    .Y(_153_)
  );
  NOR2 _444_ (
    .A(_135_),
    .B(_148_),
    .Y(_154_)
  );
  NOR2 _445_ (
    .A(_151_),
    .B(_154_),
    .Y(_155_)
  );
  AOI21 _446_ (
    .A0(_138_),
    .A1(_139_),
    .B0(_153_),
    .Y(U284)
  );
  NAND2 _447_ (
    .A(RMAX_REG_5_),
    .B(RESTART),
    .Y(_156_)
  );
  OAI21 _448_ (
    .A0(_016_),
    .A1(RESTART),
    .B0(_156_),
    .Y(_157_)
  );
  NAND2 _449_ (
    .A(REG4_REG_5_),
    .B(_029_),
    .Y(_158_)
  );
  OAI21 _450_ (
    .A0(_017_),
    .A1(_029_),
    .B0(_158_),
    .Y(_159_)
  );
  NAND2 _451_ (
    .A(_157_),
    .B(_159_),
    .Y(_160_)
  );
  INV _452_ (
    .A(_160_),
    .Y(_161_)
  );
  NOR2 _453_ (
    .A(_157_),
    .B(_159_),
    .Y(_162_)
  );
  INV _454_ (
    .A(_162_),
    .Y(_163_)
  );
  NOR2 _455_ (
    .A(_161_),
    .B(_162_),
    .Y(_164_)
  );
  OAI21 _456_ (
    .A0(_147_),
    .A1(_161_),
    .B0(_163_),
    .Y(_165_)
  );
  XNOR2 _457_ (
    .A(_147_),
    .B(_164_),
    .Y(_166_)
  );
  NAND2 _458_ (
    .A(_154_),
    .B(_166_),
    .Y(_167_)
  );
  XNOR2 _459_ (
    .A(_154_),
    .B(_166_),
    .Y(_168_)
  );
  OAI21 _460_ (
    .A0(_151_),
    .A1(_154_),
    .B0(_168_),
    .Y(_169_)
  );
  NAND2 _461_ (
    .A(_155_),
    .B(_166_),
    .Y(_170_)
  );
  AOI21 _462_ (
    .A0(_105_),
    .A1(_169_),
    .B0(_170_),
    .Y(_171_)
  );
  NAND2 _463_ (
    .A(RLAST_REG_4_),
    .B(_112_),
    .Y(_172_)
  );
  AOI22 _464_ (
    .A0(REG4_REG_4_),
    .A1(_108_),
    .B0(_110_),
    .B1(DATA_OUT_REG_4_),
    .Y(_173_)
  );
  OAI21 _465_ (
    .A0(_103_),
    .A1(_166_),
    .B0(_173_),
    .Y(_174_)
  );
  INV _466_ (
    .A(_174_),
    .Y(_175_)
  );
  AOI21 _467_ (
    .A0(_171_),
    .A1(_172_),
    .B0(_175_),
    .Y(U285)
  );
  XOR2 _468_ (
    .A(RMAX_REG_6_),
    .B(RMIN_REG_6_),
    .Y(_176_)
  );
  NOR2 _469_ (
    .A(RESTART),
    .B(_075_),
    .Y(_177_)
  );
  AOI22 _470_ (
    .A0(RESTART),
    .A1(_176_),
    .B0(_177_),
    .B1(_077_),
    .Y(_178_)
  );
  XNOR2 _471_ (
    .A(_165_),
    .B(_178_),
    .Y(_179_)
  );
  INV _472_ (
    .A(_179_),
    .Y(_180_)
  );
  XNOR2 _473_ (
    .A(_167_),
    .B(_179_),
    .Y(_181_)
  );
  XNOR2 _474_ (
    .A(_169_),
    .B(_181_),
    .Y(_182_)
  );
  NOR2 _475_ (
    .A(_103_),
    .B(_179_),
    .Y(_183_)
  );
  NAND2 _476_ (
    .A(REG4_REG_5_),
    .B(_108_),
    .Y(_184_)
  );
  AOI22 _477_ (
    .A0(DATA_OUT_REG_5_),
    .A1(_110_),
    .B0(_112_),
    .B1(RLAST_REG_5_),
    .Y(_185_)
  );
  NAND2 _478_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  NOR2 _479_ (
    .A(_183_),
    .B(_186_),
    .Y(_187_)
  );
  OAI21 _480_ (
    .A0(_106_),
    .A1(_182_),
    .B0(_187_),
    .Y(U286)
  );
  AOI22 _481_ (
    .A0(REG4_REG_6_),
    .A1(_108_),
    .B0(_112_),
    .B1(RLAST_REG_6_),
    .Y(_188_)
  );
  OAI21 _482_ (
    .A0(_025_),
    .A1(U280),
    .B0(_188_),
    .Y(_189_)
  );
  INV _483_ (
    .A(_189_),
    .Y(_190_)
  );
  AOI21 _484_ (
    .A0(_105_),
    .A1(_167_),
    .B0(_180_),
    .Y(_191_)
  );
  OAI21 _485_ (
    .A0(_169_),
    .A1(_191_),
    .B0(_190_),
    .Y(U287)
  );
  NAND2 _486_ (
    .A(REG4_REG_7_),
    .B(_108_),
    .Y(_192_)
  );
  AOI22 _487_ (
    .A0(DATA_OUT_REG_7_),
    .A1(_110_),
    .B0(_112_),
    .B1(RLAST_REG_7_),
    .Y(_193_)
  );
  NAND2 _488_ (
    .A(_192_),
    .B(_193_),
    .Y(U288)
  );
  AOI22 _489_ (
    .A0(REG3_REG_0_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_0_),
    .Y(_194_)
  );
  INV _490_ (
    .A(_194_),
    .Y(U289)
  );
  AOI22 _491_ (
    .A0(REG3_REG_1_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_1_),
    .Y(_195_)
  );
  INV _492_ (
    .A(_195_),
    .Y(U290)
  );
  AOI22 _493_ (
    .A0(REG3_REG_2_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_2_),
    .Y(_196_)
  );
  INV _494_ (
    .A(_196_),
    .Y(U291)
  );
  AOI22 _495_ (
    .A0(REG3_REG_3_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_3_),
    .Y(_197_)
  );
  INV _496_ (
    .A(_197_),
    .Y(U292)
  );
  AOI22 _497_ (
    .A0(REG3_REG_4_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_4_),
    .Y(_198_)
  );
  INV _498_ (
    .A(_198_),
    .Y(U293)
  );
  AOI22 _499_ (
    .A0(REG3_REG_5_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_5_),
    .Y(_199_)
  );
  INV _500_ (
    .A(_199_),
    .Y(U294)
  );
  AOI22 _501_ (
    .A0(REG3_REG_6_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_6_),
    .Y(_200_)
  );
  INV _502_ (
    .A(_200_),
    .Y(U295)
  );
  AOI22 _503_ (
    .A0(REG3_REG_7_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG4_REG_7_),
    .Y(_201_)
  );
  INV _504_ (
    .A(_201_),
    .Y(U296)
  );
  AOI22 _505_ (
    .A0(REG2_REG_0_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_0_),
    .Y(_202_)
  );
  INV _506_ (
    .A(_202_),
    .Y(U297)
  );
  AOI22 _507_ (
    .A0(REG2_REG_1_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_1_),
    .Y(_203_)
  );
  INV _508_ (
    .A(_203_),
    .Y(U298)
  );
  AOI22 _509_ (
    .A0(REG2_REG_2_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_2_),
    .Y(_204_)
  );
  INV _510_ (
    .A(_204_),
    .Y(U299)
  );
  AOI22 _511_ (
    .A0(REG2_REG_3_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_3_),
    .Y(_205_)
  );
  INV _512_ (
    .A(_205_),
    .Y(U300)
  );
  AOI22 _513_ (
    .A0(REG2_REG_4_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_4_),
    .Y(_206_)
  );
  INV _514_ (
    .A(_206_),
    .Y(U301)
  );
  AOI22 _515_ (
    .A0(REG2_REG_5_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_5_),
    .Y(_207_)
  );
  INV _516_ (
    .A(_207_),
    .Y(U302)
  );
  AOI22 _517_ (
    .A0(REG2_REG_6_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_6_),
    .Y(_208_)
  );
  INV _518_ (
    .A(_208_),
    .Y(U303)
  );
  AOI22 _519_ (
    .A0(REG2_REG_7_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG3_REG_7_),
    .Y(_209_)
  );
  INV _520_ (
    .A(_209_),
    .Y(U304)
  );
  AOI22 _521_ (
    .A0(REG1_REG_0_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_0_),
    .Y(_210_)
  );
  INV _522_ (
    .A(_210_),
    .Y(U305)
  );
  AOI22 _523_ (
    .A0(REG1_REG_1_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_1_),
    .Y(_211_)
  );
  INV _524_ (
    .A(_211_),
    .Y(U306)
  );
  AOI22 _525_ (
    .A0(REG1_REG_2_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_2_),
    .Y(_212_)
  );
  INV _526_ (
    .A(_212_),
    .Y(U307)
  );
  AOI22 _527_ (
    .A0(REG1_REG_3_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_3_),
    .Y(_213_)
  );
  INV _528_ (
    .A(_213_),
    .Y(U308)
  );
  AOI22 _529_ (
    .A0(REG1_REG_4_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_4_),
    .Y(_214_)
  );
  INV _530_ (
    .A(_214_),
    .Y(U309)
  );
  AOI22 _531_ (
    .A0(REG1_REG_5_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_5_),
    .Y(_215_)
  );
  INV _532_ (
    .A(_215_),
    .Y(U310)
  );
  AOI22 _533_ (
    .A0(REG1_REG_6_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_6_),
    .Y(_216_)
  );
  INV _534_ (
    .A(_216_),
    .Y(U311)
  );
  AOI22 _535_ (
    .A0(REG1_REG_7_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG2_REG_7_),
    .Y(_217_)
  );
  INV _536_ (
    .A(_217_),
    .Y(U312)
  );
  AOI22 _537_ (
    .A0(DATA_IN_0_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_0_),
    .Y(_218_)
  );
  INV _538_ (
    .A(_218_),
    .Y(U313)
  );
  AOI22 _539_ (
    .A0(DATA_IN_1_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_1_),
    .Y(_219_)
  );
  INV _540_ (
    .A(_219_),
    .Y(U314)
  );
  AOI22 _541_ (
    .A0(DATA_IN_2_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_2_),
    .Y(_220_)
  );
  INV _542_ (
    .A(_220_),
    .Y(U315)
  );
  AOI22 _543_ (
    .A0(DATA_IN_3_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_3_),
    .Y(_221_)
  );
  INV _544_ (
    .A(_221_),
    .Y(U316)
  );
  AOI22 _545_ (
    .A0(DATA_IN_4_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_4_),
    .Y(_222_)
  );
  INV _546_ (
    .A(_222_),
    .Y(U317)
  );
  AOI22 _547_ (
    .A0(DATA_IN_5_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_5_),
    .Y(_223_)
  );
  INV _548_ (
    .A(_223_),
    .Y(U318)
  );
  AOI22 _549_ (
    .A0(DATA_IN_6_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_6_),
    .Y(_224_)
  );
  INV _550_ (
    .A(_224_),
    .Y(U319)
  );
  AOI22 _551_ (
    .A0(DATA_IN_7_),
    .A1(_082_),
    .B0(_110_),
    .B1(REG1_REG_7_),
    .Y(_225_)
  );
  INV _552_ (
    .A(_225_),
    .Y(U320)
  );
  NOR2 _553_ (
    .A(STATO_REG_0_),
    .B(ENABLE),
    .Y(_226_)
  );
  NOR2 _554_ (
    .A(_001_),
    .B(_226_),
    .Y(_227_)
  );
  OAI21 _555_ (
    .A0(STATO_REG_0_),
    .A1(ENABLE),
    .B0(_081_),
    .Y(_228_)
  );
  AOI22 _556_ (
    .A0(DATA_IN_0_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_0_),
    .Y(_229_)
  );
  INV _557_ (
    .A(_229_),
    .Y(U321)
  );
  AOI22 _558_ (
    .A0(DATA_IN_1_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_1_),
    .Y(_230_)
  );
  INV _559_ (
    .A(_230_),
    .Y(U322)
  );
  AOI22 _560_ (
    .A0(DATA_IN_2_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_2_),
    .Y(_231_)
  );
  INV _561_ (
    .A(_231_),
    .Y(U323)
  );
  AOI22 _562_ (
    .A0(DATA_IN_3_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_3_),
    .Y(_232_)
  );
  INV _563_ (
    .A(_232_),
    .Y(U324)
  );
  AOI22 _564_ (
    .A0(DATA_IN_4_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_4_),
    .Y(_233_)
  );
  INV _565_ (
    .A(_233_),
    .Y(U325)
  );
  AOI22 _566_ (
    .A0(DATA_IN_5_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_5_),
    .Y(_234_)
  );
  INV _567_ (
    .A(_234_),
    .Y(U326)
  );
  AOI22 _568_ (
    .A0(DATA_IN_6_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_6_),
    .Y(_235_)
  );
  INV _569_ (
    .A(_235_),
    .Y(U327)
  );
  AOI22 _570_ (
    .A0(DATA_IN_7_),
    .A1(_227_),
    .B0(_228_),
    .B1(RLAST_REG_7_),
    .Y(_236_)
  );
  INV _571_ (
    .A(_236_),
    .Y(U328)
  );
  NOR2 _572_ (
    .A(_008_),
    .B(DATA_IN_1_),
    .Y(_237_)
  );
  NOR3 _573_ (
    .A(RMAX_REG_0_),
    .B(_011_),
    .C(_237_),
    .Y(_238_)
  );
  OAI22 _574_ (
    .A0(RMAX_REG_1_),
    .A1(_009_),
    .B0(_021_),
    .B1(RMAX_REG_2_),
    .Y(_239_)
  );
  AOI22 _575_ (
    .A0(RMAX_REG_3_),
    .A1(_006_),
    .B0(RMAX_REG_2_),
    .B1(_021_),
    .Y(_240_)
  );
  OAI21 _576_ (
    .A0(_238_),
    .A1(_239_),
    .B0(_240_),
    .Y(_241_)
  );
  AOI22 _577_ (
    .A0(_005_),
    .A1(DATA_IN_3_),
    .B0(DATA_IN_4_),
    .B1(_004_),
    .Y(_242_)
  );
  AOI22 _578_ (
    .A0(RMAX_REG_5_),
    .A1(_016_),
    .B0(_241_),
    .B1(_242_),
    .Y(_243_)
  );
  OAI21 _579_ (
    .A0(_004_),
    .A1(DATA_IN_4_),
    .B0(_243_),
    .Y(_244_)
  );
  AOI22 _580_ (
    .A0(_002_),
    .A1(DATA_IN_6_),
    .B0(DATA_IN_5_),
    .B1(_003_),
    .Y(_245_)
  );
  NAND2 _581_ (
    .A(_244_),
    .B(_245_),
    .Y(_246_)
  );
  AOI22 _582_ (
    .A0(RMAX_REG_6_),
    .A1(_014_),
    .B0(_031_),
    .B1(DATA_IN_7_),
    .Y(_247_)
  );
  AOI22 _583_ (
    .A0(_012_),
    .A1(RMAX_REG_7_),
    .B0(_246_),
    .B1(_247_),
    .Y(_248_)
  );
  NOR2 _584_ (
    .A(_009_),
    .B(RMIN_REG_1_),
    .Y(_249_)
  );
  NOR3 _585_ (
    .A(DATA_IN_0_),
    .B(_030_),
    .C(_249_),
    .Y(_250_)
  );
  OAI22 _586_ (
    .A0(DATA_IN_2_),
    .A1(_022_),
    .B0(_023_),
    .B1(DATA_IN_1_),
    .Y(_251_)
  );
  AOI22 _587_ (
    .A0(DATA_IN_3_),
    .A1(_020_),
    .B0(DATA_IN_2_),
    .B1(_022_),
    .Y(_252_)
  );
  OAI21 _588_ (
    .A0(_250_),
    .A1(_251_),
    .B0(_252_),
    .Y(_253_)
  );
  AOI22 _589_ (
    .A0(_018_),
    .A1(RMIN_REG_4_),
    .B0(RMIN_REG_3_),
    .B1(_006_),
    .Y(_254_)
  );
  AOI22 _590_ (
    .A0(DATA_IN_4_),
    .A1(_019_),
    .B0(_253_),
    .B1(_254_),
    .Y(_255_)
  );
  OAI21 _591_ (
    .A0(_016_),
    .A1(RMIN_REG_5_),
    .B0(_255_),
    .Y(_256_)
  );
  AOI22 _592_ (
    .A0(_014_),
    .A1(RMIN_REG_6_),
    .B0(_016_),
    .B1(RMIN_REG_5_),
    .Y(_257_)
  );
  NAND2 _593_ (
    .A(DATA_IN_6_),
    .B(_015_),
    .Y(_258_)
  );
  AOI22 _594_ (
    .A0(_012_),
    .A1(RMIN_REG_7_),
    .B0(_256_),
    .B1(_257_),
    .Y(_259_)
  );
  AOI22 _595_ (
    .A0(DATA_IN_7_),
    .A1(_013_),
    .B0(_258_),
    .B1(_259_),
    .Y(_260_)
  );
  NAND2 _596_ (
    .A(STATO_REG_1_),
    .B(_248_),
    .Y(_261_)
  );
  OAI21 _597_ (
    .A0(_260_),
    .A1(_261_),
    .B0(_000_),
    .Y(_262_)
  );
  NAND2 _598_ (
    .A(DATA_IN_0_),
    .B(_262_),
    .Y(_263_)
  );
  OAI21 _599_ (
    .A0(_030_),
    .A1(_262_),
    .B0(_263_),
    .Y(U329)
  );
  NAND2 _600_ (
    .A(DATA_IN_1_),
    .B(_262_),
    .Y(_264_)
  );
  OAI21 _601_ (
    .A0(_023_),
    .A1(_262_),
    .B0(_264_),
    .Y(U330)
  );
  NAND2 _602_ (
    .A(DATA_IN_2_),
    .B(_262_),
    .Y(_265_)
  );
  OAI21 _603_ (
    .A0(_022_),
    .A1(_262_),
    .B0(_265_),
    .Y(U331)
  );
  NAND2 _604_ (
    .A(DATA_IN_3_),
    .B(_262_),
    .Y(_266_)
  );
  OAI21 _605_ (
    .A0(_020_),
    .A1(_262_),
    .B0(_266_),
    .Y(U332)
  );
  NAND2 _606_ (
    .A(DATA_IN_4_),
    .B(_262_),
    .Y(_267_)
  );
  OAI21 _607_ (
    .A0(_019_),
    .A1(_262_),
    .B0(_267_),
    .Y(U333)
  );
  NAND2 _608_ (
    .A(DATA_IN_5_),
    .B(_262_),
    .Y(_268_)
  );
  OAI21 _609_ (
    .A0(_017_),
    .A1(_262_),
    .B0(_268_),
    .Y(U334)
  );
  NAND2 _610_ (
    .A(DATA_IN_6_),
    .B(_262_),
    .Y(_269_)
  );
  OAI21 _611_ (
    .A0(_015_),
    .A1(_262_),
    .B0(_269_),
    .Y(U335)
  );
  NAND2 _612_ (
    .A(DATA_IN_7_),
    .B(_262_),
    .Y(_270_)
  );
  OAI21 _613_ (
    .A0(_013_),
    .A1(_262_),
    .B0(_270_),
    .Y(U336)
  );
  OAI21 _614_ (
    .A0(_001_),
    .A1(_248_),
    .B0(_000_),
    .Y(_271_)
  );
  NAND2 _615_ (
    .A(DATA_IN_0_),
    .B(_271_),
    .Y(_272_)
  );
  OAI21 _616_ (
    .A0(_010_),
    .A1(_271_),
    .B0(_272_),
    .Y(U337)
  );
  NAND2 _617_ (
    .A(DATA_IN_1_),
    .B(_271_),
    .Y(_273_)
  );
  OAI21 _618_ (
    .A0(_008_),
    .A1(_271_),
    .B0(_273_),
    .Y(U338)
  );
  NAND2 _619_ (
    .A(DATA_IN_2_),
    .B(_271_),
    .Y(_274_)
  );
  OAI21 _620_ (
    .A0(_007_),
    .A1(_271_),
    .B0(_274_),
    .Y(U339)
  );
  NAND2 _621_ (
    .A(DATA_IN_3_),
    .B(_271_),
    .Y(_275_)
  );
  OAI21 _622_ (
    .A0(_005_),
    .A1(_271_),
    .B0(_275_),
    .Y(U340)
  );
  NAND2 _623_ (
    .A(DATA_IN_4_),
    .B(_271_),
    .Y(_276_)
  );
  OAI21 _624_ (
    .A0(_004_),
    .A1(_271_),
    .B0(_276_),
    .Y(U341)
  );
  NAND2 _625_ (
    .A(DATA_IN_5_),
    .B(_271_),
    .Y(_277_)
  );
  OAI21 _626_ (
    .A0(_003_),
    .A1(_271_),
    .B0(_277_),
    .Y(U342)
  );
  NAND2 _627_ (
    .A(DATA_IN_6_),
    .B(_271_),
    .Y(_278_)
  );
  OAI21 _628_ (
    .A0(_002_),
    .A1(_271_),
    .B0(_278_),
    .Y(U343)
  );
  NAND2 _629_ (
    .A(DATA_IN_7_),
    .B(_271_),
    .Y(_279_)
  );
  OAI21 _630_ (
    .A0(_031_),
    .A1(_271_),
    .B0(_279_),
    .Y(U344)
  );
  NAND2 _631_ (
    .A(_062_),
    .B(_104_),
    .Y(_280_)
  );
  NOR3 _632_ (
    .A(_064_),
    .B(_106_),
    .C(_113_),
    .Y(_281_)
  );
  NAND2 _633_ (
    .A(REG4_REG_0_),
    .B(_108_),
    .Y(_282_)
  );
  AOI22 _634_ (
    .A0(DATA_OUT_REG_0_),
    .A1(_110_),
    .B0(_112_),
    .B1(RLAST_REG_0_),
    .Y(_283_)
  );
  NAND2 _635_ (
    .A(_282_),
    .B(_283_),
    .Y(_284_)
  );
  NOR2 _636_ (
    .A(_281_),
    .B(_284_),
    .Y(_285_)
  );
  NAND2 _637_ (
    .A(_280_),
    .B(_285_),
    .Y(U281)
  );
  \$_FF_  _638_ (
    .D(U344),
    .Q(RMAX_REG_7_)
  );
  \$_FF_  _639_ (
    .D(U343),
    .Q(RMAX_REG_6_)
  );
  \$_FF_  _640_ (
    .D(U342),
    .Q(RMAX_REG_5_)
  );
  \$_FF_  _641_ (
    .D(U341),
    .Q(RMAX_REG_4_)
  );
  \$_FF_  _642_ (
    .D(U340),
    .Q(RMAX_REG_3_)
  );
  \$_FF_  _643_ (
    .D(U339),
    .Q(RMAX_REG_2_)
  );
  \$_FF_  _644_ (
    .D(U338),
    .Q(RMAX_REG_1_)
  );
  \$_FF_  _645_ (
    .D(U337),
    .Q(RMAX_REG_0_)
  );
  \$_FF_  _646_ (
    .D(U336),
    .Q(RMIN_REG_7_)
  );
  \$_FF_  _647_ (
    .D(U335),
    .Q(RMIN_REG_6_)
  );
  \$_FF_  _648_ (
    .D(U334),
    .Q(RMIN_REG_5_)
  );
  \$_FF_  _649_ (
    .D(U333),
    .Q(RMIN_REG_4_)
  );
  \$_FF_  _650_ (
    .D(U332),
    .Q(RMIN_REG_3_)
  );
  \$_FF_  _651_ (
    .D(U331),
    .Q(RMIN_REG_2_)
  );
  \$_FF_  _652_ (
    .D(U330),
    .Q(RMIN_REG_1_)
  );
  \$_FF_  _653_ (
    .D(U329),
    .Q(RMIN_REG_0_)
  );
  \$_FF_  _654_ (
    .D(U328),
    .Q(RLAST_REG_7_)
  );
  \$_FF_  _655_ (
    .D(U327),
    .Q(RLAST_REG_6_)
  );
  \$_FF_  _656_ (
    .D(U326),
    .Q(RLAST_REG_5_)
  );
  \$_FF_  _657_ (
    .D(U325),
    .Q(RLAST_REG_4_)
  );
  \$_FF_  _658_ (
    .D(U324),
    .Q(RLAST_REG_3_)
  );
  \$_FF_  _659_ (
    .D(U323),
    .Q(RLAST_REG_2_)
  );
  \$_FF_  _660_ (
    .D(U322),
    .Q(RLAST_REG_1_)
  );
  \$_FF_  _661_ (
    .D(U321),
    .Q(RLAST_REG_0_)
  );
  \$_FF_  _662_ (
    .D(U320),
    .Q(REG1_REG_7_)
  );
  \$_FF_  _663_ (
    .D(U319),
    .Q(REG1_REG_6_)
  );
  \$_FF_  _664_ (
    .D(U318),
    .Q(REG1_REG_5_)
  );
  \$_FF_  _665_ (
    .D(U317),
    .Q(REG1_REG_4_)
  );
  \$_FF_  _666_ (
    .D(U316),
    .Q(REG1_REG_3_)
  );
  \$_FF_  _667_ (
    .D(U315),
    .Q(REG1_REG_2_)
  );
  \$_FF_  _668_ (
    .D(U314),
    .Q(REG1_REG_1_)
  );
  \$_FF_  _669_ (
    .D(U313),
    .Q(REG1_REG_0_)
  );
  \$_FF_  _670_ (
    .D(U312),
    .Q(REG2_REG_7_)
  );
  \$_FF_  _671_ (
    .D(U311),
    .Q(REG2_REG_6_)
  );
  \$_FF_  _672_ (
    .D(U310),
    .Q(REG2_REG_5_)
  );
  \$_FF_  _673_ (
    .D(U309),
    .Q(REG2_REG_4_)
  );
  \$_FF_  _674_ (
    .D(U308),
    .Q(REG2_REG_3_)
  );
  \$_FF_  _675_ (
    .D(U307),
    .Q(REG2_REG_2_)
  );
  \$_FF_  _676_ (
    .D(U306),
    .Q(REG2_REG_1_)
  );
  \$_FF_  _677_ (
    .D(U305),
    .Q(REG2_REG_0_)
  );
  \$_FF_  _678_ (
    .D(U304),
    .Q(REG3_REG_7_)
  );
  \$_FF_  _679_ (
    .D(U303),
    .Q(REG3_REG_6_)
  );
  \$_FF_  _680_ (
    .D(U302),
    .Q(REG3_REG_5_)
  );
  \$_FF_  _681_ (
    .D(U301),
    .Q(REG3_REG_4_)
  );
  \$_FF_  _682_ (
    .D(U300),
    .Q(REG3_REG_3_)
  );
  \$_FF_  _683_ (
    .D(U299),
    .Q(REG3_REG_2_)
  );
  \$_FF_  _684_ (
    .D(U298),
    .Q(REG3_REG_1_)
  );
  \$_FF_  _685_ (
    .D(U297),
    .Q(REG3_REG_0_)
  );
  \$_FF_  _686_ (
    .D(U296),
    .Q(REG4_REG_7_)
  );
  \$_FF_  _687_ (
    .D(U295),
    .Q(REG4_REG_6_)
  );
  \$_FF_  _688_ (
    .D(U294),
    .Q(REG4_REG_5_)
  );
  \$_FF_  _689_ (
    .D(U293),
    .Q(REG4_REG_4_)
  );
  \$_FF_  _690_ (
    .D(U292),
    .Q(REG4_REG_3_)
  );
  \$_FF_  _691_ (
    .D(U291),
    .Q(REG4_REG_2_)
  );
  \$_FF_  _692_ (
    .D(U290),
    .Q(REG4_REG_1_)
  );
  \$_FF_  _693_ (
    .D(U289),
    .Q(REG4_REG_0_)
  );
  \$_FF_  _694_ (
    .D(U288),
    .Q(DATA_OUT_REG_7_)
  );
  \$_FF_  _695_ (
    .D(U287),
    .Q(DATA_OUT_REG_6_)
  );
  \$_FF_  _696_ (
    .D(U286),
    .Q(DATA_OUT_REG_5_)
  );
  \$_FF_  _697_ (
    .D(U285),
    .Q(DATA_OUT_REG_4_)
  );
  \$_FF_  _698_ (
    .D(U284),
    .Q(DATA_OUT_REG_3_)
  );
  \$_FF_  _699_ (
    .D(U283),
    .Q(DATA_OUT_REG_2_)
  );
  \$_FF_  _700_ (
    .D(U282),
    .Q(DATA_OUT_REG_1_)
  );
  \$_FF_  _701_ (
    .D(U281),
    .Q(DATA_OUT_REG_0_)
  );
  \$_FF_  _702_ (
    .D(U280),
    .Q(STATO_REG_1_)
  );
  \$_FF_  _703_ (
    .D(U375),
    .Q(STATO_REG_0_)
  );
  assign DATA_OUT_0_ = DATA_OUT_REG_0_;
  assign DATA_OUT_1_ = DATA_OUT_REG_1_;
  assign DATA_OUT_2_ = DATA_OUT_REG_2_;
  assign DATA_OUT_3_ = DATA_OUT_REG_3_;
  assign DATA_OUT_4_ = DATA_OUT_REG_4_;
  assign DATA_OUT_5_ = DATA_OUT_REG_5_;
  assign DATA_OUT_6_ = DATA_OUT_REG_6_;
  assign DATA_OUT_7_ = DATA_OUT_REG_7_;
endmodule
