/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b06.blif (EQL, CONT_EQL, CC_MUX_2_, CC_MUX_1_, USCITE_2_, USCITE_1_, ENABLE_COUNT, ACKOUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  output ACKOUT;
  wire ACKOUT;
  wire ACKOUT_REG;
  output CC_MUX_1_;
  wire CC_MUX_1_;
  output CC_MUX_2_;
  wire CC_MUX_2_;
  (* init = 1'h0 *)
  wire CC_MUX_REG_1_;
  (* init = 1'h0 *)
  wire CC_MUX_REG_2_;
  input CONT_EQL;
  wire CONT_EQL;
  output ENABLE_COUNT;
  wire ENABLE_COUNT;
  (* init = 1'h0 *)
  wire ENABLE_COUNT_REG;
  input EQL;
  wire EQL;
  (* init = 1'h0 *)
  wire STATE_REG_0_;
  (* init = 1'h0 *)
  wire STATE_REG_1_;
  (* init = 1'h0 *)
  wire STATE_REG_2_;
  wire U55;
  wire U56;
  wire U57;
  wire U58;
  wire U59;
  wire U60;
  wire U61;
  wire U62;
  output USCITE_1_;
  wire USCITE_1_;
  output USCITE_2_;
  wire USCITE_2_;
  (* init = 1'h0 *)
  wire USCITE_REG_1_;
  (* init = 1'h0 *)
  wire USCITE_REG_2_;
  INV _25_ (
    .A(STATE_REG_2_),
    .Y(_00_)
  );
  INV _26_ (
    .A(STATE_REG_1_),
    .Y(_01_)
  );
  INV _27_ (
    .A(STATE_REG_0_),
    .Y(_02_)
  );
  INV _28_ (
    .A(EQL),
    .Y(_03_)
  );
  NAND2 _29_ (
    .A(STATE_REG_1_),
    .B(STATE_REG_0_),
    .Y(_04_)
  );
  INV _30_ (
    .A(_04_),
    .Y(_05_)
  );
  NOR2 _31_ (
    .A(_00_),
    .B(STATE_REG_0_),
    .Y(_06_)
  );
  NOR2 _32_ (
    .A(STATE_REG_2_),
    .B(STATE_REG_0_),
    .Y(_07_)
  );
  NOR3 _33_ (
    .A(STATE_REG_2_),
    .B(STATE_REG_1_),
    .C(STATE_REG_0_),
    .Y(_08_)
  );
  NOR2 _34_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  OAI21 _35_ (
    .A0(STATE_REG_1_),
    .A1(STATE_REG_0_),
    .B0(_03_),
    .Y(_10_)
  );
  NAND2 _36_ (
    .A(_09_),
    .B(_10_),
    .Y(U55)
  );
  NOR2 _37_ (
    .A(STATE_REG_2_),
    .B(_02_),
    .Y(_11_)
  );
  NOR2 _38_ (
    .A(STATE_REG_2_),
    .B(_01_),
    .Y(_12_)
  );
  OAI22 _39_ (
    .A0(_02_),
    .A1(EQL),
    .B0(_11_),
    .B1(_12_),
    .Y(_13_)
  );
  NOR2 _40_ (
    .A(STATE_REG_1_),
    .B(EQL),
    .Y(_14_)
  );
  NAND2 _41_ (
    .A(_06_),
    .B(_14_),
    .Y(_15_)
  );
  NOR2 _42_ (
    .A(_01_),
    .B(_03_),
    .Y(_16_)
  );
  NAND2 _43_ (
    .A(STATE_REG_1_),
    .B(EQL),
    .Y(_17_)
  );
  AOI21 _44_ (
    .A0(_13_),
    .A1(_15_),
    .B0(_17_),
    .Y(U56)
  );
  NAND2 _45_ (
    .A(STATE_REG_2_),
    .B(_10_),
    .Y(_18_)
  );
  NOR3 _46_ (
    .A(STATE_REG_2_),
    .B(_02_),
    .C(EQL),
    .Y(_19_)
  );
  NAND2 _47_ (
    .A(_01_),
    .B(_19_),
    .Y(_20_)
  );
  NAND2 _48_ (
    .A(_18_),
    .B(_20_),
    .Y(U57)
  );
  OAI22 _49_ (
    .A0(_14_),
    .A1(_16_),
    .B0(_19_),
    .B1(_06_),
    .Y(U58)
  );
  OAI21 _50_ (
    .A0(_11_),
    .A1(_16_),
    .B0(_04_),
    .Y(_21_)
  );
  NAND2 _51_ (
    .A(_18_),
    .B(_21_),
    .Y(U59)
  );
  NAND2 _52_ (
    .A(STATE_REG_2_),
    .B(STATE_REG_1_),
    .Y(_22_)
  );
  AOI21 _53_ (
    .A0(EQL),
    .A1(_09_),
    .B0(_22_),
    .Y(U60)
  );
  OAI21 _54_ (
    .A0(_00_),
    .A1(_17_),
    .B0(_15_),
    .Y(U61)
  );
  AOI21 _55_ (
    .A0(STATE_REG_1_),
    .A1(_03_),
    .B0(_07_),
    .Y(_23_)
  );
  NOR2 _56_ (
    .A(_00_),
    .B(_04_),
    .Y(_24_)
  );
  OAI21 _57_ (
    .A0(CONT_EQL),
    .A1(_24_),
    .B0(_23_),
    .Y(U62)
  );
  \$_FF_  _58_ (
    .D(U57),
    .Q(STATE_REG_2_)
  );
  \$_FF_  _59_ (
    .D(U56),
    .Q(STATE_REG_1_)
  );
  \$_FF_  _60_ (
    .D(U55),
    .Q(STATE_REG_0_)
  );
  \$_FF_  _61_ (
    .D(U59),
    .Q(CC_MUX_REG_2_)
  );
  \$_FF_  _62_ (
    .D(U58),
    .Q(CC_MUX_REG_1_)
  );
  \$_FF_  _63_ (
    .D(U61),
    .Q(USCITE_REG_2_)
  );
  \$_FF_  _64_ (
    .D(U60),
    .Q(USCITE_REG_1_)
  );
  \$_FF_  _65_ (
    .D(U62),
    .Q(ENABLE_COUNT_REG)
  );
  assign CC_MUX_2_ = CC_MUX_REG_2_;
  assign ENABLE_COUNT = ENABLE_COUNT_REG;
  assign CC_MUX_1_ = CC_MUX_REG_1_;
  assign ACKOUT = ENABLE_COUNT_REG;
  assign ACKOUT_REG = ENABLE_COUNT_REG;
  assign USCITE_1_ = USCITE_REG_1_;
  assign USCITE_2_ = USCITE_REG_2_;
endmodule
