/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b08.blif (START, I_7_, I_6_, I_5_, I_4_, I_3_, I_2_, I_1_, I_0_, O_3_, O_2_, O_1_, O_0_);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  (* init = 1'h0 *)
  wire IN_R_REG_0_;
  (* init = 1'h0 *)
  wire IN_R_REG_1_;
  (* init = 1'h0 *)
  wire IN_R_REG_2_;
  (* init = 1'h0 *)
  wire IN_R_REG_3_;
  (* init = 1'h0 *)
  wire IN_R_REG_4_;
  (* init = 1'h0 *)
  wire IN_R_REG_5_;
  (* init = 1'h0 *)
  wire IN_R_REG_6_;
  (* init = 1'h0 *)
  wire IN_R_REG_7_;
  input I_0_;
  wire I_0_;
  input I_1_;
  wire I_1_;
  input I_2_;
  wire I_2_;
  input I_3_;
  wire I_3_;
  input I_4_;
  wire I_4_;
  input I_5_;
  wire I_5_;
  input I_6_;
  wire I_6_;
  input I_7_;
  wire I_7_;
  (* init = 1'h0 *)
  wire MAR_REG_0_;
  (* init = 1'h0 *)
  wire MAR_REG_1_;
  (* init = 1'h0 *)
  wire MAR_REG_2_;
  (* init = 1'h0 *)
  wire OUT_R_REG_0_;
  (* init = 1'h0 *)
  wire OUT_R_REG_1_;
  (* init = 1'h0 *)
  wire OUT_R_REG_2_;
  (* init = 1'h0 *)
  wire OUT_R_REG_3_;
  output O_0_;
  wire O_0_;
  output O_1_;
  wire O_1_;
  output O_2_;
  wire O_2_;
  output O_3_;
  wire O_3_;
  (* init = 1'h0 *)
  wire O_REG_0_;
  (* init = 1'h0 *)
  wire O_REG_1_;
  (* init = 1'h0 *)
  wire O_REG_2_;
  (* init = 1'h0 *)
  wire O_REG_3_;
  input START;
  wire START;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  wire U183;
  wire U184;
  wire U185;
  wire U186;
  wire U187;
  wire U188;
  wire U189;
  wire U206;
  wire U207;
  wire U208;
  wire U209;
  wire U210;
  wire U211;
  wire U212;
  wire U213;
  wire U214;
  wire U215;
  wire U216;
  wire U217;
  wire U218;
  wire U219;
  INV _089_ (
    .A(IN_R_REG_7_),
    .Y(_041_)
  );
  INV _090_ (
    .A(IN_R_REG_5_),
    .Y(_042_)
  );
  INV _091_ (
    .A(IN_R_REG_1_),
    .Y(_043_)
  );
  INV _092_ (
    .A(IN_R_REG_0_),
    .Y(_044_)
  );
  INV _093_ (
    .A(IN_R_REG_2_),
    .Y(_045_)
  );
  INV _094_ (
    .A(IN_R_REG_6_),
    .Y(_046_)
  );
  INV _095_ (
    .A(IN_R_REG_4_),
    .Y(_047_)
  );
  INV _096_ (
    .A(O_REG_3_),
    .Y(_048_)
  );
  INV _097_ (
    .A(OUT_R_REG_3_),
    .Y(_049_)
  );
  INV _098_ (
    .A(O_REG_2_),
    .Y(_050_)
  );
  INV _099_ (
    .A(OUT_R_REG_2_),
    .Y(_051_)
  );
  INV _100_ (
    .A(O_REG_1_),
    .Y(_052_)
  );
  INV _101_ (
    .A(OUT_R_REG_1_),
    .Y(_053_)
  );
  INV _102_ (
    .A(O_REG_0_),
    .Y(_054_)
  );
  INV _103_ (
    .A(OUT_R_REG_0_),
    .Y(_055_)
  );
  INV _104_ (
    .A(STATO_REG_1_),
    .Y(_056_)
  );
  INV _105_ (
    .A(MAR_REG_0_),
    .Y(_057_)
  );
  INV _106_ (
    .A(MAR_REG_1_),
    .Y(_058_)
  );
  INV _107_ (
    .A(MAR_REG_2_),
    .Y(_059_)
  );
  INV _108_ (
    .A(IN_R_REG_3_),
    .Y(_060_)
  );
  NOR2 _109_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_0_),
    .Y(_061_)
  );
  NOR2 _110_ (
    .A(STATO_REG_1_),
    .B(_061_),
    .Y(_062_)
  );
  NAND2 _111_ (
    .A(_057_),
    .B(MAR_REG_1_),
    .Y(_063_)
  );
  NOR2 _112_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_2_),
    .Y(_064_)
  );
  NOR3 _113_ (
    .A(MAR_REG_0_),
    .B(MAR_REG_1_),
    .C(MAR_REG_2_),
    .Y(_065_)
  );
  NAND2 _114_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_2_),
    .Y(_066_)
  );
  NOR2 _115_ (
    .A(_058_),
    .B(MAR_REG_2_),
    .Y(_067_)
  );
  NOR2 _116_ (
    .A(_057_),
    .B(MAR_REG_1_),
    .Y(_068_)
  );
  XNOR2 _117_ (
    .A(MAR_REG_0_),
    .B(MAR_REG_1_),
    .Y(_069_)
  );
  NAND2 _118_ (
    .A(MAR_REG_2_),
    .B(_069_),
    .Y(_070_)
  );
  NAND2 _119_ (
    .A(MAR_REG_0_),
    .B(MAR_REG_2_),
    .Y(_071_)
  );
  INV _120_ (
    .A(_071_),
    .Y(_072_)
  );
  NOR2 _121_ (
    .A(MAR_REG_1_),
    .B(_071_),
    .Y(_073_)
  );
  NOR2 _122_ (
    .A(_057_),
    .B(MAR_REG_2_),
    .Y(_074_)
  );
  NAND2 _123_ (
    .A(MAR_REG_0_),
    .B(MAR_REG_1_),
    .Y(_075_)
  );
  AOI21 _124_ (
    .A0(MAR_REG_0_),
    .A1(MAR_REG_1_),
    .B0(_059_),
    .Y(_076_)
  );
  NAND2 _125_ (
    .A(IN_R_REG_2_),
    .B(_076_),
    .Y(_077_)
  );
  NOR2 _126_ (
    .A(_073_),
    .B(_077_),
    .Y(_078_)
  );
  OAI21 _127_ (
    .A0(MAR_REG_1_),
    .A1(_071_),
    .B0(IN_R_REG_1_),
    .Y(_079_)
  );
  OAI21 _128_ (
    .A0(MAR_REG_2_),
    .A1(_075_),
    .B0(_042_),
    .Y(_080_)
  );
  OAI22 _129_ (
    .A0(MAR_REG_2_),
    .A1(_069_),
    .B0(_079_),
    .B1(_080_),
    .Y(_081_)
  );
  AOI21 _130_ (
    .A0(_057_),
    .A1(MAR_REG_1_),
    .B0(_059_),
    .Y(_082_)
  );
  AOI22 _131_ (
    .A0(IN_R_REG_0_),
    .A1(_076_),
    .B0(_082_),
    .B1(_041_),
    .Y(_083_)
  );
  OAI22 _132_ (
    .A0(IN_R_REG_2_),
    .A1(_081_),
    .B0(_083_),
    .B1(_068_),
    .Y(_084_)
  );
  OAI21 _133_ (
    .A0(_078_),
    .A1(_084_),
    .B0(_070_),
    .Y(_085_)
  );
  INV _134_ (
    .A(_085_),
    .Y(_086_)
  );
  NAND2 _135_ (
    .A(_059_),
    .B(_075_),
    .Y(_087_)
  );
  OAI22 _136_ (
    .A0(IN_R_REG_0_),
    .A1(MAR_REG_1_),
    .B0(_087_),
    .B1(_043_),
    .Y(_088_)
  );
  NOR2 _137_ (
    .A(_086_),
    .B(_088_),
    .Y(_000_)
  );
  NOR2 _138_ (
    .A(MAR_REG_0_),
    .B(_066_),
    .Y(_001_)
  );
  AOI22 _139_ (
    .A0(_057_),
    .A1(_064_),
    .B0(_066_),
    .B1(_087_),
    .Y(_002_)
  );
  AOI22 _140_ (
    .A0(_057_),
    .A1(_067_),
    .B0(_069_),
    .B1(MAR_REG_2_),
    .Y(_003_)
  );
  NOR2 _141_ (
    .A(IN_R_REG_6_),
    .B(_074_),
    .Y(_004_)
  );
  AOI22 _142_ (
    .A0(IN_R_REG_6_),
    .A1(_002_),
    .B0(_003_),
    .B1(_004_),
    .Y(_005_)
  );
  NOR2 _143_ (
    .A(_001_),
    .B(_005_),
    .Y(_006_)
  );
  NAND2 _144_ (
    .A(IN_R_REG_4_),
    .B(MAR_REG_1_),
    .Y(_007_)
  );
  AOI22 _145_ (
    .A0(IN_R_REG_4_),
    .A1(_074_),
    .B0(_076_),
    .B1(_007_),
    .Y(_008_)
  );
  NAND2 _146_ (
    .A(MAR_REG_1_),
    .B(_072_),
    .Y(_009_)
  );
  INV _147_ (
    .A(_009_),
    .Y(_010_)
  );
  OAI21 _148_ (
    .A0(_064_),
    .A1(_010_),
    .B0(IN_R_REG_7_),
    .Y(_011_)
  );
  OAI21 _149_ (
    .A0(IN_R_REG_5_),
    .A1(MAR_REG_2_),
    .B0(IN_R_REG_3_),
    .Y(_012_)
  );
  NOR2 _150_ (
    .A(_067_),
    .B(_072_),
    .Y(_013_)
  );
  NAND2 _151_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NOR2 _152_ (
    .A(_056_),
    .B(STATO_REG_0_),
    .Y(_015_)
  );
  AOI21 _153_ (
    .A0(_011_),
    .A1(_014_),
    .B0(_015_),
    .Y(_016_)
  );
  NOR3 _154_ (
    .A(_006_),
    .B(_008_),
    .C(_016_),
    .Y(_017_)
  );
  OAI21 _155_ (
    .A0(_065_),
    .A1(_000_),
    .B0(_017_),
    .Y(_018_)
  );
  OAI22 _156_ (
    .A0(_055_),
    .A1(_062_),
    .B0(_063_),
    .B1(_018_),
    .Y(U183)
  );
  OAI22 _157_ (
    .A0(_053_),
    .A1(_062_),
    .B0(_072_),
    .B1(_018_),
    .Y(U184)
  );
  OAI22 _158_ (
    .A0(_051_),
    .A1(_062_),
    .B0(_003_),
    .B1(_018_),
    .Y(U185)
  );
  NAND2 _159_ (
    .A(_063_),
    .B(_002_),
    .Y(_019_)
  );
  INV _160_ (
    .A(_019_),
    .Y(_020_)
  );
  OAI22 _161_ (
    .A0(_049_),
    .A1(_062_),
    .B0(_018_),
    .B1(_020_),
    .Y(U186)
  );
  NAND2 _162_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_0_),
    .Y(_021_)
  );
  OAI22 _163_ (
    .A0(_059_),
    .A1(_062_),
    .B0(_076_),
    .B1(_021_),
    .Y(U187)
  );
  OAI21 _164_ (
    .A0(_056_),
    .A1(_009_),
    .B0(STATO_REG_0_),
    .Y(_022_)
  );
  NAND2 _165_ (
    .A(START),
    .B(_022_),
    .Y(_023_)
  );
  OAI21 _166_ (
    .A0(_056_),
    .A1(STATO_REG_0_),
    .B0(_023_),
    .Y(U188)
  );
  NOR3 _167_ (
    .A(START),
    .B(_009_),
    .C(_021_),
    .Y(_024_)
  );
  NOR2 _168_ (
    .A(_061_),
    .B(_024_),
    .Y(U189)
  );
  NOR2 _169_ (
    .A(_056_),
    .B(MAR_REG_0_),
    .Y(_025_)
  );
  NOR2 _170_ (
    .A(_022_),
    .B(_025_),
    .Y(_026_)
  );
  AOI21 _171_ (
    .A0(STATO_REG_1_),
    .A1(STATO_REG_0_),
    .B0(_068_),
    .Y(_027_)
  );
  OAI21 _172_ (
    .A0(_058_),
    .A1(_026_),
    .B0(_027_),
    .Y(U206)
  );
  NOR2 _173_ (
    .A(STATO_REG_0_),
    .B(MAR_REG_0_),
    .Y(_028_)
  );
  NOR2 _174_ (
    .A(_026_),
    .B(_028_),
    .Y(U207)
  );
  NAND2 _175_ (
    .A(I_7_),
    .B(_062_),
    .Y(_029_)
  );
  OAI21 _176_ (
    .A0(_041_),
    .A1(_062_),
    .B0(_029_),
    .Y(U208)
  );
  NAND2 _177_ (
    .A(I_6_),
    .B(_062_),
    .Y(_030_)
  );
  OAI21 _178_ (
    .A0(_046_),
    .A1(_062_),
    .B0(_030_),
    .Y(U209)
  );
  NAND2 _179_ (
    .A(I_5_),
    .B(_062_),
    .Y(_031_)
  );
  OAI21 _180_ (
    .A0(_042_),
    .A1(_062_),
    .B0(_031_),
    .Y(U210)
  );
  NAND2 _181_ (
    .A(I_4_),
    .B(_062_),
    .Y(_032_)
  );
  OAI21 _182_ (
    .A0(_047_),
    .A1(_062_),
    .B0(_032_),
    .Y(U211)
  );
  NAND2 _183_ (
    .A(I_3_),
    .B(_062_),
    .Y(_033_)
  );
  OAI21 _184_ (
    .A0(_060_),
    .A1(_062_),
    .B0(_033_),
    .Y(U212)
  );
  NAND2 _185_ (
    .A(I_2_),
    .B(_062_),
    .Y(_034_)
  );
  OAI21 _186_ (
    .A0(_045_),
    .A1(_062_),
    .B0(_034_),
    .Y(U213)
  );
  NAND2 _187_ (
    .A(I_1_),
    .B(_062_),
    .Y(_035_)
  );
  OAI21 _188_ (
    .A0(_043_),
    .A1(_062_),
    .B0(_035_),
    .Y(U214)
  );
  NAND2 _189_ (
    .A(I_0_),
    .B(_062_),
    .Y(_036_)
  );
  OAI21 _190_ (
    .A0(_044_),
    .A1(_062_),
    .B0(_036_),
    .Y(U215)
  );
  NAND2 _191_ (
    .A(OUT_R_REG_3_),
    .B(_024_),
    .Y(_037_)
  );
  OAI21 _192_ (
    .A0(_048_),
    .A1(_024_),
    .B0(_037_),
    .Y(U216)
  );
  NAND2 _193_ (
    .A(OUT_R_REG_2_),
    .B(_024_),
    .Y(_038_)
  );
  OAI21 _194_ (
    .A0(_050_),
    .A1(_024_),
    .B0(_038_),
    .Y(U217)
  );
  NAND2 _195_ (
    .A(OUT_R_REG_1_),
    .B(_024_),
    .Y(_039_)
  );
  OAI21 _196_ (
    .A0(_052_),
    .A1(_024_),
    .B0(_039_),
    .Y(U218)
  );
  NAND2 _197_ (
    .A(OUT_R_REG_0_),
    .B(_024_),
    .Y(_040_)
  );
  OAI21 _198_ (
    .A0(_054_),
    .A1(_024_),
    .B0(_040_),
    .Y(U219)
  );
  \$_FF_  _199_ (
    .D(U219),
    .Q(O_REG_0_)
  );
  \$_FF_  _200_ (
    .D(U189),
    .Q(STATO_REG_1_)
  );
  \$_FF_  _201_ (
    .D(U188),
    .Q(STATO_REG_0_)
  );
  \$_FF_  _202_ (
    .D(U187),
    .Q(MAR_REG_2_)
  );
  \$_FF_  _203_ (
    .D(U206),
    .Q(MAR_REG_1_)
  );
  \$_FF_  _204_ (
    .D(U207),
    .Q(MAR_REG_0_)
  );
  \$_FF_  _205_ (
    .D(U208),
    .Q(IN_R_REG_7_)
  );
  \$_FF_  _206_ (
    .D(U209),
    .Q(IN_R_REG_6_)
  );
  \$_FF_  _207_ (
    .D(U210),
    .Q(IN_R_REG_5_)
  );
  \$_FF_  _208_ (
    .D(U211),
    .Q(IN_R_REG_4_)
  );
  \$_FF_  _209_ (
    .D(U212),
    .Q(IN_R_REG_3_)
  );
  \$_FF_  _210_ (
    .D(U213),
    .Q(IN_R_REG_2_)
  );
  \$_FF_  _211_ (
    .D(U214),
    .Q(IN_R_REG_1_)
  );
  \$_FF_  _212_ (
    .D(U215),
    .Q(IN_R_REG_0_)
  );
  \$_FF_  _213_ (
    .D(U186),
    .Q(OUT_R_REG_3_)
  );
  \$_FF_  _214_ (
    .D(U185),
    .Q(OUT_R_REG_2_)
  );
  \$_FF_  _215_ (
    .D(U184),
    .Q(OUT_R_REG_1_)
  );
  \$_FF_  _216_ (
    .D(U183),
    .Q(OUT_R_REG_0_)
  );
  \$_FF_  _217_ (
    .D(U216),
    .Q(O_REG_3_)
  );
  \$_FF_  _218_ (
    .D(U217),
    .Q(O_REG_2_)
  );
  \$_FF_  _219_ (
    .D(U218),
    .Q(O_REG_1_)
  );
  assign O_0_ = O_REG_0_;
  assign O_1_ = O_REG_1_;
  assign O_2_ = O_REG_2_;
  assign O_3_ = O_REG_3_;
endmodule
