/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b04.blif (RESTART, AVERAGE, ENABLE, DATA_IN_7_, DATA_IN_6_, DATA_IN_5_, DATA_IN_4_, DATA_IN_3_, DATA_IN_2_, DATA_IN_1_, DATA_IN_0_, DATA_OUT_7_, DATA_OUT_6_, DATA_OUT_5_, DATA_OUT_4_, DATA_OUT_3_, DATA_OUT_2_, DATA_OUT_1_, DATA_OUT_0_);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  input AVERAGE;
  wire AVERAGE;
  input DATA_IN_0_;
  wire DATA_IN_0_;
  input DATA_IN_1_;
  wire DATA_IN_1_;
  input DATA_IN_2_;
  wire DATA_IN_2_;
  input DATA_IN_3_;
  wire DATA_IN_3_;
  input DATA_IN_4_;
  wire DATA_IN_4_;
  input DATA_IN_5_;
  wire DATA_IN_5_;
  input DATA_IN_6_;
  wire DATA_IN_6_;
  input DATA_IN_7_;
  wire DATA_IN_7_;
  output DATA_OUT_0_;
  wire DATA_OUT_0_;
  output DATA_OUT_1_;
  wire DATA_OUT_1_;
  output DATA_OUT_2_;
  wire DATA_OUT_2_;
  output DATA_OUT_3_;
  wire DATA_OUT_3_;
  output DATA_OUT_4_;
  wire DATA_OUT_4_;
  output DATA_OUT_5_;
  wire DATA_OUT_5_;
  output DATA_OUT_6_;
  wire DATA_OUT_6_;
  output DATA_OUT_7_;
  wire DATA_OUT_7_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_0_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_1_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_2_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_3_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_4_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_5_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_6_;
  (* init = 1'h0 *)
  wire DATA_OUT_REG_7_;
  input ENABLE;
  wire ENABLE;
  (* init = 1'h0 *)
  wire REG1_REG_0_;
  (* init = 1'h0 *)
  wire REG1_REG_1_;
  (* init = 1'h0 *)
  wire REG1_REG_2_;
  (* init = 1'h0 *)
  wire REG1_REG_3_;
  (* init = 1'h0 *)
  wire REG1_REG_4_;
  (* init = 1'h0 *)
  wire REG1_REG_5_;
  (* init = 1'h0 *)
  wire REG1_REG_6_;
  (* init = 1'h0 *)
  wire REG1_REG_7_;
  (* init = 1'h0 *)
  wire REG2_REG_0_;
  (* init = 1'h0 *)
  wire REG2_REG_1_;
  (* init = 1'h0 *)
  wire REG2_REG_2_;
  (* init = 1'h0 *)
  wire REG2_REG_3_;
  (* init = 1'h0 *)
  wire REG2_REG_4_;
  (* init = 1'h0 *)
  wire REG2_REG_5_;
  (* init = 1'h0 *)
  wire REG2_REG_6_;
  (* init = 1'h0 *)
  wire REG2_REG_7_;
  (* init = 1'h0 *)
  wire REG3_REG_0_;
  (* init = 1'h0 *)
  wire REG3_REG_1_;
  (* init = 1'h0 *)
  wire REG3_REG_2_;
  (* init = 1'h0 *)
  wire REG3_REG_3_;
  (* init = 1'h0 *)
  wire REG3_REG_4_;
  (* init = 1'h0 *)
  wire REG3_REG_5_;
  (* init = 1'h0 *)
  wire REG3_REG_6_;
  (* init = 1'h0 *)
  wire REG3_REG_7_;
  (* init = 1'h0 *)
  wire REG4_REG_0_;
  (* init = 1'h0 *)
  wire REG4_REG_1_;
  (* init = 1'h0 *)
  wire REG4_REG_2_;
  (* init = 1'h0 *)
  wire REG4_REG_3_;
  (* init = 1'h0 *)
  wire REG4_REG_4_;
  (* init = 1'h0 *)
  wire REG4_REG_5_;
  (* init = 1'h0 *)
  wire REG4_REG_6_;
  (* init = 1'h0 *)
  wire REG4_REG_7_;
  input RESTART;
  wire RESTART;
  (* init = 1'h0 *)
  wire RLAST_REG_0_;
  (* init = 1'h0 *)
  wire RLAST_REG_1_;
  (* init = 1'h0 *)
  wire RLAST_REG_2_;
  (* init = 1'h0 *)
  wire RLAST_REG_3_;
  (* init = 1'h0 *)
  wire RLAST_REG_4_;
  (* init = 1'h0 *)
  wire RLAST_REG_5_;
  (* init = 1'h0 *)
  wire RLAST_REG_6_;
  (* init = 1'h0 *)
  wire RLAST_REG_7_;
  (* init = 1'h0 *)
  wire RMAX_REG_0_;
  (* init = 1'h0 *)
  wire RMAX_REG_1_;
  (* init = 1'h0 *)
  wire RMAX_REG_2_;
  (* init = 1'h0 *)
  wire RMAX_REG_3_;
  (* init = 1'h0 *)
  wire RMAX_REG_4_;
  (* init = 1'h0 *)
  wire RMAX_REG_5_;
  (* init = 1'h0 *)
  wire RMAX_REG_6_;
  (* init = 1'h0 *)
  wire RMAX_REG_7_;
  (* init = 1'h0 *)
  wire RMIN_REG_0_;
  (* init = 1'h0 *)
  wire RMIN_REG_1_;
  (* init = 1'h0 *)
  wire RMIN_REG_2_;
  (* init = 1'h0 *)
  wire RMIN_REG_3_;
  (* init = 1'h0 *)
  wire RMIN_REG_4_;
  (* init = 1'h0 *)
  wire RMIN_REG_5_;
  (* init = 1'h0 *)
  wire RMIN_REG_6_;
  (* init = 1'h0 *)
  wire RMIN_REG_7_;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  wire U280;
  wire U281;
  wire U282;
  wire U283;
  wire U284;
  wire U285;
  wire U286;
  wire U287;
  wire U288;
  wire U289;
  wire U290;
  wire U291;
  wire U292;
  wire U293;
  wire U294;
  wire U295;
  wire U296;
  wire U297;
  wire U298;
  wire U299;
  wire U300;
  wire U301;
  wire U302;
  wire U303;
  wire U304;
  wire U305;
  wire U306;
  wire U307;
  wire U308;
  wire U309;
  wire U310;
  wire U311;
  wire U312;
  wire U313;
  wire U314;
  wire U315;
  wire U316;
  wire U317;
  wire U318;
  wire U319;
  wire U320;
  wire U321;
  wire U322;
  wire U323;
  wire U324;
  wire U325;
  wire U326;
  wire U327;
  wire U328;
  wire U329;
  wire U330;
  wire U331;
  wire U332;
  wire U333;
  wire U334;
  wire U335;
  wire U336;
  wire U337;
  wire U338;
  wire U339;
  wire U340;
  wire U341;
  wire U342;
  wire U343;
  wire U344;
  wire U375;
  INV _274_ (
    .A(STATO_REG_0_),
    .Y(_000_)
  );
  INV _275_ (
    .A(STATO_REG_1_),
    .Y(_001_)
  );
  INV _276_ (
    .A(RMAX_REG_6_),
    .Y(_002_)
  );
  INV _277_ (
    .A(RMAX_REG_5_),
    .Y(_003_)
  );
  INV _278_ (
    .A(DATA_IN_3_),
    .Y(_004_)
  );
  INV _279_ (
    .A(RMAX_REG_1_),
    .Y(_005_)
  );
  INV _280_ (
    .A(DATA_IN_1_),
    .Y(_006_)
  );
  INV _281_ (
    .A(DATA_IN_0_),
    .Y(_007_)
  );
  INV _282_ (
    .A(DATA_IN_7_),
    .Y(_008_)
  );
  INV _283_ (
    .A(RMIN_REG_7_),
    .Y(_009_)
  );
  INV _284_ (
    .A(DATA_IN_6_),
    .Y(_010_)
  );
  INV _285_ (
    .A(RMIN_REG_6_),
    .Y(_011_)
  );
  INV _286_ (
    .A(DATA_IN_5_),
    .Y(_012_)
  );
  INV _287_ (
    .A(RMIN_REG_5_),
    .Y(_013_)
  );
  INV _288_ (
    .A(DATA_IN_4_),
    .Y(_014_)
  );
  INV _289_ (
    .A(RMIN_REG_4_),
    .Y(_015_)
  );
  INV _290_ (
    .A(RMIN_REG_3_),
    .Y(_016_)
  );
  INV _291_ (
    .A(DATA_IN_2_),
    .Y(_017_)
  );
  INV _292_ (
    .A(RMIN_REG_2_),
    .Y(_018_)
  );
  INV _293_ (
    .A(RMIN_REG_1_),
    .Y(_019_)
  );
  INV _294_ (
    .A(REG4_REG_0_),
    .Y(_020_)
  );
  INV _295_ (
    .A(REG4_REG_1_),
    .Y(_021_)
  );
  INV _296_ (
    .A(AVERAGE),
    .Y(_022_)
  );
  INV _297_ (
    .A(RESTART),
    .Y(_023_)
  );
  INV _298_ (
    .A(RMIN_REG_0_),
    .Y(_024_)
  );
  INV _299_ (
    .A(RMAX_REG_7_),
    .Y(_025_)
  );
  NAND2 _300_ (
    .A(RMAX_REG_2_),
    .B(RESTART),
    .Y(_026_)
  );
  OAI21 _301_ (
    .A0(_017_),
    .A1(RESTART),
    .B0(_026_),
    .Y(_027_)
  );
  NAND2 _302_ (
    .A(REG4_REG_2_),
    .B(_023_),
    .Y(_028_)
  );
  OAI21 _303_ (
    .A0(_018_),
    .A1(_023_),
    .B0(_028_),
    .Y(_029_)
  );
  NOR2 _304_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  XNOR2 _305_ (
    .A(_027_),
    .B(_029_),
    .Y(_031_)
  );
  NAND2 _306_ (
    .A(RMAX_REG_0_),
    .B(RESTART),
    .Y(_032_)
  );
  NAND2 _307_ (
    .A(DATA_IN_0_),
    .B(_023_),
    .Y(_033_)
  );
  OAI21 _308_ (
    .A0(_007_),
    .A1(RESTART),
    .B0(_032_),
    .Y(_034_)
  );
  NAND2 _309_ (
    .A(RESTART),
    .B(RMIN_REG_0_),
    .Y(_035_)
  );
  NAND2 _310_ (
    .A(REG4_REG_0_),
    .B(_023_),
    .Y(_036_)
  );
  OAI21 _311_ (
    .A0(_020_),
    .A1(RESTART),
    .B0(_035_),
    .Y(_037_)
  );
  AOI22 _312_ (
    .A0(_032_),
    .A1(_033_),
    .B0(_035_),
    .B1(_036_),
    .Y(_038_)
  );
  NAND2 _313_ (
    .A(_034_),
    .B(_037_),
    .Y(_039_)
  );
  NAND2 _314_ (
    .A(RMIN_REG_1_),
    .B(RESTART),
    .Y(_040_)
  );
  OAI21 _315_ (
    .A0(_021_),
    .A1(RESTART),
    .B0(_040_),
    .Y(_041_)
  );
  INV _316_ (
    .A(_041_),
    .Y(_042_)
  );
  NOR2 _317_ (
    .A(_038_),
    .B(_041_),
    .Y(_043_)
  );
  NAND2 _318_ (
    .A(_039_),
    .B(_042_),
    .Y(_044_)
  );
  NAND2 _319_ (
    .A(_005_),
    .B(RESTART),
    .Y(_045_)
  );
  OAI21 _320_ (
    .A0(DATA_IN_1_),
    .A1(RESTART),
    .B0(_045_),
    .Y(_046_)
  );
  OAI21 _321_ (
    .A0(_039_),
    .A1(_042_),
    .B0(_046_),
    .Y(_047_)
  );
  NAND2 _322_ (
    .A(_044_),
    .B(_047_),
    .Y(_048_)
  );
  XNOR2 _323_ (
    .A(_031_),
    .B(_048_),
    .Y(_049_)
  );
  INV _324_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR2 _325_ (
    .A(_034_),
    .B(_037_),
    .Y(_051_)
  );
  NOR2 _326_ (
    .A(_038_),
    .B(_051_),
    .Y(_052_)
  );
  XNOR2 _327_ (
    .A(_038_),
    .B(_042_),
    .Y(_053_)
  );
  OAI22 _328_ (
    .A0(_043_),
    .A1(_047_),
    .B0(_053_),
    .B1(_046_),
    .Y(_054_)
  );
  NAND2 _329_ (
    .A(_052_),
    .B(_054_),
    .Y(_055_)
  );
  NAND2 _330_ (
    .A(_049_),
    .B(_055_),
    .Y(_056_)
  );
  AOI22 _331_ (
    .A0(DATA_IN_0_),
    .A1(REG4_REG_0_),
    .B0(REG4_REG_1_),
    .B1(DATA_IN_1_),
    .Y(_057_)
  );
  OAI22 _332_ (
    .A0(DATA_IN_2_),
    .A1(REG4_REG_2_),
    .B0(REG4_REG_1_),
    .B1(DATA_IN_1_),
    .Y(_058_)
  );
  AOI22 _333_ (
    .A0(DATA_IN_3_),
    .A1(REG4_REG_3_),
    .B0(REG4_REG_2_),
    .B1(DATA_IN_2_),
    .Y(_059_)
  );
  OAI21 _334_ (
    .A0(_057_),
    .A1(_058_),
    .B0(_059_),
    .Y(_060_)
  );
  NOR2 _335_ (
    .A(DATA_IN_4_),
    .B(REG4_REG_4_),
    .Y(_061_)
  );
  OAI21 _336_ (
    .A0(DATA_IN_3_),
    .A1(REG4_REG_3_),
    .B0(_060_),
    .Y(_062_)
  );
  AOI22 _337_ (
    .A0(DATA_IN_4_),
    .A1(REG4_REG_4_),
    .B0(REG4_REG_5_),
    .B1(DATA_IN_5_),
    .Y(_063_)
  );
  OAI21 _338_ (
    .A0(_061_),
    .A1(_062_),
    .B0(_063_),
    .Y(_064_)
  );
  INV _339_ (
    .A(_064_),
    .Y(_065_)
  );
  OAI22 _340_ (
    .A0(DATA_IN_6_),
    .A1(REG4_REG_6_),
    .B0(REG4_REG_5_),
    .B1(DATA_IN_5_),
    .Y(_066_)
  );
  NAND2 _341_ (
    .A(DATA_IN_6_),
    .B(REG4_REG_6_),
    .Y(_067_)
  );
  OAI22 _342_ (
    .A0(DATA_IN_7_),
    .A1(REG4_REG_7_),
    .B0(_065_),
    .B1(_066_),
    .Y(_068_)
  );
  INV _343_ (
    .A(_068_),
    .Y(_069_)
  );
  AOI22 _344_ (
    .A0(DATA_IN_7_),
    .A1(REG4_REG_7_),
    .B0(_067_),
    .B1(_069_),
    .Y(_070_)
  );
  NOR2 _345_ (
    .A(STATO_REG_0_),
    .B(STATO_REG_1_),
    .Y(U375)
  );
  INV _346_ (
    .A(U375),
    .Y(_071_)
  );
  NOR2 _347_ (
    .A(STATO_REG_0_),
    .B(_001_),
    .Y(_072_)
  );
  NAND2 _348_ (
    .A(_023_),
    .B(_072_),
    .Y(_073_)
  );
  AOI21 _349_ (
    .A0(ENABLE),
    .A1(_023_),
    .B0(_072_),
    .Y(_074_)
  );
  NOR2 _350_ (
    .A(AVERAGE),
    .B(_074_),
    .Y(_075_)
  );
  INV _351_ (
    .A(_075_),
    .Y(_076_)
  );
  NAND2 _352_ (
    .A(_070_),
    .B(_075_),
    .Y(_077_)
  );
  AOI22 _353_ (
    .A0(RMAX_REG_1_),
    .A1(RMIN_REG_1_),
    .B0(RMIN_REG_0_),
    .B1(RMAX_REG_0_),
    .Y(_078_)
  );
  OAI22 _354_ (
    .A0(RMAX_REG_2_),
    .A1(RMIN_REG_2_),
    .B0(RMIN_REG_1_),
    .B1(RMAX_REG_1_),
    .Y(_079_)
  );
  AOI22 _355_ (
    .A0(RMAX_REG_3_),
    .A1(RMIN_REG_3_),
    .B0(RMIN_REG_2_),
    .B1(RMAX_REG_2_),
    .Y(_080_)
  );
  OAI21 _356_ (
    .A0(_078_),
    .A1(_079_),
    .B0(_080_),
    .Y(_081_)
  );
  NAND2 _357_ (
    .A(RMAX_REG_4_),
    .B(RMIN_REG_4_),
    .Y(_082_)
  );
  OAI21 _358_ (
    .A0(RMAX_REG_3_),
    .A1(RMIN_REG_3_),
    .B0(_081_),
    .Y(_083_)
  );
  NAND2 _359_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  OAI21 _360_ (
    .A0(RMAX_REG_4_),
    .A1(RMIN_REG_4_),
    .B0(_084_),
    .Y(_085_)
  );
  OAI21 _361_ (
    .A0(_003_),
    .A1(_013_),
    .B0(_085_),
    .Y(_086_)
  );
  NAND2 _362_ (
    .A(_003_),
    .B(_013_),
    .Y(_087_)
  );
  NAND2 _363_ (
    .A(_002_),
    .B(_011_),
    .Y(_088_)
  );
  AOI21 _364_ (
    .A0(_086_),
    .A1(_087_),
    .B0(_088_),
    .Y(_089_)
  );
  AOI22 _365_ (
    .A0(RMAX_REG_6_),
    .A1(RMIN_REG_6_),
    .B0(_025_),
    .B1(_009_),
    .Y(_090_)
  );
  AOI22 _366_ (
    .A0(RMIN_REG_7_),
    .A1(RMAX_REG_7_),
    .B0(_089_),
    .B1(_090_),
    .Y(_091_)
  );
  NAND2 _367_ (
    .A(RESTART),
    .B(_072_),
    .Y(_092_)
  );
  INV _368_ (
    .A(_092_),
    .Y(_093_)
  );
  NAND2 _369_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  AOI22 _370_ (
    .A0(_070_),
    .A1(_075_),
    .B0(_091_),
    .B1(_093_),
    .Y(_095_)
  );
  NAND2 _371_ (
    .A(_077_),
    .B(_094_),
    .Y(_096_)
  );
  OAI22 _372_ (
    .A0(_070_),
    .A1(_076_),
    .B0(_091_),
    .B1(_092_),
    .Y(_097_)
  );
  INV _373_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR2 _374_ (
    .A(_049_),
    .B(_055_),
    .Y(_099_)
  );
  AOI21 _375_ (
    .A0(_050_),
    .A1(_052_),
    .B0(_054_),
    .Y(_100_)
  );
  NOR2 _376_ (
    .A(_022_),
    .B(_074_),
    .Y(_101_)
  );
  XNOR2 _377_ (
    .A(STATO_REG_0_),
    .B(STATO_REG_1_),
    .Y(_102_)
  );
  INV _378_ (
    .A(_102_),
    .Y(U280)
  );
  NAND2 _379_ (
    .A(DATA_OUT_REG_1_),
    .B(_102_),
    .Y(_103_)
  );
  NOR2 _380_ (
    .A(ENABLE),
    .B(_073_),
    .Y(_104_)
  );
  NOR2 _381_ (
    .A(_052_),
    .B(_054_),
    .Y(_105_)
  );
  XOR2 _382_ (
    .A(_052_),
    .B(_054_),
    .Y(_106_)
  );
  NAND2 _383_ (
    .A(_049_),
    .B(_105_),
    .Y(_107_)
  );
  AOI21 _384_ (
    .A0(_056_),
    .A1(_097_),
    .B0(_100_),
    .Y(_108_)
  );
  AOI22 _385_ (
    .A0(REG4_REG_1_),
    .A1(_101_),
    .B0(_104_),
    .B1(RLAST_REG_1_),
    .Y(_109_)
  );
  OAI21 _386_ (
    .A0(_049_),
    .A1(_095_),
    .B0(_109_),
    .Y(_110_)
  );
  INV _387_ (
    .A(_110_),
    .Y(_111_)
  );
  AOI21 _388_ (
    .A0(_103_),
    .A1(_108_),
    .B0(_111_),
    .Y(U282)
  );
  AOI22 _389_ (
    .A0(REG4_REG_2_),
    .A1(_101_),
    .B0(_102_),
    .B1(DATA_OUT_REG_2_),
    .Y(_112_)
  );
  AOI22 _390_ (
    .A0(_027_),
    .A1(_029_),
    .B0(_044_),
    .B1(_047_),
    .Y(_113_)
  );
  NOR2 _391_ (
    .A(_030_),
    .B(_113_),
    .Y(_114_)
  );
  NAND2 _392_ (
    .A(RMAX_REG_3_),
    .B(RESTART),
    .Y(_115_)
  );
  OAI21 _393_ (
    .A0(_004_),
    .A1(RESTART),
    .B0(_115_),
    .Y(_116_)
  );
  NAND2 _394_ (
    .A(REG4_REG_3_),
    .B(_023_),
    .Y(_117_)
  );
  OAI21 _395_ (
    .A0(_016_),
    .A1(_023_),
    .B0(_117_),
    .Y(_118_)
  );
  NAND2 _396_ (
    .A(_116_),
    .B(_118_),
    .Y(_119_)
  );
  XNOR2 _397_ (
    .A(_116_),
    .B(_118_),
    .Y(_120_)
  );
  OAI21 _398_ (
    .A0(_030_),
    .A1(_113_),
    .B0(_119_),
    .Y(_121_)
  );
  OAI21 _399_ (
    .A0(_116_),
    .A1(_118_),
    .B0(_121_),
    .Y(_122_)
  );
  XNOR2 _400_ (
    .A(_114_),
    .B(_120_),
    .Y(_123_)
  );
  NAND2 _401_ (
    .A(_096_),
    .B(_123_),
    .Y(_124_)
  );
  NAND2 _402_ (
    .A(_099_),
    .B(_123_),
    .Y(_125_)
  );
  NOR2 _403_ (
    .A(_107_),
    .B(_123_),
    .Y(_126_)
  );
  XNOR2 _404_ (
    .A(_100_),
    .B(_123_),
    .Y(_127_)
  );
  AOI22 _405_ (
    .A0(RLAST_REG_2_),
    .A1(_104_),
    .B0(_127_),
    .B1(_097_),
    .Y(_128_)
  );
  AOI21 _406_ (
    .A0(_112_),
    .A1(_124_),
    .B0(_128_),
    .Y(U283)
  );
  NAND2 _407_ (
    .A(RLAST_REG_3_),
    .B(_104_),
    .Y(_129_)
  );
  AOI22 _408_ (
    .A0(REG4_REG_3_),
    .A1(_101_),
    .B0(_102_),
    .B1(DATA_OUT_REG_3_),
    .Y(_130_)
  );
  NAND2 _409_ (
    .A(RMAX_REG_4_),
    .B(RESTART),
    .Y(_131_)
  );
  OAI21 _410_ (
    .A0(_014_),
    .A1(RESTART),
    .B0(_131_),
    .Y(_132_)
  );
  NAND2 _411_ (
    .A(REG4_REG_4_),
    .B(_023_),
    .Y(_133_)
  );
  OAI21 _412_ (
    .A0(_015_),
    .A1(_023_),
    .B0(_133_),
    .Y(_134_)
  );
  NAND2 _413_ (
    .A(_132_),
    .B(_134_),
    .Y(_135_)
  );
  NOR2 _414_ (
    .A(_132_),
    .B(_134_),
    .Y(_136_)
  );
  XNOR2 _415_ (
    .A(_132_),
    .B(_134_),
    .Y(_137_)
  );
  OAI21 _416_ (
    .A0(_122_),
    .A1(_136_),
    .B0(_135_),
    .Y(_138_)
  );
  XNOR2 _417_ (
    .A(_122_),
    .B(_137_),
    .Y(_139_)
  );
  NAND2 _418_ (
    .A(_125_),
    .B(_139_),
    .Y(_140_)
  );
  OAI21 _419_ (
    .A0(_125_),
    .A1(_139_),
    .B0(_097_),
    .Y(_141_)
  );
  OAI21 _420_ (
    .A0(_095_),
    .A1(_139_),
    .B0(_141_),
    .Y(_142_)
  );
  NAND2 _421_ (
    .A(_140_),
    .B(_142_),
    .Y(_143_)
  );
  NAND2 _422_ (
    .A(_126_),
    .B(_139_),
    .Y(_144_)
  );
  OAI21 _423_ (
    .A0(_125_),
    .A1(_139_),
    .B0(_144_),
    .Y(_145_)
  );
  AOI21 _424_ (
    .A0(_129_),
    .A1(_130_),
    .B0(_143_),
    .Y(U284)
  );
  NAND2 _425_ (
    .A(_003_),
    .B(RESTART),
    .Y(_146_)
  );
  OAI21 _426_ (
    .A0(DATA_IN_5_),
    .A1(RESTART),
    .B0(_146_),
    .Y(_147_)
  );
  NAND2 _427_ (
    .A(_013_),
    .B(RESTART),
    .Y(_148_)
  );
  OAI21 _428_ (
    .A0(REG4_REG_5_),
    .A1(RESTART),
    .B0(_148_),
    .Y(_149_)
  );
  NOR2 _429_ (
    .A(_147_),
    .B(_149_),
    .Y(_150_)
  );
  NAND2 _430_ (
    .A(_147_),
    .B(_149_),
    .Y(_151_)
  );
  XNOR2 _431_ (
    .A(_147_),
    .B(_149_),
    .Y(_152_)
  );
  OAI21 _432_ (
    .A0(_138_),
    .A1(_150_),
    .B0(_151_),
    .Y(_153_)
  );
  XNOR2 _433_ (
    .A(_138_),
    .B(_152_),
    .Y(_154_)
  );
  NOR2 _434_ (
    .A(_144_),
    .B(_154_),
    .Y(_155_)
  );
  XNOR2 _435_ (
    .A(_144_),
    .B(_154_),
    .Y(_156_)
  );
  NAND2 _436_ (
    .A(_145_),
    .B(_156_),
    .Y(_157_)
  );
  XOR2 _437_ (
    .A(_145_),
    .B(_156_),
    .Y(_158_)
  );
  NAND2 _438_ (
    .A(_097_),
    .B(_158_),
    .Y(_159_)
  );
  NAND2 _439_ (
    .A(_096_),
    .B(_154_),
    .Y(_160_)
  );
  NAND2 _440_ (
    .A(REG4_REG_4_),
    .B(_101_),
    .Y(_161_)
  );
  AOI22 _441_ (
    .A0(DATA_OUT_REG_4_),
    .A1(_102_),
    .B0(_104_),
    .B1(RLAST_REG_4_),
    .Y(_162_)
  );
  NAND2 _442_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  INV _443_ (
    .A(_163_),
    .Y(_164_)
  );
  AOI21 _444_ (
    .A0(_159_),
    .A1(_160_),
    .B0(_164_),
    .Y(U285)
  );
  XNOR2 _445_ (
    .A(RMAX_REG_6_),
    .B(RMIN_REG_6_),
    .Y(_165_)
  );
  NAND2 _446_ (
    .A(RESTART),
    .B(_165_),
    .Y(_166_)
  );
  XNOR2 _447_ (
    .A(_010_),
    .B(REG4_REG_6_),
    .Y(_167_)
  );
  OAI21 _448_ (
    .A0(RESTART),
    .A1(_167_),
    .B0(_166_),
    .Y(_168_)
  );
  XNOR2 _449_ (
    .A(_153_),
    .B(_168_),
    .Y(_169_)
  );
  XOR2 _450_ (
    .A(_155_),
    .B(_169_),
    .Y(_170_)
  );
  XNOR2 _451_ (
    .A(_157_),
    .B(_170_),
    .Y(_171_)
  );
  NOR2 _452_ (
    .A(_095_),
    .B(_169_),
    .Y(_172_)
  );
  NAND2 _453_ (
    .A(REG4_REG_5_),
    .B(_101_),
    .Y(_173_)
  );
  AOI22 _454_ (
    .A0(DATA_OUT_REG_5_),
    .A1(_102_),
    .B0(_104_),
    .B1(RLAST_REG_5_),
    .Y(_174_)
  );
  NAND2 _455_ (
    .A(_173_),
    .B(_174_),
    .Y(_175_)
  );
  NOR2 _456_ (
    .A(_172_),
    .B(_175_),
    .Y(_176_)
  );
  OAI21 _457_ (
    .A0(_098_),
    .A1(_171_),
    .B0(_176_),
    .Y(U286)
  );
  NAND2 _458_ (
    .A(DATA_OUT_REG_6_),
    .B(_102_),
    .Y(_177_)
  );
  AOI22 _459_ (
    .A0(REG4_REG_6_),
    .A1(_101_),
    .B0(_104_),
    .B1(RLAST_REG_6_),
    .Y(_178_)
  );
  NOR3 _460_ (
    .A(_098_),
    .B(_155_),
    .C(_169_),
    .Y(_179_)
  );
  AOI21 _461_ (
    .A0(_145_),
    .A1(_156_),
    .B0(_179_),
    .Y(_180_)
  );
  AOI21 _462_ (
    .A0(_177_),
    .A1(_178_),
    .B0(_180_),
    .Y(U287)
  );
  NAND2 _463_ (
    .A(REG4_REG_7_),
    .B(_101_),
    .Y(_181_)
  );
  AOI22 _464_ (
    .A0(DATA_OUT_REG_7_),
    .A1(_102_),
    .B0(_104_),
    .B1(RLAST_REG_7_),
    .Y(_182_)
  );
  NAND2 _465_ (
    .A(_181_),
    .B(_182_),
    .Y(U288)
  );
  AOI22 _466_ (
    .A0(REG3_REG_0_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_0_),
    .Y(_183_)
  );
  INV _467_ (
    .A(_183_),
    .Y(U289)
  );
  AOI22 _468_ (
    .A0(REG3_REG_1_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_1_),
    .Y(_184_)
  );
  INV _469_ (
    .A(_184_),
    .Y(U290)
  );
  AOI22 _470_ (
    .A0(REG3_REG_2_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_2_),
    .Y(_185_)
  );
  INV _471_ (
    .A(_185_),
    .Y(U291)
  );
  AOI22 _472_ (
    .A0(REG3_REG_3_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_3_),
    .Y(_186_)
  );
  INV _473_ (
    .A(_186_),
    .Y(U292)
  );
  AOI22 _474_ (
    .A0(REG3_REG_4_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_4_),
    .Y(_187_)
  );
  INV _475_ (
    .A(_187_),
    .Y(U293)
  );
  AOI22 _476_ (
    .A0(REG3_REG_5_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_5_),
    .Y(_188_)
  );
  INV _477_ (
    .A(_188_),
    .Y(U294)
  );
  AOI22 _478_ (
    .A0(REG3_REG_6_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_6_),
    .Y(_189_)
  );
  INV _479_ (
    .A(_189_),
    .Y(U295)
  );
  AOI22 _480_ (
    .A0(REG3_REG_7_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG4_REG_7_),
    .Y(_190_)
  );
  INV _481_ (
    .A(_190_),
    .Y(U296)
  );
  AOI22 _482_ (
    .A0(REG2_REG_0_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_0_),
    .Y(_191_)
  );
  INV _483_ (
    .A(_191_),
    .Y(U297)
  );
  AOI22 _484_ (
    .A0(REG2_REG_1_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_1_),
    .Y(_192_)
  );
  INV _485_ (
    .A(_192_),
    .Y(U298)
  );
  AOI22 _486_ (
    .A0(REG2_REG_2_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_2_),
    .Y(_193_)
  );
  INV _487_ (
    .A(_193_),
    .Y(U299)
  );
  AOI22 _488_ (
    .A0(REG2_REG_3_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_3_),
    .Y(_194_)
  );
  INV _489_ (
    .A(_194_),
    .Y(U300)
  );
  AOI22 _490_ (
    .A0(REG2_REG_4_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_4_),
    .Y(_195_)
  );
  INV _491_ (
    .A(_195_),
    .Y(U301)
  );
  AOI22 _492_ (
    .A0(REG2_REG_5_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_5_),
    .Y(_196_)
  );
  INV _493_ (
    .A(_196_),
    .Y(U302)
  );
  AOI22 _494_ (
    .A0(REG2_REG_6_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_6_),
    .Y(_197_)
  );
  INV _495_ (
    .A(_197_),
    .Y(U303)
  );
  AOI22 _496_ (
    .A0(REG2_REG_7_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG3_REG_7_),
    .Y(_198_)
  );
  INV _497_ (
    .A(_198_),
    .Y(U304)
  );
  AOI22 _498_ (
    .A0(REG1_REG_0_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_0_),
    .Y(_199_)
  );
  INV _499_ (
    .A(_199_),
    .Y(U305)
  );
  AOI22 _500_ (
    .A0(REG1_REG_1_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_1_),
    .Y(_200_)
  );
  INV _501_ (
    .A(_200_),
    .Y(U306)
  );
  AOI22 _502_ (
    .A0(REG1_REG_2_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_2_),
    .Y(_201_)
  );
  INV _503_ (
    .A(_201_),
    .Y(U307)
  );
  AOI22 _504_ (
    .A0(REG1_REG_3_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_3_),
    .Y(_202_)
  );
  INV _505_ (
    .A(_202_),
    .Y(U308)
  );
  AOI22 _506_ (
    .A0(REG1_REG_4_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_4_),
    .Y(_203_)
  );
  INV _507_ (
    .A(_203_),
    .Y(U309)
  );
  AOI22 _508_ (
    .A0(REG1_REG_5_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_5_),
    .Y(_204_)
  );
  INV _509_ (
    .A(_204_),
    .Y(U310)
  );
  AOI22 _510_ (
    .A0(REG1_REG_6_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_6_),
    .Y(_205_)
  );
  INV _511_ (
    .A(_205_),
    .Y(U311)
  );
  AOI22 _512_ (
    .A0(REG1_REG_7_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG2_REG_7_),
    .Y(_206_)
  );
  INV _513_ (
    .A(_206_),
    .Y(U312)
  );
  AOI22 _514_ (
    .A0(DATA_IN_0_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_0_),
    .Y(_207_)
  );
  INV _515_ (
    .A(_207_),
    .Y(U313)
  );
  AOI22 _516_ (
    .A0(DATA_IN_1_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_1_),
    .Y(_208_)
  );
  INV _517_ (
    .A(_208_),
    .Y(U314)
  );
  AOI22 _518_ (
    .A0(DATA_IN_2_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_2_),
    .Y(_209_)
  );
  INV _519_ (
    .A(_209_),
    .Y(U315)
  );
  AOI22 _520_ (
    .A0(DATA_IN_3_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_3_),
    .Y(_210_)
  );
  INV _521_ (
    .A(_210_),
    .Y(U316)
  );
  AOI22 _522_ (
    .A0(DATA_IN_4_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_4_),
    .Y(_211_)
  );
  INV _523_ (
    .A(_211_),
    .Y(U317)
  );
  AOI22 _524_ (
    .A0(DATA_IN_5_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_5_),
    .Y(_212_)
  );
  INV _525_ (
    .A(_212_),
    .Y(U318)
  );
  AOI22 _526_ (
    .A0(DATA_IN_6_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_6_),
    .Y(_213_)
  );
  INV _527_ (
    .A(_213_),
    .Y(U319)
  );
  AOI22 _528_ (
    .A0(DATA_IN_7_),
    .A1(_072_),
    .B0(_102_),
    .B1(REG1_REG_7_),
    .Y(_214_)
  );
  INV _529_ (
    .A(_214_),
    .Y(U320)
  );
  NOR2 _530_ (
    .A(STATO_REG_0_),
    .B(ENABLE),
    .Y(_215_)
  );
  NOR2 _531_ (
    .A(_001_),
    .B(_215_),
    .Y(_216_)
  );
  OAI21 _532_ (
    .A0(STATO_REG_0_),
    .A1(ENABLE),
    .B0(_071_),
    .Y(_217_)
  );
  AOI22 _533_ (
    .A0(DATA_IN_0_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_0_),
    .Y(_218_)
  );
  INV _534_ (
    .A(_218_),
    .Y(U321)
  );
  AOI22 _535_ (
    .A0(DATA_IN_1_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_1_),
    .Y(_219_)
  );
  INV _536_ (
    .A(_219_),
    .Y(U322)
  );
  AOI22 _537_ (
    .A0(DATA_IN_2_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_2_),
    .Y(_220_)
  );
  INV _538_ (
    .A(_220_),
    .Y(U323)
  );
  AOI22 _539_ (
    .A0(DATA_IN_3_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_3_),
    .Y(_221_)
  );
  INV _540_ (
    .A(_221_),
    .Y(U324)
  );
  AOI22 _541_ (
    .A0(DATA_IN_4_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_4_),
    .Y(_222_)
  );
  INV _542_ (
    .A(_222_),
    .Y(U325)
  );
  AOI22 _543_ (
    .A0(DATA_IN_5_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_5_),
    .Y(_223_)
  );
  INV _544_ (
    .A(_223_),
    .Y(U326)
  );
  AOI22 _545_ (
    .A0(DATA_IN_6_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_6_),
    .Y(_224_)
  );
  INV _546_ (
    .A(_224_),
    .Y(U327)
  );
  AOI22 _547_ (
    .A0(DATA_IN_7_),
    .A1(_216_),
    .B0(_217_),
    .B1(RLAST_REG_7_),
    .Y(_225_)
  );
  INV _548_ (
    .A(_225_),
    .Y(U328)
  );
  NOR2 _549_ (
    .A(_005_),
    .B(DATA_IN_1_),
    .Y(_226_)
  );
  NOR3 _550_ (
    .A(RMAX_REG_0_),
    .B(_007_),
    .C(_226_),
    .Y(_227_)
  );
  OAI22 _551_ (
    .A0(RMAX_REG_1_),
    .A1(_006_),
    .B0(_017_),
    .B1(RMAX_REG_2_),
    .Y(_228_)
  );
  AOI22 _552_ (
    .A0(RMAX_REG_3_),
    .A1(_004_),
    .B0(RMAX_REG_2_),
    .B1(_017_),
    .Y(_229_)
  );
  OAI21 _553_ (
    .A0(_227_),
    .A1(_228_),
    .B0(_229_),
    .Y(_230_)
  );
  NOR2 _554_ (
    .A(RMAX_REG_4_),
    .B(_014_),
    .Y(_231_)
  );
  OAI21 _555_ (
    .A0(RMAX_REG_3_),
    .A1(_004_),
    .B0(_230_),
    .Y(_232_)
  );
  AOI22 _556_ (
    .A0(RMAX_REG_5_),
    .A1(_012_),
    .B0(_014_),
    .B1(RMAX_REG_4_),
    .Y(_233_)
  );
  OAI21 _557_ (
    .A0(_231_),
    .A1(_232_),
    .B0(_233_),
    .Y(_234_)
  );
  AOI22 _558_ (
    .A0(_002_),
    .A1(DATA_IN_6_),
    .B0(DATA_IN_5_),
    .B1(_003_),
    .Y(_235_)
  );
  NAND2 _559_ (
    .A(_234_),
    .B(_235_),
    .Y(_236_)
  );
  AOI22 _560_ (
    .A0(RMAX_REG_6_),
    .A1(_010_),
    .B0(_025_),
    .B1(DATA_IN_7_),
    .Y(_237_)
  );
  AOI22 _561_ (
    .A0(_008_),
    .A1(RMAX_REG_7_),
    .B0(_236_),
    .B1(_237_),
    .Y(_238_)
  );
  NOR2 _562_ (
    .A(_006_),
    .B(RMIN_REG_1_),
    .Y(_239_)
  );
  NOR3 _563_ (
    .A(DATA_IN_0_),
    .B(_024_),
    .C(_239_),
    .Y(_240_)
  );
  OAI22 _564_ (
    .A0(DATA_IN_2_),
    .A1(_018_),
    .B0(_019_),
    .B1(DATA_IN_1_),
    .Y(_241_)
  );
  AOI22 _565_ (
    .A0(DATA_IN_3_),
    .A1(_016_),
    .B0(DATA_IN_2_),
    .B1(_018_),
    .Y(_242_)
  );
  OAI21 _566_ (
    .A0(_240_),
    .A1(_241_),
    .B0(_242_),
    .Y(_243_)
  );
  AOI22 _567_ (
    .A0(_014_),
    .A1(RMIN_REG_4_),
    .B0(RMIN_REG_3_),
    .B1(_004_),
    .Y(_244_)
  );
  AOI22 _568_ (
    .A0(DATA_IN_4_),
    .A1(_015_),
    .B0(_243_),
    .B1(_244_),
    .Y(_245_)
  );
  OAI21 _569_ (
    .A0(_012_),
    .A1(RMIN_REG_5_),
    .B0(_245_),
    .Y(_246_)
  );
  AOI22 _570_ (
    .A0(_010_),
    .A1(RMIN_REG_6_),
    .B0(_012_),
    .B1(RMIN_REG_5_),
    .Y(_247_)
  );
  NAND2 _571_ (
    .A(DATA_IN_6_),
    .B(_011_),
    .Y(_248_)
  );
  AOI22 _572_ (
    .A0(_008_),
    .A1(RMIN_REG_7_),
    .B0(_246_),
    .B1(_247_),
    .Y(_249_)
  );
  AOI22 _573_ (
    .A0(DATA_IN_7_),
    .A1(_009_),
    .B0(_248_),
    .B1(_249_),
    .Y(_250_)
  );
  NAND2 _574_ (
    .A(STATO_REG_1_),
    .B(_238_),
    .Y(_251_)
  );
  OAI21 _575_ (
    .A0(_250_),
    .A1(_251_),
    .B0(_000_),
    .Y(_252_)
  );
  NAND2 _576_ (
    .A(DATA_IN_0_),
    .B(_252_),
    .Y(_253_)
  );
  OAI21 _577_ (
    .A0(_024_),
    .A1(_252_),
    .B0(_253_),
    .Y(U329)
  );
  NAND2 _578_ (
    .A(DATA_IN_1_),
    .B(_252_),
    .Y(_254_)
  );
  OAI21 _579_ (
    .A0(_019_),
    .A1(_252_),
    .B0(_254_),
    .Y(U330)
  );
  NAND2 _580_ (
    .A(DATA_IN_2_),
    .B(_252_),
    .Y(_255_)
  );
  OAI21 _581_ (
    .A0(_018_),
    .A1(_252_),
    .B0(_255_),
    .Y(U331)
  );
  NAND2 _582_ (
    .A(DATA_IN_3_),
    .B(_252_),
    .Y(_256_)
  );
  OAI21 _583_ (
    .A0(_016_),
    .A1(_252_),
    .B0(_256_),
    .Y(U332)
  );
  NAND2 _584_ (
    .A(DATA_IN_4_),
    .B(_252_),
    .Y(_257_)
  );
  OAI21 _585_ (
    .A0(_015_),
    .A1(_252_),
    .B0(_257_),
    .Y(U333)
  );
  NAND2 _586_ (
    .A(DATA_IN_5_),
    .B(_252_),
    .Y(_258_)
  );
  OAI21 _587_ (
    .A0(_013_),
    .A1(_252_),
    .B0(_258_),
    .Y(U334)
  );
  NAND2 _588_ (
    .A(DATA_IN_6_),
    .B(_252_),
    .Y(_259_)
  );
  OAI21 _589_ (
    .A0(_011_),
    .A1(_252_),
    .B0(_259_),
    .Y(U335)
  );
  NAND2 _590_ (
    .A(DATA_IN_7_),
    .B(_252_),
    .Y(_260_)
  );
  OAI21 _591_ (
    .A0(_009_),
    .A1(_252_),
    .B0(_260_),
    .Y(U336)
  );
  NOR2 _592_ (
    .A(_001_),
    .B(_238_),
    .Y(_261_)
  );
  NOR2 _593_ (
    .A(STATO_REG_0_),
    .B(_261_),
    .Y(_262_)
  );
  NAND2 _594_ (
    .A(RMAX_REG_0_),
    .B(_262_),
    .Y(_263_)
  );
  OAI21 _595_ (
    .A0(_007_),
    .A1(_262_),
    .B0(_263_),
    .Y(U337)
  );
  NAND2 _596_ (
    .A(RMAX_REG_1_),
    .B(_262_),
    .Y(_264_)
  );
  OAI21 _597_ (
    .A0(_006_),
    .A1(_262_),
    .B0(_264_),
    .Y(U338)
  );
  NAND2 _598_ (
    .A(RMAX_REG_2_),
    .B(_262_),
    .Y(_265_)
  );
  OAI21 _599_ (
    .A0(_017_),
    .A1(_262_),
    .B0(_265_),
    .Y(U339)
  );
  NAND2 _600_ (
    .A(RMAX_REG_3_),
    .B(_262_),
    .Y(_266_)
  );
  OAI21 _601_ (
    .A0(_004_),
    .A1(_262_),
    .B0(_266_),
    .Y(U340)
  );
  NAND2 _602_ (
    .A(RMAX_REG_4_),
    .B(_262_),
    .Y(_267_)
  );
  OAI21 _603_ (
    .A0(_014_),
    .A1(_262_),
    .B0(_267_),
    .Y(U341)
  );
  NAND2 _604_ (
    .A(RMAX_REG_5_),
    .B(_262_),
    .Y(_268_)
  );
  OAI21 _605_ (
    .A0(_012_),
    .A1(_262_),
    .B0(_268_),
    .Y(U342)
  );
  NAND2 _606_ (
    .A(RMAX_REG_6_),
    .B(_262_),
    .Y(_269_)
  );
  OAI21 _607_ (
    .A0(_010_),
    .A1(_262_),
    .B0(_269_),
    .Y(U343)
  );
  NAND2 _608_ (
    .A(RMAX_REG_7_),
    .B(_262_),
    .Y(_270_)
  );
  OAI21 _609_ (
    .A0(_008_),
    .A1(_262_),
    .B0(_270_),
    .Y(U344)
  );
  NAND2 _610_ (
    .A(_097_),
    .B(_106_),
    .Y(_271_)
  );
  AOI22 _611_ (
    .A0(_054_),
    .A1(_096_),
    .B0(_102_),
    .B1(DATA_OUT_REG_0_),
    .Y(_272_)
  );
  AOI22 _612_ (
    .A0(REG4_REG_0_),
    .A1(_101_),
    .B0(_104_),
    .B1(RLAST_REG_0_),
    .Y(_273_)
  );
  AOI21 _613_ (
    .A0(_271_),
    .A1(_272_),
    .B0(_273_),
    .Y(U281)
  );
  \$_FF_  _614_ (
    .D(U344),
    .Q(RMAX_REG_7_)
  );
  \$_FF_  _615_ (
    .D(U343),
    .Q(RMAX_REG_6_)
  );
  \$_FF_  _616_ (
    .D(U342),
    .Q(RMAX_REG_5_)
  );
  \$_FF_  _617_ (
    .D(U341),
    .Q(RMAX_REG_4_)
  );
  \$_FF_  _618_ (
    .D(U340),
    .Q(RMAX_REG_3_)
  );
  \$_FF_  _619_ (
    .D(U339),
    .Q(RMAX_REG_2_)
  );
  \$_FF_  _620_ (
    .D(U338),
    .Q(RMAX_REG_1_)
  );
  \$_FF_  _621_ (
    .D(U337),
    .Q(RMAX_REG_0_)
  );
  \$_FF_  _622_ (
    .D(U336),
    .Q(RMIN_REG_7_)
  );
  \$_FF_  _623_ (
    .D(U335),
    .Q(RMIN_REG_6_)
  );
  \$_FF_  _624_ (
    .D(U334),
    .Q(RMIN_REG_5_)
  );
  \$_FF_  _625_ (
    .D(U333),
    .Q(RMIN_REG_4_)
  );
  \$_FF_  _626_ (
    .D(U332),
    .Q(RMIN_REG_3_)
  );
  \$_FF_  _627_ (
    .D(U331),
    .Q(RMIN_REG_2_)
  );
  \$_FF_  _628_ (
    .D(U330),
    .Q(RMIN_REG_1_)
  );
  \$_FF_  _629_ (
    .D(U329),
    .Q(RMIN_REG_0_)
  );
  \$_FF_  _630_ (
    .D(U328),
    .Q(RLAST_REG_7_)
  );
  \$_FF_  _631_ (
    .D(U327),
    .Q(RLAST_REG_6_)
  );
  \$_FF_  _632_ (
    .D(U326),
    .Q(RLAST_REG_5_)
  );
  \$_FF_  _633_ (
    .D(U325),
    .Q(RLAST_REG_4_)
  );
  \$_FF_  _634_ (
    .D(U324),
    .Q(RLAST_REG_3_)
  );
  \$_FF_  _635_ (
    .D(U323),
    .Q(RLAST_REG_2_)
  );
  \$_FF_  _636_ (
    .D(U322),
    .Q(RLAST_REG_1_)
  );
  \$_FF_  _637_ (
    .D(U321),
    .Q(RLAST_REG_0_)
  );
  \$_FF_  _638_ (
    .D(U320),
    .Q(REG1_REG_7_)
  );
  \$_FF_  _639_ (
    .D(U319),
    .Q(REG1_REG_6_)
  );
  \$_FF_  _640_ (
    .D(U318),
    .Q(REG1_REG_5_)
  );
  \$_FF_  _641_ (
    .D(U317),
    .Q(REG1_REG_4_)
  );
  \$_FF_  _642_ (
    .D(U316),
    .Q(REG1_REG_3_)
  );
  \$_FF_  _643_ (
    .D(U315),
    .Q(REG1_REG_2_)
  );
  \$_FF_  _644_ (
    .D(U314),
    .Q(REG1_REG_1_)
  );
  \$_FF_  _645_ (
    .D(U313),
    .Q(REG1_REG_0_)
  );
  \$_FF_  _646_ (
    .D(U312),
    .Q(REG2_REG_7_)
  );
  \$_FF_  _647_ (
    .D(U311),
    .Q(REG2_REG_6_)
  );
  \$_FF_  _648_ (
    .D(U310),
    .Q(REG2_REG_5_)
  );
  \$_FF_  _649_ (
    .D(U309),
    .Q(REG2_REG_4_)
  );
  \$_FF_  _650_ (
    .D(U308),
    .Q(REG2_REG_3_)
  );
  \$_FF_  _651_ (
    .D(U307),
    .Q(REG2_REG_2_)
  );
  \$_FF_  _652_ (
    .D(U306),
    .Q(REG2_REG_1_)
  );
  \$_FF_  _653_ (
    .D(U305),
    .Q(REG2_REG_0_)
  );
  \$_FF_  _654_ (
    .D(U304),
    .Q(REG3_REG_7_)
  );
  \$_FF_  _655_ (
    .D(U303),
    .Q(REG3_REG_6_)
  );
  \$_FF_  _656_ (
    .D(U302),
    .Q(REG3_REG_5_)
  );
  \$_FF_  _657_ (
    .D(U301),
    .Q(REG3_REG_4_)
  );
  \$_FF_  _658_ (
    .D(U300),
    .Q(REG3_REG_3_)
  );
  \$_FF_  _659_ (
    .D(U299),
    .Q(REG3_REG_2_)
  );
  \$_FF_  _660_ (
    .D(U298),
    .Q(REG3_REG_1_)
  );
  \$_FF_  _661_ (
    .D(U297),
    .Q(REG3_REG_0_)
  );
  \$_FF_  _662_ (
    .D(U296),
    .Q(REG4_REG_7_)
  );
  \$_FF_  _663_ (
    .D(U295),
    .Q(REG4_REG_6_)
  );
  \$_FF_  _664_ (
    .D(U294),
    .Q(REG4_REG_5_)
  );
  \$_FF_  _665_ (
    .D(U293),
    .Q(REG4_REG_4_)
  );
  \$_FF_  _666_ (
    .D(U292),
    .Q(REG4_REG_3_)
  );
  \$_FF_  _667_ (
    .D(U291),
    .Q(REG4_REG_2_)
  );
  \$_FF_  _668_ (
    .D(U290),
    .Q(REG4_REG_1_)
  );
  \$_FF_  _669_ (
    .D(U289),
    .Q(REG4_REG_0_)
  );
  \$_FF_  _670_ (
    .D(U288),
    .Q(DATA_OUT_REG_7_)
  );
  \$_FF_  _671_ (
    .D(U287),
    .Q(DATA_OUT_REG_6_)
  );
  \$_FF_  _672_ (
    .D(U286),
    .Q(DATA_OUT_REG_5_)
  );
  \$_FF_  _673_ (
    .D(U285),
    .Q(DATA_OUT_REG_4_)
  );
  \$_FF_  _674_ (
    .D(U284),
    .Q(DATA_OUT_REG_3_)
  );
  \$_FF_  _675_ (
    .D(U283),
    .Q(DATA_OUT_REG_2_)
  );
  \$_FF_  _676_ (
    .D(U282),
    .Q(DATA_OUT_REG_1_)
  );
  \$_FF_  _677_ (
    .D(U281),
    .Q(DATA_OUT_REG_0_)
  );
  \$_FF_  _678_ (
    .D(U280),
    .Q(STATO_REG_1_)
  );
  \$_FF_  _679_ (
    .D(U375),
    .Q(STATO_REG_0_)
  );
  assign DATA_OUT_5_ = DATA_OUT_REG_5_;
  assign DATA_OUT_6_ = DATA_OUT_REG_6_;
  assign DATA_OUT_7_ = DATA_OUT_REG_7_;
  assign DATA_OUT_0_ = DATA_OUT_REG_0_;
  assign DATA_OUT_1_ = DATA_OUT_REG_1_;
  assign DATA_OUT_2_ = DATA_OUT_REG_2_;
  assign DATA_OUT_3_ = DATA_OUT_REG_3_;
  assign DATA_OUT_4_ = DATA_OUT_REG_4_;
endmodule
