/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b05.blif (START, SIGN, DISPMAX1_6_, DISPMAX1_5_, DISPMAX1_4_, DISPMAX1_3_, DISPMAX1_2_, DISPMAX1_1_, DISPMAX1_0_, DISPMAX2_6_, DISPMAX2_5_, DISPMAX2_4_, DISPMAX2_3_, DISPMAX2_2_, DISPMAX2_1_, DISPMAX2_0_, DISPMAX3_6_, DISPMAX3_5_, DISPMAX3_4_, DISPMAX3_3_, DISPMAX3_2_
, DISPMAX3_1_, DISPMAX3_0_, DISPNUM1_6_, DISPNUM1_5_, DISPNUM1_4_, DISPNUM1_3_, DISPNUM1_2_, DISPNUM1_1_, DISPNUM1_0_, DISPNUM2_6_, DISPNUM2_5_, DISPNUM2_4_, DISPNUM2_3_, DISPNUM2_2_, DISPNUM2_1_, DISPNUM2_0_);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  output DISPMAX1_0_;
  wire DISPMAX1_0_;
  output DISPMAX1_1_;
  wire DISPMAX1_1_;
  output DISPMAX1_2_;
  wire DISPMAX1_2_;
  output DISPMAX1_3_;
  wire DISPMAX1_3_;
  output DISPMAX1_4_;
  wire DISPMAX1_4_;
  output DISPMAX1_5_;
  wire DISPMAX1_5_;
  output DISPMAX1_6_;
  wire DISPMAX1_6_;
  output DISPMAX2_0_;
  wire DISPMAX2_0_;
  output DISPMAX2_1_;
  wire DISPMAX2_1_;
  output DISPMAX2_2_;
  wire DISPMAX2_2_;
  output DISPMAX2_3_;
  wire DISPMAX2_3_;
  output DISPMAX2_4_;
  wire DISPMAX2_4_;
  output DISPMAX2_5_;
  wire DISPMAX2_5_;
  output DISPMAX2_6_;
  wire DISPMAX2_6_;
  output DISPMAX3_0_;
  wire DISPMAX3_0_;
  output DISPMAX3_1_;
  wire DISPMAX3_1_;
  output DISPMAX3_2_;
  wire DISPMAX3_2_;
  output DISPMAX3_3_;
  wire DISPMAX3_3_;
  output DISPMAX3_4_;
  wire DISPMAX3_4_;
  output DISPMAX3_5_;
  wire DISPMAX3_5_;
  output DISPMAX3_6_;
  wire DISPMAX3_6_;
  output DISPNUM1_0_;
  wire DISPNUM1_0_;
  output DISPNUM1_1_;
  wire DISPNUM1_1_;
  output DISPNUM1_2_;
  wire DISPNUM1_2_;
  output DISPNUM1_3_;
  wire DISPNUM1_3_;
  output DISPNUM1_4_;
  wire DISPNUM1_4_;
  output DISPNUM1_5_;
  wire DISPNUM1_5_;
  output DISPNUM1_6_;
  wire DISPNUM1_6_;
  output DISPNUM2_0_;
  wire DISPNUM2_0_;
  output DISPNUM2_1_;
  wire DISPNUM2_1_;
  output DISPNUM2_2_;
  wire DISPNUM2_2_;
  output DISPNUM2_3_;
  wire DISPNUM2_3_;
  output DISPNUM2_4_;
  wire DISPNUM2_4_;
  output DISPNUM2_5_;
  wire DISPNUM2_5_;
  output DISPNUM2_6_;
  wire DISPNUM2_6_;
  (* init = 1'h0 *)
  wire EN_DISP_REG;
  (* init = 1'h0 *)
  wire FLAG_REG;
  (* init = 1'h0 *)
  wire MAR_REG_0_;
  (* init = 1'h0 *)
  wire MAR_REG_1_;
  (* init = 1'h0 *)
  wire MAR_REG_2_;
  (* init = 1'h0 *)
  wire MAR_REG_3_;
  (* init = 1'h0 *)
  wire MAR_REG_4_;
  (* init = 1'h0 *)
  wire MAX_REG_0_;
  (* init = 1'h0 *)
  wire MAX_REG_1_;
  (* init = 1'h0 *)
  wire MAX_REG_2_;
  (* init = 1'h0 *)
  wire MAX_REG_3_;
  (* init = 1'h0 *)
  wire MAX_REG_4_;
  (* init = 1'h0 *)
  wire MAX_REG_5_;
  (* init = 1'h0 *)
  wire MAX_REG_6_;
  (* init = 1'h0 *)
  wire MAX_REG_7_;
  (* init = 1'h0 *)
  wire MAX_REG_8_;
  (* init = 1'h0 *)
  wire NUM_REG_0_;
  (* init = 1'h0 *)
  wire NUM_REG_1_;
  (* init = 1'h0 *)
  wire NUM_REG_2_;
  (* init = 1'h0 *)
  wire NUM_REG_3_;
  (* init = 1'h0 *)
  wire NUM_REG_4_;
  (* init = 1'h0 *)
  wire RES_DISP_REG;
  output SIGN;
  wire SIGN;
  input START;
  wire START;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  (* init = 1'h0 *)
  wire STATO_REG_2_;
  (* init = 1'h0 *)
  wire TEMP_REG_0_;
  (* init = 1'h0 *)
  wire TEMP_REG_1_;
  (* init = 1'h0 *)
  wire TEMP_REG_2_;
  (* init = 1'h0 *)
  wire TEMP_REG_3_;
  (* init = 1'h0 *)
  wire TEMP_REG_4_;
  (* init = 1'h0 *)
  wire TEMP_REG_5_;
  (* init = 1'h0 *)
  wire TEMP_REG_6_;
  (* init = 1'h0 *)
  wire TEMP_REG_7_;
  (* init = 1'h0 *)
  wire TEMP_REG_8_;
  wire U589;
  wire U590;
  wire U591;
  wire U643;
  wire U644;
  wire U645;
  wire U646;
  wire U647;
  wire U648;
  wire U649;
  wire U650;
  wire U651;
  wire U652;
  wire U653;
  wire U654;
  wire U655;
  wire U656;
  wire U657;
  wire U658;
  wire U659;
  wire U660;
  wire U661;
  wire U662;
  wire U663;
  wire U664;
  wire U665;
  wire U666;
  wire U667;
  wire U668;
  wire U669;
  wire U670;
  wire U671;
  wire U672;
  wire U673;
  wire U674;
  wire U675;
  wire U676;
  wire U677;
  wire U678;
  wire U679;
  wire U680;
  wire U727;
  wire U728;
  wire U729;
  wire U730;
  wire U731;
  wire U732;
  wire U733;
  wire U734;
  wire U735;
  wire U736;
  wire U737;
  wire U738;
  wire U739;
  wire U740;
  wire U741;
  wire U742;
  wire U743;
  wire U744;
  wire U792;
  INV _356_ (
    .A(MAX_REG_8_),
    .Y(_352_)
  );
  INV _357_ (
    .A(RES_DISP_REG),
    .Y(_353_)
  );
  INV _358_ (
    .A(EN_DISP_REG),
    .Y(_354_)
  );
  INV _359_ (
    .A(STATO_REG_0_),
    .Y(_355_)
  );
  INV _360_ (
    .A(STATO_REG_1_),
    .Y(_000_)
  );
  INV _361_ (
    .A(FLAG_REG),
    .Y(_001_)
  );
  INV _362_ (
    .A(MAR_REG_1_),
    .Y(_002_)
  );
  INV _363_ (
    .A(MAR_REG_4_),
    .Y(_003_)
  );
  INV _364_ (
    .A(MAR_REG_0_),
    .Y(_004_)
  );
  INV _365_ (
    .A(MAR_REG_3_),
    .Y(_005_)
  );
  INV _366_ (
    .A(MAR_REG_2_),
    .Y(_006_)
  );
  INV _367_ (
    .A(STATO_REG_2_),
    .Y(_007_)
  );
  INV _368_ (
    .A(START),
    .Y(_008_)
  );
  INV _369_ (
    .A(NUM_REG_3_),
    .Y(_009_)
  );
  INV _370_ (
    .A(TEMP_REG_7_),
    .Y(_010_)
  );
  INV _371_ (
    .A(TEMP_REG_3_),
    .Y(_011_)
  );
  INV _372_ (
    .A(TEMP_REG_2_),
    .Y(_012_)
  );
  INV _373_ (
    .A(MAX_REG_4_),
    .Y(_013_)
  );
  INV _374_ (
    .A(NUM_REG_2_),
    .Y(_014_)
  );
  INV _375_ (
    .A(NUM_REG_4_),
    .Y(_015_)
  );
  INV _376_ (
    .A(MAX_REG_0_),
    .Y(_016_)
  );
  INV _377_ (
    .A(MAX_REG_2_),
    .Y(_017_)
  );
  NAND2 _378_ (
    .A(RES_DISP_REG),
    .B(_354_),
    .Y(_018_)
  );
  INV _379_ (
    .A(_018_),
    .Y(DISPMAX1_3_)
  );
  NOR2 _380_ (
    .A(NUM_REG_1_),
    .B(NUM_REG_2_),
    .Y(_019_)
  );
  NOR2 _381_ (
    .A(_009_),
    .B(_019_),
    .Y(_020_)
  );
  OAI21 _382_ (
    .A0(NUM_REG_1_),
    .A1(NUM_REG_2_),
    .B0(NUM_REG_3_),
    .Y(_021_)
  );
  NOR2 _383_ (
    .A(NUM_REG_4_),
    .B(_020_),
    .Y(_022_)
  );
  NOR3 _384_ (
    .A(NUM_REG_4_),
    .B(_018_),
    .C(_020_),
    .Y(DISPNUM1_0_)
  );
  NOR2 _385_ (
    .A(MAR_REG_1_),
    .B(_005_),
    .Y(_023_)
  );
  NAND2 _386_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_3_),
    .Y(_024_)
  );
  INV _387_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR2 _388_ (
    .A(_004_),
    .B(_006_),
    .Y(_026_)
  );
  NAND2 _389_ (
    .A(MAR_REG_4_),
    .B(MAR_REG_0_),
    .Y(_027_)
  );
  AOI21 _390_ (
    .A0(MAR_REG_4_),
    .A1(MAR_REG_0_),
    .B0(MAR_REG_2_),
    .Y(_028_)
  );
  INV _391_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR2 _392_ (
    .A(_024_),
    .B(_028_),
    .Y(_030_)
  );
  NAND2 _393_ (
    .A(STATO_REG_2_),
    .B(_030_),
    .Y(_031_)
  );
  NAND2 _394_ (
    .A(_355_),
    .B(STATO_REG_1_),
    .Y(_032_)
  );
  NAND2 _395_ (
    .A(STATO_REG_0_),
    .B(STATO_REG_1_),
    .Y(_033_)
  );
  OAI21 _396_ (
    .A0(_008_),
    .A1(_031_),
    .B0(_033_),
    .Y(U643)
  );
  NOR2 _397_ (
    .A(_007_),
    .B(_030_),
    .Y(_034_)
  );
  AOI21 _398_ (
    .A0(STATO_REG_0_),
    .A1(_000_),
    .B0(START),
    .Y(_035_)
  );
  INV _399_ (
    .A(_035_),
    .Y(_036_)
  );
  NOR2 _400_ (
    .A(_034_),
    .B(_036_),
    .Y(_037_)
  );
  OAI21 _401_ (
    .A0(_007_),
    .A1(_030_),
    .B0(_035_),
    .Y(_038_)
  );
  NAND2 _402_ (
    .A(_032_),
    .B(_037_),
    .Y(U644)
  );
  NOR2 _403_ (
    .A(STATO_REG_0_),
    .B(STATO_REG_2_),
    .Y(_039_)
  );
  OAI21 _404_ (
    .A0(STATO_REG_1_),
    .A1(START),
    .B0(_032_),
    .Y(_040_)
  );
  NOR3 _405_ (
    .A(_034_),
    .B(_039_),
    .C(_040_),
    .Y(_041_)
  );
  OAI21 _406_ (
    .A0(START),
    .A1(_031_),
    .B0(_041_),
    .Y(U645)
  );
  NOR2 _407_ (
    .A(RES_DISP_REG),
    .B(EN_DISP_REG),
    .Y(DISPMAX1_6_)
  );
  NOR2 _408_ (
    .A(MAX_REG_8_),
    .B(_353_),
    .Y(_042_)
  );
  NOR2 _409_ (
    .A(EN_DISP_REG),
    .B(_042_),
    .Y(SIGN)
  );
  NAND2 _410_ (
    .A(MAX_REG_1_),
    .B(_016_),
    .Y(_043_)
  );
  NOR3 _411_ (
    .A(MAX_REG_1_),
    .B(MAX_REG_0_),
    .C(MAX_REG_2_),
    .Y(_044_)
  );
  INV _412_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR2 _413_ (
    .A(MAX_REG_3_),
    .B(MAX_REG_4_),
    .Y(_046_)
  );
  NOR3 _414_ (
    .A(MAX_REG_3_),
    .B(MAX_REG_4_),
    .C(_045_),
    .Y(_047_)
  );
  NAND2 _415_ (
    .A(_044_),
    .B(_046_),
    .Y(_048_)
  );
  NOR2 _416_ (
    .A(_352_),
    .B(_047_),
    .Y(_049_)
  );
  NAND2 _417_ (
    .A(MAX_REG_8_),
    .B(_048_),
    .Y(_050_)
  );
  NOR2 _418_ (
    .A(_352_),
    .B(_044_),
    .Y(_051_)
  );
  XNOR2 _419_ (
    .A(MAX_REG_3_),
    .B(_051_),
    .Y(_052_)
  );
  XNOR2 _420_ (
    .A(MAX_REG_8_),
    .B(MAX_REG_1_),
    .Y(_053_)
  );
  OAI21 _421_ (
    .A0(_016_),
    .A1(_053_),
    .B0(_043_),
    .Y(_054_)
  );
  OAI21 _422_ (
    .A0(MAX_REG_1_),
    .A1(MAX_REG_0_),
    .B0(MAX_REG_8_),
    .Y(_055_)
  );
  XNOR2 _423_ (
    .A(MAX_REG_2_),
    .B(_055_),
    .Y(_056_)
  );
  NOR2 _424_ (
    .A(MAX_REG_8_),
    .B(_013_),
    .Y(_057_)
  );
  NAND2 _425_ (
    .A(MAX_REG_3_),
    .B(_057_),
    .Y(_058_)
  );
  INV _426_ (
    .A(_058_),
    .Y(_059_)
  );
  OAI21 _427_ (
    .A0(MAX_REG_8_),
    .A1(_013_),
    .B0(_056_),
    .Y(_060_)
  );
  OAI21 _428_ (
    .A0(_056_),
    .A1(_058_),
    .B0(_060_),
    .Y(_061_)
  );
  NOR2 _429_ (
    .A(_054_),
    .B(_061_),
    .Y(_062_)
  );
  NOR2 _430_ (
    .A(_054_),
    .B(_056_),
    .Y(_063_)
  );
  NOR3 _431_ (
    .A(_049_),
    .B(_052_),
    .C(_063_),
    .Y(_064_)
  );
  NOR2 _432_ (
    .A(_057_),
    .B(_064_),
    .Y(_065_)
  );
  NAND2 _433_ (
    .A(MAX_REG_1_),
    .B(_056_),
    .Y(_066_)
  );
  NOR2 _434_ (
    .A(_058_),
    .B(_066_),
    .Y(_067_)
  );
  AOI21 _435_ (
    .A0(MAX_REG_1_),
    .A1(_056_),
    .B0(_059_),
    .Y(_068_)
  );
  OAI21 _436_ (
    .A0(MAX_REG_3_),
    .A1(MAX_REG_2_),
    .B0(_057_),
    .Y(_069_)
  );
  INV _437_ (
    .A(_069_),
    .Y(_070_)
  );
  NOR2 _438_ (
    .A(_067_),
    .B(_069_),
    .Y(_071_)
  );
  NAND2 _439_ (
    .A(_068_),
    .B(_070_),
    .Y(_072_)
  );
  AOI21 _440_ (
    .A0(_056_),
    .A1(_057_),
    .B0(_068_),
    .Y(_073_)
  );
  NOR2 _441_ (
    .A(_062_),
    .B(_065_),
    .Y(_074_)
  );
  NAND2 _442_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  XOR2 _443_ (
    .A(_052_),
    .B(_075_),
    .Y(_076_)
  );
  XNOR2 _444_ (
    .A(_052_),
    .B(_075_),
    .Y(_077_)
  );
  NAND2 _445_ (
    .A(_056_),
    .B(_065_),
    .Y(_078_)
  );
  NOR2 _446_ (
    .A(_054_),
    .B(_071_),
    .Y(_079_)
  );
  XNOR2 _447_ (
    .A(_061_),
    .B(_079_),
    .Y(_080_)
  );
  OAI21 _448_ (
    .A0(_065_),
    .A1(_080_),
    .B0(_078_),
    .Y(_081_)
  );
  NOR2 _449_ (
    .A(_076_),
    .B(_081_),
    .Y(_082_)
  );
  NOR2 _450_ (
    .A(_049_),
    .B(_082_),
    .Y(_083_)
  );
  INV _451_ (
    .A(_083_),
    .Y(_084_)
  );
  NAND2 _452_ (
    .A(_050_),
    .B(_076_),
    .Y(_085_)
  );
  INV _453_ (
    .A(_085_),
    .Y(_086_)
  );
  OAI21 _454_ (
    .A0(_057_),
    .A1(_064_),
    .B0(_072_),
    .Y(_087_)
  );
  XNOR2 _455_ (
    .A(_054_),
    .B(_087_),
    .Y(_088_)
  );
  INV _456_ (
    .A(_088_),
    .Y(_089_)
  );
  OAI21 _457_ (
    .A0(_016_),
    .A1(_089_),
    .B0(_077_),
    .Y(_090_)
  );
  OAI21 _458_ (
    .A0(_084_),
    .A1(_090_),
    .B0(_085_),
    .Y(_091_)
  );
  NOR2 _459_ (
    .A(_049_),
    .B(_089_),
    .Y(_092_)
  );
  NAND2 _460_ (
    .A(_082_),
    .B(_092_),
    .Y(_093_)
  );
  NAND2 _461_ (
    .A(RES_DISP_REG),
    .B(_093_),
    .Y(_094_)
  );
  NAND2 _462_ (
    .A(_083_),
    .B(_090_),
    .Y(_095_)
  );
  NOR2 _463_ (
    .A(_091_),
    .B(_094_),
    .Y(_096_)
  );
  NOR2 _464_ (
    .A(EN_DISP_REG),
    .B(_096_),
    .Y(DISPMAX3_6_)
  );
  NOR2 _465_ (
    .A(MAX_REG_0_),
    .B(_088_),
    .Y(_097_)
  );
  INV _466_ (
    .A(_097_),
    .Y(_098_)
  );
  OAI21 _467_ (
    .A0(_081_),
    .A1(_098_),
    .B0(_050_),
    .Y(_099_)
  );
  NAND2 _468_ (
    .A(_085_),
    .B(_099_),
    .Y(_100_)
  );
  NAND2 _469_ (
    .A(_093_),
    .B(_100_),
    .Y(_101_)
  );
  NAND2 _470_ (
    .A(_077_),
    .B(_097_),
    .Y(_102_)
  );
  NAND2 _471_ (
    .A(_083_),
    .B(_102_),
    .Y(_103_)
  );
  NOR2 _472_ (
    .A(_090_),
    .B(_103_),
    .Y(_104_)
  );
  NOR3 _473_ (
    .A(_086_),
    .B(_101_),
    .C(_104_),
    .Y(_105_)
  );
  NOR2 _474_ (
    .A(_018_),
    .B(_105_),
    .Y(DISPMAX3_5_)
  );
  NOR2 _475_ (
    .A(MAX_REG_0_),
    .B(_093_),
    .Y(_106_)
  );
  NOR2 _476_ (
    .A(_018_),
    .B(_106_),
    .Y(DISPMAX3_4_)
  );
  NOR2 _477_ (
    .A(_018_),
    .B(_104_),
    .Y(DISPMAX3_3_)
  );
  NAND2 _478_ (
    .A(MAX_REG_0_),
    .B(_092_),
    .Y(_107_)
  );
  AOI22 _479_ (
    .A0(_083_),
    .A1(_102_),
    .B0(_107_),
    .B1(_101_),
    .Y(_108_)
  );
  NOR2 _480_ (
    .A(_018_),
    .B(_108_),
    .Y(DISPMAX3_2_)
  );
  NOR2 _481_ (
    .A(_091_),
    .B(_099_),
    .Y(_109_)
  );
  NOR2 _482_ (
    .A(_018_),
    .B(_109_),
    .Y(DISPMAX3_1_)
  );
  AOI21 _483_ (
    .A0(_081_),
    .A1(_092_),
    .B0(_095_),
    .Y(_110_)
  );
  OAI21 _484_ (
    .A0(_016_),
    .A1(_093_),
    .B0(_110_),
    .Y(_111_)
  );
  NOR2 _485_ (
    .A(_099_),
    .B(_111_),
    .Y(_112_)
  );
  NOR2 _486_ (
    .A(_018_),
    .B(_112_),
    .Y(DISPMAX3_0_)
  );
  NOR2 _487_ (
    .A(_015_),
    .B(_019_),
    .Y(_113_)
  );
  NOR2 _488_ (
    .A(_015_),
    .B(_021_),
    .Y(_114_)
  );
  OAI21 _489_ (
    .A0(NUM_REG_3_),
    .A1(_113_),
    .B0(_021_),
    .Y(_115_)
  );
  OAI21 _490_ (
    .A0(_015_),
    .A1(_021_),
    .B0(_115_),
    .Y(_116_)
  );
  INV _491_ (
    .A(_116_),
    .Y(_117_)
  );
  OAI21 _492_ (
    .A0(NUM_REG_1_),
    .A1(_022_),
    .B0(NUM_REG_2_),
    .Y(_118_)
  );
  NAND2 _493_ (
    .A(NUM_REG_4_),
    .B(_019_),
    .Y(_119_)
  );
  NAND2 _494_ (
    .A(_118_),
    .B(_119_),
    .Y(_120_)
  );
  NOR2 _495_ (
    .A(_116_),
    .B(_120_),
    .Y(_121_)
  );
  AOI21 _496_ (
    .A0(_117_),
    .A1(_118_),
    .B0(_119_),
    .Y(_122_)
  );
  XNOR2 _497_ (
    .A(NUM_REG_1_),
    .B(_022_),
    .Y(_123_)
  );
  NAND2 _498_ (
    .A(NUM_REG_0_),
    .B(_123_),
    .Y(_124_)
  );
  INV _499_ (
    .A(_124_),
    .Y(_125_)
  );
  NAND2 _500_ (
    .A(_117_),
    .B(_124_),
    .Y(_126_)
  );
  NAND2 _501_ (
    .A(_122_),
    .B(_126_),
    .Y(_127_)
  );
  OAI21 _502_ (
    .A0(_122_),
    .A1(_123_),
    .B0(_127_),
    .Y(_128_)
  );
  NOR2 _503_ (
    .A(_116_),
    .B(_124_),
    .Y(_129_)
  );
  NOR2 _504_ (
    .A(_121_),
    .B(_129_),
    .Y(_130_)
  );
  NAND2 _505_ (
    .A(RES_DISP_REG),
    .B(_128_),
    .Y(_131_)
  );
  NOR2 _506_ (
    .A(_130_),
    .B(_131_),
    .Y(_132_)
  );
  NOR2 _507_ (
    .A(EN_DISP_REG),
    .B(_132_),
    .Y(DISPNUM2_6_)
  );
  NOR3 _508_ (
    .A(NUM_REG_0_),
    .B(NUM_REG_2_),
    .C(_123_),
    .Y(_133_)
  );
  OAI21 _509_ (
    .A0(_123_),
    .A1(_133_),
    .B0(_121_),
    .Y(_134_)
  );
  OAI21 _510_ (
    .A0(NUM_REG_0_),
    .A1(_123_),
    .B0(_120_),
    .Y(_135_)
  );
  INV _511_ (
    .A(_135_),
    .Y(_136_)
  );
  NOR2 _512_ (
    .A(_116_),
    .B(_136_),
    .Y(_137_)
  );
  OAI21 _513_ (
    .A0(_129_),
    .A1(_137_),
    .B0(_134_),
    .Y(_138_)
  );
  INV _514_ (
    .A(_138_),
    .Y(_139_)
  );
  NOR2 _515_ (
    .A(_018_),
    .B(_139_),
    .Y(DISPNUM2_5_)
  );
  NAND2 _516_ (
    .A(_121_),
    .B(_123_),
    .Y(_140_)
  );
  NOR2 _517_ (
    .A(NUM_REG_0_),
    .B(_140_),
    .Y(_141_)
  );
  NOR2 _518_ (
    .A(_018_),
    .B(_141_),
    .Y(DISPNUM2_4_)
  );
  NOR2 _519_ (
    .A(_126_),
    .B(_135_),
    .Y(_142_)
  );
  NOR2 _520_ (
    .A(_018_),
    .B(_142_),
    .Y(DISPNUM2_3_)
  );
  NOR2 _521_ (
    .A(_125_),
    .B(_134_),
    .Y(_143_)
  );
  NOR3 _522_ (
    .A(_116_),
    .B(_136_),
    .C(_143_),
    .Y(_144_)
  );
  NOR2 _523_ (
    .A(_018_),
    .B(_144_),
    .Y(DISPNUM2_2_)
  );
  NOR2 _524_ (
    .A(_130_),
    .B(_133_),
    .Y(_145_)
  );
  NOR2 _525_ (
    .A(_018_),
    .B(_145_),
    .Y(DISPNUM2_1_)
  );
  NAND2 _526_ (
    .A(_120_),
    .B(_123_),
    .Y(_146_)
  );
  OAI21 _527_ (
    .A0(_125_),
    .A1(_133_),
    .B0(_121_),
    .Y(_147_)
  );
  AOI22 _528_ (
    .A0(_122_),
    .A1(_126_),
    .B0(_146_),
    .B1(_147_),
    .Y(_148_)
  );
  NOR2 _529_ (
    .A(_115_),
    .B(_133_),
    .Y(_149_)
  );
  NOR3 _530_ (
    .A(_018_),
    .B(_114_),
    .C(_149_),
    .Y(_150_)
  );
  OAI21 _531_ (
    .A0(_116_),
    .A1(_148_),
    .B0(_150_),
    .Y(_151_)
  );
  INV _532_ (
    .A(_151_),
    .Y(DISPNUM2_0_)
  );
  NAND2 _533_ (
    .A(RES_DISP_REG),
    .B(_069_),
    .Y(_152_)
  );
  INV _534_ (
    .A(_152_),
    .Y(_153_)
  );
  NOR2 _535_ (
    .A(EN_DISP_REG),
    .B(_153_),
    .Y(DISPMAX2_6_)
  );
  NAND2 _536_ (
    .A(DISPMAX1_3_),
    .B(_065_),
    .Y(_154_)
  );
  INV _537_ (
    .A(_154_),
    .Y(DISPMAX2_1_)
  );
  OAI21 _538_ (
    .A0(_018_),
    .A1(_069_),
    .B0(_154_),
    .Y(DISPMAX2_5_)
  );
  INV _539_ (
    .A(DISPMAX2_5_),
    .Y(_155_)
  );
  NOR2 _540_ (
    .A(_018_),
    .B(_071_),
    .Y(DISPMAX2_4_)
  );
  NOR2 _541_ (
    .A(_067_),
    .B(_155_),
    .Y(DISPMAX2_2_)
  );
  OAI21 _542_ (
    .A0(_018_),
    .A1(_068_),
    .B0(_154_),
    .Y(DISPMAX2_0_)
  );
  NAND2 _543_ (
    .A(MAR_REG_1_),
    .B(_026_),
    .Y(_156_)
  );
  NOR3 _544_ (
    .A(MAR_REG_4_),
    .B(_004_),
    .C(_006_),
    .Y(_157_)
  );
  AOI21 _545_ (
    .A0(MAR_REG_1_),
    .A1(MAR_REG_3_),
    .B0(_157_),
    .Y(_158_)
  );
  NOR2 _546_ (
    .A(MAR_REG_2_),
    .B(_027_),
    .Y(_159_)
  );
  NOR2 _547_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_3_),
    .Y(_160_)
  );
  NOR3 _548_ (
    .A(_003_),
    .B(MAR_REG_0_),
    .C(MAR_REG_2_),
    .Y(_161_)
  );
  NAND2 _549_ (
    .A(_160_),
    .B(_161_),
    .Y(_162_)
  );
  AOI22 _550_ (
    .A0(_025_),
    .A1(_159_),
    .B0(_160_),
    .B1(_161_),
    .Y(_163_)
  );
  NOR3 _551_ (
    .A(MAR_REG_4_),
    .B(_004_),
    .C(MAR_REG_2_),
    .Y(_164_)
  );
  NAND2 _552_ (
    .A(_025_),
    .B(_164_),
    .Y(_165_)
  );
  NAND2 _553_ (
    .A(_023_),
    .B(_159_),
    .Y(_166_)
  );
  AOI21 _554_ (
    .A0(_003_),
    .A1(_004_),
    .B0(_160_),
    .Y(_167_)
  );
  NOR3 _555_ (
    .A(MAR_REG_4_),
    .B(MAR_REG_0_),
    .C(_006_),
    .Y(_168_)
  );
  NAND2 _556_ (
    .A(_160_),
    .B(_168_),
    .Y(_169_)
  );
  AOI21 _557_ (
    .A0(_158_),
    .A1(_163_),
    .B0(_166_),
    .Y(_170_)
  );
  INV _558_ (
    .A(_170_),
    .Y(_171_)
  );
  NAND2 _559_ (
    .A(_165_),
    .B(_169_),
    .Y(_172_)
  );
  NOR2 _560_ (
    .A(_170_),
    .B(_172_),
    .Y(_173_)
  );
  AOI21 _561_ (
    .A0(_165_),
    .A1(_169_),
    .B0(_171_),
    .Y(_174_)
  );
  NOR3 _562_ (
    .A(_003_),
    .B(MAR_REG_0_),
    .C(_006_),
    .Y(_175_)
  );
  AOI21 _563_ (
    .A0(MAR_REG_4_),
    .A1(_004_),
    .B0(MAR_REG_2_),
    .Y(_176_)
  );
  OAI21 _564_ (
    .A0(MAR_REG_2_),
    .A1(_027_),
    .B0(_176_),
    .Y(_177_)
  );
  OAI21 _565_ (
    .A0(_159_),
    .A1(_175_),
    .B0(_160_),
    .Y(_178_)
  );
  NOR2 _566_ (
    .A(_002_),
    .B(MAR_REG_3_),
    .Y(_179_)
  );
  NAND2 _567_ (
    .A(MAR_REG_1_),
    .B(_005_),
    .Y(_180_)
  );
  OAI21 _568_ (
    .A0(_161_),
    .A1(_168_),
    .B0(_179_),
    .Y(_181_)
  );
  XNOR2 _569_ (
    .A(_002_),
    .B(MAR_REG_3_),
    .Y(_182_)
  );
  NAND2 _570_ (
    .A(_164_),
    .B(_182_),
    .Y(_183_)
  );
  AOI22 _571_ (
    .A0(_160_),
    .A1(_177_),
    .B0(_182_),
    .B1(_164_),
    .Y(_184_)
  );
  AOI21 _572_ (
    .A0(_178_),
    .A1(_181_),
    .B0(_183_),
    .Y(_185_)
  );
  OAI21 _573_ (
    .A0(_157_),
    .A1(_159_),
    .B0(_179_),
    .Y(_186_)
  );
  NOR3 _574_ (
    .A(MAR_REG_4_),
    .B(MAR_REG_0_),
    .C(MAR_REG_2_),
    .Y(_187_)
  );
  NAND2 _575_ (
    .A(MAR_REG_3_),
    .B(_187_),
    .Y(_188_)
  );
  NAND2 _576_ (
    .A(_186_),
    .B(_188_),
    .Y(_189_)
  );
  NOR3 _577_ (
    .A(_174_),
    .B(_185_),
    .C(_189_),
    .Y(_190_)
  );
  NOR3 _578_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_3_),
    .C(_028_),
    .Y(_191_)
  );
  NAND2 _579_ (
    .A(_029_),
    .B(_160_),
    .Y(_192_)
  );
  NOR2 _580_ (
    .A(_185_),
    .B(_191_),
    .Y(_193_)
  );
  AOI21 _581_ (
    .A0(_181_),
    .A1(_184_),
    .B0(_192_),
    .Y(_194_)
  );
  NAND2 _582_ (
    .A(_160_),
    .B(_164_),
    .Y(_195_)
  );
  NAND2 _583_ (
    .A(_175_),
    .B(_179_),
    .Y(_196_)
  );
  AOI22 _584_ (
    .A0(_023_),
    .A1(_026_),
    .B0(_175_),
    .B1(_179_),
    .Y(_197_)
  );
  AOI21 _585_ (
    .A0(_163_),
    .A1(_195_),
    .B0(_197_),
    .Y(_198_)
  );
  AOI21 _586_ (
    .A0(_004_),
    .A1(MAR_REG_2_),
    .B0(_025_),
    .Y(_199_)
  );
  AOI22 _587_ (
    .A0(_025_),
    .A1(_029_),
    .B0(_187_),
    .B1(MAR_REG_3_),
    .Y(_200_)
  );
  AOI21 _588_ (
    .A0(_167_),
    .A1(_199_),
    .B0(_200_),
    .Y(_201_)
  );
  OAI21 _589_ (
    .A0(MAR_REG_4_),
    .A1(_156_),
    .B0(_165_),
    .Y(_202_)
  );
  NOR2 _590_ (
    .A(_201_),
    .B(_202_),
    .Y(_203_)
  );
  NAND2 _591_ (
    .A(_193_),
    .B(_203_),
    .Y(_204_)
  );
  NOR2 _592_ (
    .A(_198_),
    .B(_204_),
    .Y(_205_)
  );
  NOR2 _593_ (
    .A(TEMP_REG_5_),
    .B(_205_),
    .Y(_206_)
  );
  INV _594_ (
    .A(_206_),
    .Y(_207_)
  );
  AOI21 _595_ (
    .A0(_165_),
    .A1(_186_),
    .B0(_196_),
    .Y(_208_)
  );
  NOR2 _596_ (
    .A(_201_),
    .B(_208_),
    .Y(_209_)
  );
  NAND2 _597_ (
    .A(TEMP_REG_4_),
    .B(_209_),
    .Y(_210_)
  );
  AOI22 _598_ (
    .A0(_157_),
    .A1(_160_),
    .B0(_161_),
    .B1(_023_),
    .Y(_211_)
  );
  AOI22 _599_ (
    .A0(_023_),
    .A1(_159_),
    .B0(_179_),
    .B1(_029_),
    .Y(_212_)
  );
  AOI21 _600_ (
    .A0(_188_),
    .A1(_211_),
    .B0(_212_),
    .Y(_213_)
  );
  NOR2 _601_ (
    .A(_198_),
    .B(_213_),
    .Y(_214_)
  );
  NOR3 _602_ (
    .A(_011_),
    .B(_198_),
    .C(_213_),
    .Y(_215_)
  );
  NAND2 _603_ (
    .A(TEMP_REG_3_),
    .B(_214_),
    .Y(_216_)
  );
  AOI21 _604_ (
    .A0(_162_),
    .A1(_166_),
    .B0(_169_),
    .Y(_217_)
  );
  NOR2 _605_ (
    .A(_208_),
    .B(_217_),
    .Y(_218_)
  );
  NOR3 _606_ (
    .A(_194_),
    .B(_208_),
    .C(_217_),
    .Y(_219_)
  );
  NAND2 _607_ (
    .A(_193_),
    .B(_218_),
    .Y(_220_)
  );
  OAI21 _608_ (
    .A0(_027_),
    .A1(_180_),
    .B0(_211_),
    .Y(_221_)
  );
  NOR3 _609_ (
    .A(_170_),
    .B(_201_),
    .C(_221_),
    .Y(_222_)
  );
  NAND2 _610_ (
    .A(_158_),
    .B(_211_),
    .Y(_223_)
  );
  NOR3 _611_ (
    .A(_185_),
    .B(_208_),
    .C(_223_),
    .Y(_224_)
  );
  AOI22 _612_ (
    .A0(TEMP_REG_1_),
    .A1(_222_),
    .B0(_224_),
    .B1(TEMP_REG_0_),
    .Y(_225_)
  );
  NOR2 _613_ (
    .A(TEMP_REG_1_),
    .B(_222_),
    .Y(_226_)
  );
  OAI22 _614_ (
    .A0(TEMP_REG_2_),
    .A1(_219_),
    .B0(_222_),
    .B1(TEMP_REG_1_),
    .Y(_227_)
  );
  OAI22 _615_ (
    .A0(_012_),
    .A1(_220_),
    .B0(_225_),
    .B1(_226_),
    .Y(_228_)
  );
  OAI21 _616_ (
    .A0(TEMP_REG_2_),
    .A1(_219_),
    .B0(_228_),
    .Y(_229_)
  );
  OAI22 _617_ (
    .A0(_012_),
    .A1(_220_),
    .B0(_225_),
    .B1(_227_),
    .Y(_230_)
  );
  NAND2 _618_ (
    .A(_216_),
    .B(_229_),
    .Y(_231_)
  );
  NOR2 _619_ (
    .A(TEMP_REG_4_),
    .B(_209_),
    .Y(_232_)
  );
  NOR2 _620_ (
    .A(TEMP_REG_3_),
    .B(_214_),
    .Y(_233_)
  );
  NOR2 _621_ (
    .A(_232_),
    .B(_233_),
    .Y(_234_)
  );
  OAI21 _622_ (
    .A0(_215_),
    .A1(_230_),
    .B0(_234_),
    .Y(_235_)
  );
  AOI22 _623_ (
    .A0(TEMP_REG_4_),
    .A1(_209_),
    .B0(_231_),
    .B1(_234_),
    .Y(_236_)
  );
  NAND2 _624_ (
    .A(_196_),
    .B(_211_),
    .Y(_237_)
  );
  NOR3 _625_ (
    .A(_174_),
    .B(_194_),
    .C(_237_),
    .Y(_238_)
  );
  NAND2 _626_ (
    .A(TEMP_REG_6_),
    .B(_238_),
    .Y(_239_)
  );
  INV _627_ (
    .A(_239_),
    .Y(_240_)
  );
  NAND2 _628_ (
    .A(TEMP_REG_5_),
    .B(_205_),
    .Y(_241_)
  );
  NAND2 _629_ (
    .A(_239_),
    .B(_241_),
    .Y(_242_)
  );
  INV _630_ (
    .A(_242_),
    .Y(_243_)
  );
  AOI21 _631_ (
    .A0(_210_),
    .A1(_235_),
    .B0(_241_),
    .Y(_244_)
  );
  AOI22 _632_ (
    .A0(TEMP_REG_6_),
    .A1(_238_),
    .B0(_244_),
    .B1(_207_),
    .Y(_245_)
  );
  OAI21 _633_ (
    .A0(_206_),
    .A1(_236_),
    .B0(_243_),
    .Y(_246_)
  );
  OAI22 _634_ (
    .A0(TEMP_REG_7_),
    .A1(_190_),
    .B0(_238_),
    .B1(TEMP_REG_6_),
    .Y(_247_)
  );
  INV _635_ (
    .A(_247_),
    .Y(_248_)
  );
  AOI22 _636_ (
    .A0(TEMP_REG_7_),
    .A1(_190_),
    .B0(_246_),
    .B1(_248_),
    .Y(_249_)
  );
  XNOR2 _637_ (
    .A(TEMP_REG_8_),
    .B(_173_),
    .Y(_250_)
  );
  XOR2 _638_ (
    .A(_249_),
    .B(_250_),
    .Y(_251_)
  );
  XNOR2 _639_ (
    .A(_249_),
    .B(_250_),
    .Y(_252_)
  );
  NAND2 _640_ (
    .A(STATO_REG_1_),
    .B(_251_),
    .Y(_253_)
  );
  OAI21 _641_ (
    .A0(STATO_REG_1_),
    .A1(START),
    .B0(STATO_REG_0_),
    .Y(_254_)
  );
  INV _642_ (
    .A(_254_),
    .Y(_255_)
  );
  NAND2 _643_ (
    .A(_253_),
    .B(_255_),
    .Y(_256_)
  );
  NAND2 _644_ (
    .A(FLAG_REG),
    .B(_256_),
    .Y(_257_)
  );
  XNOR2 _645_ (
    .A(_010_),
    .B(_190_),
    .Y(_258_)
  );
  OAI21 _646_ (
    .A0(TEMP_REG_6_),
    .A1(_238_),
    .B0(_258_),
    .Y(_259_)
  );
  NOR2 _647_ (
    .A(_245_),
    .B(_259_),
    .Y(_260_)
  );
  NOR3 _648_ (
    .A(_229_),
    .B(_232_),
    .C(_233_),
    .Y(_261_)
  );
  OAI21 _649_ (
    .A0(_206_),
    .A1(_261_),
    .B0(_210_),
    .Y(_262_)
  );
  INV _650_ (
    .A(_262_),
    .Y(_263_)
  );
  OAI21 _651_ (
    .A0(_215_),
    .A1(_233_),
    .B0(_229_),
    .Y(_264_)
  );
  OAI21 _652_ (
    .A0(_210_),
    .A1(_241_),
    .B0(_259_),
    .Y(_265_)
  );
  NOR2 _653_ (
    .A(_240_),
    .B(_258_),
    .Y(_266_)
  );
  XNOR2 _654_ (
    .A(TEMP_REG_0_),
    .B(_224_),
    .Y(_267_)
  );
  XNOR2 _655_ (
    .A(TEMP_REG_1_),
    .B(_222_),
    .Y(_268_)
  );
  NOR2 _656_ (
    .A(_267_),
    .B(_268_),
    .Y(_269_)
  );
  XNOR2 _657_ (
    .A(TEMP_REG_4_),
    .B(_209_),
    .Y(_270_)
  );
  NAND2 _658_ (
    .A(_216_),
    .B(_270_),
    .Y(_271_)
  );
  XNOR2 _659_ (
    .A(_012_),
    .B(_219_),
    .Y(_272_)
  );
  AOI21 _660_ (
    .A0(_269_),
    .A1(_271_),
    .B0(_272_),
    .Y(_273_)
  );
  NOR2 _661_ (
    .A(_266_),
    .B(_273_),
    .Y(_274_)
  );
  AOI21 _662_ (
    .A0(_264_),
    .A1(_265_),
    .B0(_274_),
    .Y(_275_)
  );
  NOR3 _663_ (
    .A(_260_),
    .B(_263_),
    .C(_275_),
    .Y(_276_)
  );
  NOR3 _664_ (
    .A(_000_),
    .B(_252_),
    .C(_276_),
    .Y(_277_)
  );
  NAND2 _665_ (
    .A(STATO_REG_0_),
    .B(_277_),
    .Y(_278_)
  );
  NAND2 _666_ (
    .A(_257_),
    .B(_278_),
    .Y(U668)
  );
  NOR3 _667_ (
    .A(STATO_REG_0_),
    .B(STATO_REG_1_),
    .C(STATO_REG_2_),
    .Y(_279_)
  );
  OAI21 _668_ (
    .A0(_353_),
    .A1(_279_),
    .B0(_035_),
    .Y(U669)
  );
  OAI21 _669_ (
    .A0(_354_),
    .A1(_279_),
    .B0(_031_),
    .Y(_280_)
  );
  OAI21 _670_ (
    .A0(STATO_REG_0_),
    .A1(_031_),
    .B0(_280_),
    .Y(_281_)
  );
  NAND2 _671_ (
    .A(_035_),
    .B(_281_),
    .Y(U670)
  );
  NAND2 _672_ (
    .A(MAR_REG_0_),
    .B(_038_),
    .Y(_282_)
  );
  OAI21 _673_ (
    .A0(MAR_REG_0_),
    .A1(STATO_REG_2_),
    .B0(_282_),
    .Y(_283_)
  );
  INV _674_ (
    .A(_283_),
    .Y(U671)
  );
  XNOR2 _675_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_0_),
    .Y(_284_)
  );
  OAI22 _676_ (
    .A0(_002_),
    .A1(_038_),
    .B0(_284_),
    .B1(_007_),
    .Y(U672)
  );
  AOI21 _677_ (
    .A0(MAR_REG_1_),
    .A1(MAR_REG_0_),
    .B0(STATO_REG_2_),
    .Y(_285_)
  );
  NAND2 _678_ (
    .A(STATO_REG_2_),
    .B(_156_),
    .Y(_286_)
  );
  NAND2 _679_ (
    .A(_038_),
    .B(_286_),
    .Y(_287_)
  );
  AOI22 _680_ (
    .A0(_006_),
    .A1(_285_),
    .B0(_286_),
    .B1(_038_),
    .Y(U673)
  );
  NAND2 _681_ (
    .A(_005_),
    .B(MAR_REG_2_),
    .Y(_288_)
  );
  NAND2 _682_ (
    .A(MAR_REG_3_),
    .B(_287_),
    .Y(_289_)
  );
  OAI21 _683_ (
    .A0(_285_),
    .A1(_288_),
    .B0(_289_),
    .Y(U674)
  );
  OAI21 _684_ (
    .A0(_005_),
    .A1(_156_),
    .B0(MAR_REG_4_),
    .Y(_290_)
  );
  NAND2 _685_ (
    .A(_158_),
    .B(_290_),
    .Y(_291_)
  );
  AOI22 _686_ (
    .A0(MAR_REG_4_),
    .A1(_037_),
    .B0(_291_),
    .B1(STATO_REG_2_),
    .Y(_292_)
  );
  INV _687_ (
    .A(_292_),
    .Y(U675)
  );
  NOR2 _688_ (
    .A(_001_),
    .B(_033_),
    .Y(_293_)
  );
  NAND2 _689_ (
    .A(_252_),
    .B(_293_),
    .Y(_294_)
  );
  NAND2 _690_ (
    .A(STATO_REG_1_),
    .B(_001_),
    .Y(_295_)
  );
  AOI21 _691_ (
    .A0(_253_),
    .A1(_255_),
    .B0(_295_),
    .Y(_296_)
  );
  NAND2 _692_ (
    .A(NUM_REG_0_),
    .B(_296_),
    .Y(_297_)
  );
  OAI21 _693_ (
    .A0(NUM_REG_0_),
    .A1(_294_),
    .B0(_297_),
    .Y(U676)
  );
  NAND2 _694_ (
    .A(NUM_REG_1_),
    .B(_296_),
    .Y(_298_)
  );
  NAND2 _695_ (
    .A(NUM_REG_1_),
    .B(NUM_REG_0_),
    .Y(_299_)
  );
  XNOR2 _696_ (
    .A(NUM_REG_1_),
    .B(NUM_REG_0_),
    .Y(_300_)
  );
  OAI21 _697_ (
    .A0(_294_),
    .A1(_300_),
    .B0(_298_),
    .Y(U677)
  );
  NAND2 _698_ (
    .A(NUM_REG_2_),
    .B(_296_),
    .Y(_301_)
  );
  AOI21 _699_ (
    .A0(NUM_REG_1_),
    .A1(NUM_REG_0_),
    .B0(NUM_REG_2_),
    .Y(_302_)
  );
  XNOR2 _700_ (
    .A(_014_),
    .B(_299_),
    .Y(_303_)
  );
  OAI21 _701_ (
    .A0(_294_),
    .A1(_303_),
    .B0(_301_),
    .Y(U678)
  );
  NOR2 _702_ (
    .A(_294_),
    .B(_302_),
    .Y(_304_)
  );
  NOR2 _703_ (
    .A(_009_),
    .B(_302_),
    .Y(_305_)
  );
  NOR2 _704_ (
    .A(_294_),
    .B(_305_),
    .Y(_306_)
  );
  NOR2 _705_ (
    .A(NUM_REG_3_),
    .B(_304_),
    .Y(_307_)
  );
  NOR2 _706_ (
    .A(_296_),
    .B(_306_),
    .Y(_308_)
  );
  NOR2 _707_ (
    .A(_307_),
    .B(_308_),
    .Y(U679)
  );
  NOR3 _708_ (
    .A(_009_),
    .B(_294_),
    .C(_302_),
    .Y(_309_)
  );
  NAND2 _709_ (
    .A(_015_),
    .B(_309_),
    .Y(_310_)
  );
  OAI21 _710_ (
    .A0(_015_),
    .A1(_308_),
    .B0(_310_),
    .Y(U680)
  );
  NAND2 _711_ (
    .A(_000_),
    .B(TEMP_REG_8_),
    .Y(_311_)
  );
  OAI21 _712_ (
    .A0(_000_),
    .A1(_173_),
    .B0(_311_),
    .Y(U727)
  );
  NAND2 _713_ (
    .A(STATO_REG_1_),
    .B(_190_),
    .Y(_312_)
  );
  OAI21 _714_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_7_),
    .B0(_312_),
    .Y(_313_)
  );
  INV _715_ (
    .A(_313_),
    .Y(U728)
  );
  NAND2 _716_ (
    .A(STATO_REG_1_),
    .B(_238_),
    .Y(_314_)
  );
  OAI21 _717_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_6_),
    .B0(_314_),
    .Y(_315_)
  );
  INV _718_ (
    .A(_315_),
    .Y(U729)
  );
  NAND2 _719_ (
    .A(STATO_REG_1_),
    .B(_205_),
    .Y(_316_)
  );
  OAI21 _720_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_5_),
    .B0(_316_),
    .Y(_317_)
  );
  INV _721_ (
    .A(_317_),
    .Y(U730)
  );
  NAND2 _722_ (
    .A(STATO_REG_1_),
    .B(_209_),
    .Y(_318_)
  );
  OAI21 _723_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_4_),
    .B0(_318_),
    .Y(_319_)
  );
  INV _724_ (
    .A(_319_),
    .Y(U731)
  );
  NAND2 _725_ (
    .A(STATO_REG_1_),
    .B(_214_),
    .Y(_320_)
  );
  OAI21 _726_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_3_),
    .B0(_320_),
    .Y(_321_)
  );
  INV _727_ (
    .A(_321_),
    .Y(U732)
  );
  NAND2 _728_ (
    .A(_000_),
    .B(TEMP_REG_2_),
    .Y(_322_)
  );
  OAI21 _729_ (
    .A0(_000_),
    .A1(_219_),
    .B0(_322_),
    .Y(U733)
  );
  NAND2 _730_ (
    .A(STATO_REG_1_),
    .B(_222_),
    .Y(_323_)
  );
  OAI21 _731_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_1_),
    .B0(_323_),
    .Y(_324_)
  );
  INV _732_ (
    .A(_324_),
    .Y(U734)
  );
  NAND2 _733_ (
    .A(STATO_REG_1_),
    .B(_224_),
    .Y(_325_)
  );
  OAI21 _734_ (
    .A0(STATO_REG_1_),
    .A1(TEMP_REG_0_),
    .B0(_325_),
    .Y(_326_)
  );
  INV _735_ (
    .A(_326_),
    .Y(U735)
  );
  NAND2 _736_ (
    .A(_017_),
    .B(_220_),
    .Y(_327_)
  );
  NOR2 _737_ (
    .A(MAX_REG_1_),
    .B(_222_),
    .Y(_328_)
  );
  AOI22 _738_ (
    .A0(MAX_REG_1_),
    .A1(_222_),
    .B0(_224_),
    .B1(MAX_REG_0_),
    .Y(_329_)
  );
  OAI22 _739_ (
    .A0(_017_),
    .A1(_220_),
    .B0(_328_),
    .B1(_329_),
    .Y(_330_)
  );
  AOI22 _740_ (
    .A0(MAX_REG_3_),
    .A1(_214_),
    .B0(_327_),
    .B1(_330_),
    .Y(_331_)
  );
  OAI22 _741_ (
    .A0(MAX_REG_4_),
    .A1(_209_),
    .B0(_214_),
    .B1(MAX_REG_3_),
    .Y(_332_)
  );
  AOI22 _742_ (
    .A0(MAX_REG_5_),
    .A1(_205_),
    .B0(_209_),
    .B1(MAX_REG_4_),
    .Y(_333_)
  );
  OAI21 _743_ (
    .A0(_331_),
    .A1(_332_),
    .B0(_333_),
    .Y(_334_)
  );
  NOR2 _744_ (
    .A(MAX_REG_6_),
    .B(_238_),
    .Y(_335_)
  );
  OAI21 _745_ (
    .A0(MAX_REG_5_),
    .A1(_205_),
    .B0(_334_),
    .Y(_336_)
  );
  AOI22 _746_ (
    .A0(MAX_REG_7_),
    .A1(_190_),
    .B0(_238_),
    .B1(MAX_REG_6_),
    .Y(_337_)
  );
  OAI21 _747_ (
    .A0(_335_),
    .A1(_336_),
    .B0(_337_),
    .Y(_338_)
  );
  OAI21 _748_ (
    .A0(MAX_REG_7_),
    .A1(_190_),
    .B0(_338_),
    .Y(_339_)
  );
  XNOR2 _749_ (
    .A(MAX_REG_8_),
    .B(_173_),
    .Y(_340_)
  );
  XNOR2 _750_ (
    .A(_339_),
    .B(_340_),
    .Y(_341_)
  );
  AOI22 _751_ (
    .A0(_355_),
    .A1(STATO_REG_1_),
    .B0(_277_),
    .B1(_341_),
    .Y(_342_)
  );
  NAND2 _752_ (
    .A(MAX_REG_8_),
    .B(_342_),
    .Y(_343_)
  );
  OAI21 _753_ (
    .A0(_173_),
    .A1(_342_),
    .B0(_343_),
    .Y(U736)
  );
  NAND2 _754_ (
    .A(MAX_REG_7_),
    .B(_342_),
    .Y(_344_)
  );
  OAI21 _755_ (
    .A0(_190_),
    .A1(_342_),
    .B0(_344_),
    .Y(U737)
  );
  NAND2 _756_ (
    .A(MAX_REG_6_),
    .B(_342_),
    .Y(_345_)
  );
  OAI21 _757_ (
    .A0(_238_),
    .A1(_342_),
    .B0(_345_),
    .Y(U738)
  );
  NAND2 _758_ (
    .A(MAX_REG_5_),
    .B(_342_),
    .Y(_346_)
  );
  OAI21 _759_ (
    .A0(_205_),
    .A1(_342_),
    .B0(_346_),
    .Y(U739)
  );
  NAND2 _760_ (
    .A(MAX_REG_4_),
    .B(_342_),
    .Y(_347_)
  );
  OAI21 _761_ (
    .A0(_209_),
    .A1(_342_),
    .B0(_347_),
    .Y(U740)
  );
  NAND2 _762_ (
    .A(MAX_REG_3_),
    .B(_342_),
    .Y(_348_)
  );
  OAI21 _763_ (
    .A0(_214_),
    .A1(_342_),
    .B0(_348_),
    .Y(U741)
  );
  NAND2 _764_ (
    .A(MAX_REG_2_),
    .B(_342_),
    .Y(_349_)
  );
  OAI21 _765_ (
    .A0(_219_),
    .A1(_342_),
    .B0(_349_),
    .Y(U742)
  );
  NAND2 _766_ (
    .A(MAX_REG_1_),
    .B(_342_),
    .Y(_350_)
  );
  OAI21 _767_ (
    .A0(_222_),
    .A1(_342_),
    .B0(_350_),
    .Y(U743)
  );
  NAND2 _768_ (
    .A(MAX_REG_0_),
    .B(_342_),
    .Y(_351_)
  );
  OAI21 _769_ (
    .A0(_224_),
    .A1(_342_),
    .B0(_351_),
    .Y(U744)
  );
  INV _770_ (
    .A(_018_),
    .Y(DISPMAX1_0_)
  );
  INV _771_ (
    .A(_018_),
    .Y(DISPMAX2_3_)
  );
  \$_FF_  _772_ (
    .D(U680),
    .Q(NUM_REG_4_)
  );
  \$_FF_  _773_ (
    .D(U679),
    .Q(NUM_REG_3_)
  );
  \$_FF_  _774_ (
    .D(U678),
    .Q(NUM_REG_2_)
  );
  \$_FF_  _775_ (
    .D(U677),
    .Q(NUM_REG_1_)
  );
  \$_FF_  _776_ (
    .D(U676),
    .Q(NUM_REG_0_)
  );
  \$_FF_  _777_ (
    .D(U675),
    .Q(MAR_REG_4_)
  );
  \$_FF_  _778_ (
    .D(U674),
    .Q(MAR_REG_3_)
  );
  \$_FF_  _779_ (
    .D(U673),
    .Q(MAR_REG_2_)
  );
  \$_FF_  _780_ (
    .D(U672),
    .Q(MAR_REG_1_)
  );
  \$_FF_  _781_ (
    .D(U671),
    .Q(MAR_REG_0_)
  );
  \$_FF_  _782_ (
    .D(U727),
    .Q(TEMP_REG_8_)
  );
  \$_FF_  _783_ (
    .D(U728),
    .Q(TEMP_REG_7_)
  );
  \$_FF_  _784_ (
    .D(U729),
    .Q(TEMP_REG_6_)
  );
  \$_FF_  _785_ (
    .D(U730),
    .Q(TEMP_REG_5_)
  );
  \$_FF_  _786_ (
    .D(U731),
    .Q(TEMP_REG_4_)
  );
  \$_FF_  _787_ (
    .D(U732),
    .Q(TEMP_REG_3_)
  );
  \$_FF_  _788_ (
    .D(U733),
    .Q(TEMP_REG_2_)
  );
  \$_FF_  _789_ (
    .D(U734),
    .Q(TEMP_REG_1_)
  );
  \$_FF_  _790_ (
    .D(U735),
    .Q(TEMP_REG_0_)
  );
  \$_FF_  _791_ (
    .D(U736),
    .Q(MAX_REG_8_)
  );
  \$_FF_  _792_ (
    .D(U737),
    .Q(MAX_REG_7_)
  );
  \$_FF_  _793_ (
    .D(U738),
    .Q(MAX_REG_6_)
  );
  \$_FF_  _794_ (
    .D(U739),
    .Q(MAX_REG_5_)
  );
  \$_FF_  _795_ (
    .D(U740),
    .Q(MAX_REG_4_)
  );
  \$_FF_  _796_ (
    .D(U741),
    .Q(MAX_REG_3_)
  );
  \$_FF_  _797_ (
    .D(U742),
    .Q(MAX_REG_2_)
  );
  \$_FF_  _798_ (
    .D(U743),
    .Q(MAX_REG_1_)
  );
  \$_FF_  _799_ (
    .D(U744),
    .Q(MAX_REG_0_)
  );
  \$_FF_  _800_ (
    .D(U670),
    .Q(EN_DISP_REG)
  );
  \$_FF_  _801_ (
    .D(U669),
    .Q(RES_DISP_REG)
  );
  \$_FF_  _802_ (
    .D(U668),
    .Q(FLAG_REG)
  );
  \$_FF_  _803_ (
    .D(U645),
    .Q(STATO_REG_0_)
  );
  \$_FF_  _804_ (
    .D(U644),
    .Q(STATO_REG_1_)
  );
  \$_FF_  _805_ (
    .D(U643),
    .Q(STATO_REG_2_)
  );
  assign U589 = DISPMAX1_3_;
  assign U590 = DISPMAX1_0_;
  assign U591 = DISPNUM1_0_;
  assign U646 = SIGN;
  assign U647 = DISPMAX3_6_;
  assign U648 = DISPMAX3_5_;
  assign U649 = DISPMAX3_4_;
  assign U650 = DISPMAX3_3_;
  assign U651 = DISPMAX3_2_;
  assign U652 = DISPMAX3_1_;
  assign U653 = DISPMAX3_0_;
  assign U654 = DISPNUM2_6_;
  assign U655 = DISPNUM2_5_;
  assign U656 = DISPNUM2_4_;
  assign U657 = DISPNUM2_3_;
  assign U658 = DISPNUM2_2_;
  assign U659 = DISPNUM2_1_;
  assign U660 = DISPNUM2_0_;
  assign U661 = DISPMAX2_6_;
  assign U662 = DISPMAX2_5_;
  assign U663 = DISPMAX2_4_;
  assign U664 = DISPMAX2_3_;
  assign U665 = DISPMAX2_2_;
  assign U666 = DISPMAX2_1_;
  assign U667 = DISPMAX2_0_;
  assign U792 = DISPMAX1_6_;
  assign DISPNUM1_1_ = DISPNUM1_0_;
  assign DISPNUM1_2_ = DISPNUM1_0_;
  assign DISPNUM1_3_ = DISPMAX1_3_;
  assign DISPNUM1_4_ = DISPMAX1_3_;
  assign DISPNUM1_5_ = DISPNUM1_0_;
  assign DISPNUM1_6_ = DISPMAX1_6_;
  assign DISPMAX1_1_ = DISPMAX1_0_;
  assign DISPMAX1_2_ = DISPMAX1_0_;
  assign DISPMAX1_4_ = DISPMAX1_3_;
  assign DISPMAX1_5_ = DISPMAX1_0_;
endmodule
