/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b07.blif (START, PUNTI_RETTA_7_, PUNTI_RETTA_6_, PUNTI_RETTA_5_, PUNTI_RETTA_4_, PUNTI_RETTA_3_, PUNTI_RETTA_2_, PUNTI_RETTA_1_, PUNTI_RETTA_0_);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  (* init = 1'h0 *)
  wire CONT_REG_0_;
  (* init = 1'h0 *)
  wire CONT_REG_1_;
  (* init = 1'h0 *)
  wire CONT_REG_2_;
  (* init = 1'h0 *)
  wire CONT_REG_3_;
  (* init = 1'h0 *)
  wire CONT_REG_4_;
  (* init = 1'h0 *)
  wire CONT_REG_5_;
  (* init = 1'h0 *)
  wire CONT_REG_6_;
  (* init = 1'h0 *)
  wire CONT_REG_7_;
  (* init = 1'h0 *)
  wire MAR_REG_0_;
  (* init = 1'h0 *)
  wire MAR_REG_1_;
  (* init = 1'h0 *)
  wire MAR_REG_2_;
  (* init = 1'h0 *)
  wire MAR_REG_3_;
  (* init = 1'h0 *)
  wire MAR_REG_4_;
  (* init = 1'h0 *)
  wire MAR_REG_5_;
  (* init = 1'h0 *)
  wire MAR_REG_6_;
  (* init = 1'h0 *)
  wire MAR_REG_7_;
  output PUNTI_RETTA_0_;
  wire PUNTI_RETTA_0_;
  output PUNTI_RETTA_1_;
  wire PUNTI_RETTA_1_;
  output PUNTI_RETTA_2_;
  wire PUNTI_RETTA_2_;
  output PUNTI_RETTA_3_;
  wire PUNTI_RETTA_3_;
  output PUNTI_RETTA_4_;
  wire PUNTI_RETTA_4_;
  output PUNTI_RETTA_5_;
  wire PUNTI_RETTA_5_;
  output PUNTI_RETTA_6_;
  wire PUNTI_RETTA_6_;
  output PUNTI_RETTA_7_;
  wire PUNTI_RETTA_7_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_0_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_1_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_2_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_3_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_4_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_5_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_6_;
  (* init = 1'h0 *)
  wire PUNTI_RETTA_REG_7_;
  input START;
  wire START;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  (* init = 1'h0 *)
  wire STATO_REG_2_;
  (* init = 1'h0 *)
  wire T_REG_0_;
  (* init = 1'h0 *)
  wire T_REG_1_;
  (* init = 1'h0 *)
  wire T_REG_2_;
  (* init = 1'h0 *)
  wire T_REG_3_;
  (* init = 1'h0 *)
  wire T_REG_4_;
  (* init = 1'h0 *)
  wire T_REG_5_;
  (* init = 1'h0 *)
  wire T_REG_6_;
  wire U324;
  wire U325;
  wire U326;
  wire U327;
  wire U328;
  wire U329;
  wire U330;
  wire U331;
  wire U332;
  wire U333;
  wire U334;
  wire U335;
  wire U336;
  wire U337;
  wire U338;
  wire U339;
  wire U340;
  wire U341;
  wire U342;
  wire U343;
  wire U344;
  wire U345;
  wire U346;
  wire U347;
  wire U348;
  wire U349;
  wire U350;
  wire U351;
  wire U352;
  wire U353;
  wire U354;
  wire U355;
  wire U356;
  wire U357;
  wire U358;
  wire U388;
  wire U389;
  wire U390;
  wire U391;
  wire U394;
  wire U395;
  wire U396;
  wire U397;
  wire U398;
  wire U399;
  wire U400;
  wire U401;
  wire U402;
  wire U403;
  (* init = 1'h0 *)
  wire X_REG_0_;
  (* init = 1'h0 *)
  wire X_REG_1_;
  (* init = 1'h0 *)
  wire X_REG_2_;
  (* init = 1'h0 *)
  wire X_REG_3_;
  (* init = 1'h0 *)
  wire X_REG_4_;
  (* init = 1'h0 *)
  wire X_REG_5_;
  (* init = 1'h0 *)
  wire X_REG_6_;
  (* init = 1'h0 *)
  wire X_REG_7_;
  (* init = 1'h0 *)
  wire Y_REG_0_;
  (* init = 1'h0 *)
  wire Y_REG_1_;
  (* init = 1'h0 *)
  wire Y_REG_2_;
  (* init = 1'h0 *)
  wire Y_REG_3_;
  (* init = 1'h0 *)
  wire Y_REG_4_;
  (* init = 1'h0 *)
  wire Y_REG_5_;
  (* init = 1'h0 *)
  wire Y_REG_6_;
  INV _214_ (
    .A(MAR_REG_0_),
    .Y(_000_)
  );
  INV _215_ (
    .A(MAR_REG_2_),
    .Y(_001_)
  );
  INV _216_ (
    .A(STATO_REG_1_),
    .Y(_002_)
  );
  INV _217_ (
    .A(STATO_REG_2_),
    .Y(_003_)
  );
  INV _218_ (
    .A(START),
    .Y(_004_)
  );
  INV _219_ (
    .A(X_REG_0_),
    .Y(_005_)
  );
  INV _220_ (
    .A(STATO_REG_0_),
    .Y(_006_)
  );
  INV _221_ (
    .A(MAR_REG_6_),
    .Y(_007_)
  );
  INV _222_ (
    .A(MAR_REG_7_),
    .Y(_008_)
  );
  INV _223_ (
    .A(MAR_REG_5_),
    .Y(_009_)
  );
  INV _224_ (
    .A(MAR_REG_3_),
    .Y(_010_)
  );
  INV _225_ (
    .A(MAR_REG_4_),
    .Y(_011_)
  );
  INV _226_ (
    .A(CONT_REG_7_),
    .Y(_012_)
  );
  INV _227_ (
    .A(CONT_REG_6_),
    .Y(_013_)
  );
  INV _228_ (
    .A(CONT_REG_4_),
    .Y(_014_)
  );
  INV _229_ (
    .A(CONT_REG_3_),
    .Y(_015_)
  );
  INV _230_ (
    .A(CONT_REG_2_),
    .Y(_016_)
  );
  INV _231_ (
    .A(CONT_REG_0_),
    .Y(_017_)
  );
  INV _232_ (
    .A(CONT_REG_5_),
    .Y(_018_)
  );
  INV _233_ (
    .A(CONT_REG_1_),
    .Y(_019_)
  );
  INV _234_ (
    .A(X_REG_1_),
    .Y(_020_)
  );
  INV _235_ (
    .A(T_REG_0_),
    .Y(_021_)
  );
  INV _236_ (
    .A(T_REG_1_),
    .Y(_022_)
  );
  NOR2 _237_ (
    .A(_002_),
    .B(STATO_REG_2_),
    .Y(_023_)
  );
  NOR2 _238_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_2_),
    .Y(_024_)
  );
  NAND2 _239_ (
    .A(MAR_REG_0_),
    .B(MAR_REG_1_),
    .Y(_025_)
  );
  AOI21 _240_ (
    .A0(MAR_REG_0_),
    .A1(MAR_REG_1_),
    .B0(MAR_REG_2_),
    .Y(_026_)
  );
  NOR2 _241_ (
    .A(_010_),
    .B(_026_),
    .Y(_027_)
  );
  NOR3 _242_ (
    .A(MAR_REG_6_),
    .B(MAR_REG_7_),
    .C(MAR_REG_5_),
    .Y(_028_)
  );
  AOI21 _243_ (
    .A0(_011_),
    .A1(_027_),
    .B0(_028_),
    .Y(_029_)
  );
  INV _244_ (
    .A(_029_),
    .Y(_030_)
  );
  NOR2 _245_ (
    .A(_002_),
    .B(_003_),
    .Y(_031_)
  );
  NAND2 _246_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_2_),
    .Y(_032_)
  );
  NOR2 _247_ (
    .A(_029_),
    .B(_032_),
    .Y(_033_)
  );
  OAI21 _248_ (
    .A0(_024_),
    .A1(_033_),
    .B0(_004_),
    .Y(_034_)
  );
  INV _249_ (
    .A(_034_),
    .Y(_035_)
  );
  OAI21 _250_ (
    .A0(STATO_REG_0_),
    .A1(_033_),
    .B0(_035_),
    .Y(_036_)
  );
  AOI21 _251_ (
    .A0(STATO_REG_2_),
    .A1(_004_),
    .B0(_033_),
    .Y(_037_)
  );
  NOR2 _252_ (
    .A(X_REG_4_),
    .B(X_REG_7_),
    .Y(_038_)
  );
  NOR2 _253_ (
    .A(X_REG_5_),
    .B(_020_),
    .Y(_039_)
  );
  NOR2 _254_ (
    .A(X_REG_0_),
    .B(X_REG_6_),
    .Y(_040_)
  );
  AOI21 _255_ (
    .A0(_038_),
    .A1(_039_),
    .B0(_040_),
    .Y(_041_)
  );
  NOR3 _256_ (
    .A(X_REG_2_),
    .B(X_REG_3_),
    .C(_041_),
    .Y(_042_)
  );
  INV _257_ (
    .A(_042_),
    .Y(_043_)
  );
  NOR2 _258_ (
    .A(_037_),
    .B(_043_),
    .Y(_044_)
  );
  INV _259_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR2 _260_ (
    .A(_012_),
    .B(_032_),
    .Y(_046_)
  );
  AOI21 _261_ (
    .A0(STATO_REG_1_),
    .A1(STATO_REG_2_),
    .B0(_006_),
    .Y(_047_)
  );
  AOI22 _262_ (
    .A0(CONT_REG_6_),
    .A1(_031_),
    .B0(_047_),
    .B1(X_REG_6_),
    .Y(_048_)
  );
  INV _263_ (
    .A(_048_),
    .Y(_049_)
  );
  NOR2 _264_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_0_),
    .Y(_050_)
  );
  NAND2 _265_ (
    .A(_003_),
    .B(X_REG_6_),
    .Y(_051_)
  );
  NOR2 _266_ (
    .A(_003_),
    .B(_006_),
    .Y(_052_)
  );
  AOI22 _267_ (
    .A0(T_REG_6_),
    .A1(_050_),
    .B0(_052_),
    .B1(Y_REG_6_),
    .Y(_053_)
  );
  NAND2 _268_ (
    .A(_051_),
    .B(_053_),
    .Y(_054_)
  );
  INV _269_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR2 _270_ (
    .A(_048_),
    .B(_055_),
    .Y(_056_)
  );
  NOR2 _271_ (
    .A(_049_),
    .B(_054_),
    .Y(_057_)
  );
  NAND2 _272_ (
    .A(_003_),
    .B(X_REG_5_),
    .Y(_058_)
  );
  AOI22 _273_ (
    .A0(T_REG_5_),
    .A1(_050_),
    .B0(_052_),
    .B1(Y_REG_5_),
    .Y(_059_)
  );
  NAND2 _274_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  INV _275_ (
    .A(_060_),
    .Y(_061_)
  );
  NAND2 _276_ (
    .A(X_REG_5_),
    .B(_047_),
    .Y(_062_)
  );
  OAI21 _277_ (
    .A0(_018_),
    .A1(_032_),
    .B0(_062_),
    .Y(_063_)
  );
  INV _278_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR2 _279_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NOR2 _280_ (
    .A(_060_),
    .B(_063_),
    .Y(_066_)
  );
  NAND2 _281_ (
    .A(T_REG_4_),
    .B(_050_),
    .Y(_067_)
  );
  AOI22 _282_ (
    .A0(_003_),
    .A1(X_REG_4_),
    .B0(Y_REG_4_),
    .B1(_052_),
    .Y(_068_)
  );
  NAND2 _283_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NAND2 _284_ (
    .A(CONT_REG_4_),
    .B(_031_),
    .Y(_070_)
  );
  NAND2 _285_ (
    .A(X_REG_4_),
    .B(_047_),
    .Y(_071_)
  );
  NAND2 _286_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  AOI22 _287_ (
    .A0(_067_),
    .A1(_068_),
    .B0(_070_),
    .B1(_071_),
    .Y(_073_)
  );
  NOR2 _288_ (
    .A(_069_),
    .B(_072_),
    .Y(_074_)
  );
  NAND2 _289_ (
    .A(_003_),
    .B(X_REG_3_),
    .Y(_075_)
  );
  AOI22 _290_ (
    .A0(T_REG_3_),
    .A1(_050_),
    .B0(_052_),
    .B1(Y_REG_3_),
    .Y(_076_)
  );
  NAND2 _291_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND2 _292_ (
    .A(X_REG_3_),
    .B(_047_),
    .Y(_078_)
  );
  OAI21 _293_ (
    .A0(_015_),
    .A1(_032_),
    .B0(_078_),
    .Y(_079_)
  );
  NAND2 _294_ (
    .A(_077_),
    .B(_079_),
    .Y(_080_)
  );
  INV _295_ (
    .A(_080_),
    .Y(_081_)
  );
  NOR2 _296_ (
    .A(_077_),
    .B(_079_),
    .Y(_082_)
  );
  NAND2 _297_ (
    .A(_003_),
    .B(X_REG_2_),
    .Y(_083_)
  );
  AOI22 _298_ (
    .A0(T_REG_2_),
    .A1(_050_),
    .B0(_052_),
    .B1(Y_REG_2_),
    .Y(_084_)
  );
  NAND2 _299_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NAND2 _300_ (
    .A(X_REG_2_),
    .B(_047_),
    .Y(_086_)
  );
  AOI22 _301_ (
    .A0(CONT_REG_2_),
    .A1(_031_),
    .B0(_047_),
    .B1(X_REG_2_),
    .Y(_087_)
  );
  OAI21 _302_ (
    .A0(_016_),
    .A1(_032_),
    .B0(_086_),
    .Y(_088_)
  );
  NAND2 _303_ (
    .A(_085_),
    .B(_088_),
    .Y(_089_)
  );
  NOR2 _304_ (
    .A(_085_),
    .B(_088_),
    .Y(_090_)
  );
  NOR3 _305_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_0_),
    .C(_022_),
    .Y(_091_)
  );
  AOI21 _306_ (
    .A0(STATO_REG_2_),
    .A1(STATO_REG_0_),
    .B0(Y_REG_1_),
    .Y(_092_)
  );
  OAI21 _307_ (
    .A0(STATO_REG_2_),
    .A1(_020_),
    .B0(_092_),
    .Y(_093_)
  );
  AOI22 _308_ (
    .A0(T_REG_1_),
    .A1(_050_),
    .B0(_052_),
    .B1(Y_REG_1_),
    .Y(_094_)
  );
  NOR2 _309_ (
    .A(_091_),
    .B(_093_),
    .Y(_095_)
  );
  OAI21 _310_ (
    .A0(STATO_REG_2_),
    .A1(_020_),
    .B0(_094_),
    .Y(_096_)
  );
  AOI22 _311_ (
    .A0(CONT_REG_1_),
    .A1(_031_),
    .B0(_047_),
    .B1(X_REG_1_),
    .Y(_097_)
  );
  INV _312_ (
    .A(_097_),
    .Y(_098_)
  );
  NAND2 _313_ (
    .A(_096_),
    .B(_098_),
    .Y(_099_)
  );
  NAND2 _314_ (
    .A(_095_),
    .B(_097_),
    .Y(_100_)
  );
  NAND2 _315_ (
    .A(X_REG_0_),
    .B(_047_),
    .Y(_101_)
  );
  INV _316_ (
    .A(_101_),
    .Y(_102_)
  );
  AOI22 _317_ (
    .A0(CONT_REG_0_),
    .A1(_031_),
    .B0(_047_),
    .B1(X_REG_0_),
    .Y(_103_)
  );
  NOR3 _318_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_0_),
    .C(_021_),
    .Y(_104_)
  );
  AOI21 _319_ (
    .A0(STATO_REG_2_),
    .A1(STATO_REG_0_),
    .B0(Y_REG_0_),
    .Y(_105_)
  );
  OAI21 _320_ (
    .A0(STATO_REG_2_),
    .A1(_005_),
    .B0(_105_),
    .Y(_106_)
  );
  NOR2 _321_ (
    .A(_104_),
    .B(_106_),
    .Y(_107_)
  );
  NOR3 _322_ (
    .A(_031_),
    .B(_104_),
    .C(_106_),
    .Y(_108_)
  );
  NAND2 _323_ (
    .A(_032_),
    .B(_107_),
    .Y(_109_)
  );
  NOR2 _324_ (
    .A(_103_),
    .B(_108_),
    .Y(_110_)
  );
  NAND2 _325_ (
    .A(_100_),
    .B(_110_),
    .Y(_111_)
  );
  OAI22 _326_ (
    .A0(_095_),
    .A1(_097_),
    .B0(_103_),
    .B1(_108_),
    .Y(_112_)
  );
  NAND2 _327_ (
    .A(_099_),
    .B(_111_),
    .Y(_113_)
  );
  AOI22 _328_ (
    .A0(_085_),
    .A1(_088_),
    .B0(_100_),
    .B1(_112_),
    .Y(_114_)
  );
  AOI21 _329_ (
    .A0(_089_),
    .A1(_099_),
    .B0(_111_),
    .Y(_115_)
  );
  OAI21 _330_ (
    .A0(_085_),
    .A1(_088_),
    .B0(_115_),
    .Y(_116_)
  );
  NOR3 _331_ (
    .A(_082_),
    .B(_090_),
    .C(_114_),
    .Y(_117_)
  );
  NOR2 _332_ (
    .A(_081_),
    .B(_117_),
    .Y(_118_)
  );
  NOR3 _333_ (
    .A(_073_),
    .B(_081_),
    .C(_117_),
    .Y(_119_)
  );
  NOR2 _334_ (
    .A(_074_),
    .B(_119_),
    .Y(_120_)
  );
  NOR3 _335_ (
    .A(_066_),
    .B(_074_),
    .C(_119_),
    .Y(_121_)
  );
  NOR2 _336_ (
    .A(_065_),
    .B(_121_),
    .Y(_122_)
  );
  NOR3 _337_ (
    .A(_056_),
    .B(_065_),
    .C(_121_),
    .Y(_123_)
  );
  NOR2 _338_ (
    .A(_057_),
    .B(_123_),
    .Y(_124_)
  );
  XNOR2 _339_ (
    .A(_046_),
    .B(_124_),
    .Y(_125_)
  );
  NOR2 _340_ (
    .A(_037_),
    .B(_042_),
    .Y(_126_)
  );
  AOI22 _341_ (
    .A0(PUNTI_RETTA_REG_7_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_7_),
    .Y(_127_)
  );
  OAI21 _342_ (
    .A0(_045_),
    .A1(_125_),
    .B0(_127_),
    .Y(U358)
  );
  NOR2 _343_ (
    .A(_030_),
    .B(_032_),
    .Y(_128_)
  );
  NAND2 _344_ (
    .A(_029_),
    .B(_031_),
    .Y(_129_)
  );
  NAND2 _345_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_0_),
    .Y(_130_)
  );
  AOI21 _346_ (
    .A0(_003_),
    .A1(START),
    .B0(STATO_REG_0_),
    .Y(_131_)
  );
  NAND2 _347_ (
    .A(_130_),
    .B(_131_),
    .Y(_132_)
  );
  NOR2 _348_ (
    .A(_128_),
    .B(_132_),
    .Y(_133_)
  );
  AOI21 _349_ (
    .A0(_129_),
    .A1(_130_),
    .B0(_131_),
    .Y(_134_)
  );
  OAI21 _350_ (
    .A0(STATO_REG_1_),
    .A1(STATO_REG_2_),
    .B0(_134_),
    .Y(_135_)
  );
  XNOR2 _351_ (
    .A(_010_),
    .B(_026_),
    .Y(_136_)
  );
  OAI22 _352_ (
    .A0(_010_),
    .A1(_134_),
    .B0(_135_),
    .B1(_136_),
    .Y(U388)
  );
  XNOR2 _353_ (
    .A(_001_),
    .B(_025_),
    .Y(_137_)
  );
  OAI22 _354_ (
    .A0(_001_),
    .A1(_134_),
    .B0(_135_),
    .B1(_137_),
    .Y(U389)
  );
  NOR2 _355_ (
    .A(_000_),
    .B(MAR_REG_1_),
    .Y(_138_)
  );
  XNOR2 _356_ (
    .A(MAR_REG_0_),
    .B(MAR_REG_1_),
    .Y(_139_)
  );
  NAND2 _357_ (
    .A(MAR_REG_1_),
    .B(_133_),
    .Y(_140_)
  );
  OAI21 _358_ (
    .A0(_135_),
    .A1(_139_),
    .B0(_140_),
    .Y(U390)
  );
  NAND2 _359_ (
    .A(MAR_REG_0_),
    .B(_133_),
    .Y(_141_)
  );
  OAI21 _360_ (
    .A0(MAR_REG_0_),
    .A1(_135_),
    .B0(_141_),
    .Y(U391)
  );
  NAND2 _361_ (
    .A(STATO_REG_2_),
    .B(_050_),
    .Y(_142_)
  );
  NAND2 _362_ (
    .A(Y_REG_1_),
    .B(_142_),
    .Y(_143_)
  );
  AOI21 _363_ (
    .A0(MAR_REG_1_),
    .A1(_001_),
    .B0(MAR_REG_3_),
    .Y(_144_)
  );
  NOR2 _364_ (
    .A(_027_),
    .B(_138_),
    .Y(_145_)
  );
  OAI21 _365_ (
    .A0(MAR_REG_0_),
    .A1(_144_),
    .B0(_145_),
    .Y(_146_)
  );
  AOI21 _366_ (
    .A0(STATO_REG_2_),
    .A1(_050_),
    .B0(_146_),
    .Y(_147_)
  );
  NAND2 _367_ (
    .A(_143_),
    .B(_147_),
    .Y(U394)
  );
  XNOR2 _368_ (
    .A(_077_),
    .B(_079_),
    .Y(_148_)
  );
  XNOR2 _369_ (
    .A(_116_),
    .B(_148_),
    .Y(_149_)
  );
  NAND2 _370_ (
    .A(T_REG_3_),
    .B(_130_),
    .Y(_150_)
  );
  OAI21 _371_ (
    .A0(_130_),
    .A1(_149_),
    .B0(_150_),
    .Y(U395)
  );
  NOR2 _372_ (
    .A(_065_),
    .B(_066_),
    .Y(_151_)
  );
  XNOR2 _373_ (
    .A(_120_),
    .B(_151_),
    .Y(_152_)
  );
  NAND2 _374_ (
    .A(T_REG_5_),
    .B(_130_),
    .Y(_153_)
  );
  OAI21 _375_ (
    .A0(_130_),
    .A1(_152_),
    .B0(_153_),
    .Y(U396)
  );
  XNOR2 _376_ (
    .A(_096_),
    .B(_097_),
    .Y(_154_)
  );
  XNOR2 _377_ (
    .A(_110_),
    .B(_154_),
    .Y(_155_)
  );
  NAND2 _378_ (
    .A(T_REG_1_),
    .B(_130_),
    .Y(_156_)
  );
  OAI21 _379_ (
    .A0(_130_),
    .A1(_155_),
    .B0(_156_),
    .Y(U397)
  );
  NAND2 _380_ (
    .A(T_REG_0_),
    .B(_130_),
    .Y(_157_)
  );
  NOR2 _381_ (
    .A(_102_),
    .B(_109_),
    .Y(_158_)
  );
  NAND2 _382_ (
    .A(_101_),
    .B(_108_),
    .Y(_159_)
  );
  NOR2 _383_ (
    .A(_110_),
    .B(_158_),
    .Y(_160_)
  );
  OAI21 _384_ (
    .A0(_103_),
    .A1(_108_),
    .B0(_159_),
    .Y(_161_)
  );
  OAI21 _385_ (
    .A0(_130_),
    .A1(_161_),
    .B0(_157_),
    .Y(U398)
  );
  XNOR2 _386_ (
    .A(_069_),
    .B(_072_),
    .Y(_162_)
  );
  XNOR2 _387_ (
    .A(_118_),
    .B(_162_),
    .Y(_163_)
  );
  NAND2 _388_ (
    .A(T_REG_4_),
    .B(_130_),
    .Y(_164_)
  );
  OAI21 _389_ (
    .A0(_130_),
    .A1(_163_),
    .B0(_164_),
    .Y(U399)
  );
  XNOR2 _390_ (
    .A(_049_),
    .B(_054_),
    .Y(_165_)
  );
  XNOR2 _391_ (
    .A(_122_),
    .B(_165_),
    .Y(_166_)
  );
  NAND2 _392_ (
    .A(T_REG_6_),
    .B(_130_),
    .Y(_167_)
  );
  OAI21 _393_ (
    .A0(_130_),
    .A1(_166_),
    .B0(_167_),
    .Y(U400)
  );
  NAND2 _394_ (
    .A(T_REG_2_),
    .B(_130_),
    .Y(_168_)
  );
  XNOR2 _395_ (
    .A(_085_),
    .B(_087_),
    .Y(_169_)
  );
  XNOR2 _396_ (
    .A(_113_),
    .B(_169_),
    .Y(_170_)
  );
  OAI21 _397_ (
    .A0(_130_),
    .A1(_170_),
    .B0(_168_),
    .Y(U401)
  );
  NAND2 _398_ (
    .A(Y_REG_0_),
    .B(_142_),
    .Y(_171_)
  );
  NOR3 _399_ (
    .A(MAR_REG_1_),
    .B(MAR_REG_2_),
    .C(MAR_REG_3_),
    .Y(_172_)
  );
  NAND2 _400_ (
    .A(MAR_REG_0_),
    .B(_172_),
    .Y(_173_)
  );
  OAI21 _401_ (
    .A0(MAR_REG_0_),
    .A1(_144_),
    .B0(_173_),
    .Y(_174_)
  );
  NAND2 _402_ (
    .A(_144_),
    .B(_173_),
    .Y(_175_)
  );
  INV _403_ (
    .A(_175_),
    .Y(_176_)
  );
  NOR2 _404_ (
    .A(_172_),
    .B(_175_),
    .Y(_177_)
  );
  OAI21 _405_ (
    .A0(_142_),
    .A1(_177_),
    .B0(_171_),
    .Y(U402)
  );
  NAND2 _406_ (
    .A(Y_REG_2_),
    .B(_142_),
    .Y(_178_)
  );
  OAI21 _407_ (
    .A0(_142_),
    .A1(_176_),
    .B0(_178_),
    .Y(U403)
  );
  OAI21 _408_ (
    .A0(_004_),
    .A1(_029_),
    .B0(STATO_REG_1_),
    .Y(_179_)
  );
  NAND2 _409_ (
    .A(STATO_REG_2_),
    .B(_179_),
    .Y(_180_)
  );
  NAND2 _410_ (
    .A(_130_),
    .B(_180_),
    .Y(U324)
  );
  NOR3 _411_ (
    .A(_003_),
    .B(START),
    .C(_029_),
    .Y(_181_)
  );
  NOR3 _412_ (
    .A(_002_),
    .B(STATO_REG_0_),
    .C(_181_),
    .Y(_182_)
  );
  AOI21 _413_ (
    .A0(_002_),
    .A1(START),
    .B0(STATO_REG_0_),
    .Y(_183_)
  );
  NOR2 _414_ (
    .A(_052_),
    .B(_182_),
    .Y(_184_)
  );
  NAND2 _415_ (
    .A(_183_),
    .B(_184_),
    .Y(U325)
  );
  OAI21 _416_ (
    .A0(STATO_REG_0_),
    .A1(_031_),
    .B0(_034_),
    .Y(U326)
  );
  NAND2 _417_ (
    .A(Y_REG_6_),
    .B(_142_),
    .Y(_185_)
  );
  AOI21 _418_ (
    .A0(STATO_REG_2_),
    .A1(_050_),
    .B0(_174_),
    .Y(_186_)
  );
  NAND2 _419_ (
    .A(_185_),
    .B(_186_),
    .Y(U327)
  );
  NAND2 _420_ (
    .A(Y_REG_4_),
    .B(_142_),
    .Y(_187_)
  );
  NAND2 _421_ (
    .A(_186_),
    .B(_187_),
    .Y(U328)
  );
  NAND2 _422_ (
    .A(Y_REG_5_),
    .B(_142_),
    .Y(_188_)
  );
  NAND2 _423_ (
    .A(_186_),
    .B(_188_),
    .Y(U329)
  );
  NAND2 _424_ (
    .A(Y_REG_3_),
    .B(_142_),
    .Y(_189_)
  );
  NAND2 _425_ (
    .A(_186_),
    .B(_189_),
    .Y(U330)
  );
  NOR2 _426_ (
    .A(STATO_REG_1_),
    .B(_003_),
    .Y(_190_)
  );
  INV _427_ (
    .A(_190_),
    .Y(_191_)
  );
  NAND2 _428_ (
    .A(_160_),
    .B(_190_),
    .Y(_192_)
  );
  NOR3 _429_ (
    .A(_002_),
    .B(STATO_REG_2_),
    .C(STATO_REG_0_),
    .Y(_193_)
  );
  NOR2 _430_ (
    .A(_190_),
    .B(_193_),
    .Y(_194_)
  );
  NAND2 _431_ (
    .A(X_REG_0_),
    .B(_194_),
    .Y(_195_)
  );
  OAI21 _432_ (
    .A0(_172_),
    .A1(_175_),
    .B0(_193_),
    .Y(_196_)
  );
  AOI21 _433_ (
    .A0(_192_),
    .A1(_195_),
    .B0(_196_),
    .Y(U331)
  );
  AOI22 _434_ (
    .A0(_146_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_1_),
    .Y(_197_)
  );
  OAI21 _435_ (
    .A0(_155_),
    .A1(_191_),
    .B0(_197_),
    .Y(U332)
  );
  AOI22 _436_ (
    .A0(_175_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_2_),
    .Y(_198_)
  );
  OAI21 _437_ (
    .A0(_170_),
    .A1(_191_),
    .B0(_198_),
    .Y(U333)
  );
  AOI22 _438_ (
    .A0(_174_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_3_),
    .Y(_199_)
  );
  OAI21 _439_ (
    .A0(_149_),
    .A1(_191_),
    .B0(_199_),
    .Y(U334)
  );
  AOI22 _440_ (
    .A0(_174_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_4_),
    .Y(_200_)
  );
  OAI21 _441_ (
    .A0(_163_),
    .A1(_191_),
    .B0(_200_),
    .Y(U335)
  );
  AOI22 _442_ (
    .A0(_174_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_5_),
    .Y(_201_)
  );
  OAI21 _443_ (
    .A0(_152_),
    .A1(_191_),
    .B0(_201_),
    .Y(U336)
  );
  AOI22 _444_ (
    .A0(_174_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_6_),
    .Y(_202_)
  );
  OAI21 _445_ (
    .A0(_166_),
    .A1(_191_),
    .B0(_202_),
    .Y(U337)
  );
  AOI22 _446_ (
    .A0(_174_),
    .A1(_193_),
    .B0(_194_),
    .B1(X_REG_7_),
    .Y(_203_)
  );
  OAI21 _447_ (
    .A0(_125_),
    .A1(_191_),
    .B0(_203_),
    .Y(U338)
  );
  NOR2 _448_ (
    .A(_011_),
    .B(_134_),
    .Y(U339)
  );
  NOR2 _449_ (
    .A(_009_),
    .B(_134_),
    .Y(U340)
  );
  NOR2 _450_ (
    .A(_007_),
    .B(_134_),
    .Y(U341)
  );
  NOR2 _451_ (
    .A(_008_),
    .B(_134_),
    .Y(U342)
  );
  NAND2 _452_ (
    .A(_042_),
    .B(_128_),
    .Y(_204_)
  );
  OAI21 _453_ (
    .A0(_023_),
    .A1(_131_),
    .B0(_204_),
    .Y(_205_)
  );
  OAI22 _454_ (
    .A0(_161_),
    .A1(_204_),
    .B0(_205_),
    .B1(_017_),
    .Y(U343)
  );
  OAI22 _455_ (
    .A0(_155_),
    .A1(_204_),
    .B0(_205_),
    .B1(_019_),
    .Y(U344)
  );
  OAI22 _456_ (
    .A0(_170_),
    .A1(_204_),
    .B0(_205_),
    .B1(_016_),
    .Y(U345)
  );
  OAI22 _457_ (
    .A0(_149_),
    .A1(_204_),
    .B0(_205_),
    .B1(_015_),
    .Y(U346)
  );
  OAI22 _458_ (
    .A0(_163_),
    .A1(_204_),
    .B0(_205_),
    .B1(_014_),
    .Y(U347)
  );
  OAI22 _459_ (
    .A0(_152_),
    .A1(_204_),
    .B0(_205_),
    .B1(_018_),
    .Y(U348)
  );
  OAI22 _460_ (
    .A0(_166_),
    .A1(_204_),
    .B0(_205_),
    .B1(_013_),
    .Y(U349)
  );
  OAI22 _461_ (
    .A0(_125_),
    .A1(_204_),
    .B0(_205_),
    .B1(_012_),
    .Y(U350)
  );
  NAND2 _462_ (
    .A(CONT_REG_0_),
    .B(_126_),
    .Y(_206_)
  );
  AOI22 _463_ (
    .A0(PUNTI_RETTA_REG_0_),
    .A1(_036_),
    .B0(_044_),
    .B1(_160_),
    .Y(_207_)
  );
  NAND2 _464_ (
    .A(_206_),
    .B(_207_),
    .Y(U351)
  );
  AOI22 _465_ (
    .A0(PUNTI_RETTA_REG_1_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_1_),
    .Y(_208_)
  );
  OAI21 _466_ (
    .A0(_045_),
    .A1(_155_),
    .B0(_208_),
    .Y(U352)
  );
  AOI22 _467_ (
    .A0(PUNTI_RETTA_REG_2_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_2_),
    .Y(_209_)
  );
  OAI21 _468_ (
    .A0(_045_),
    .A1(_170_),
    .B0(_209_),
    .Y(U353)
  );
  AOI22 _469_ (
    .A0(PUNTI_RETTA_REG_3_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_3_),
    .Y(_210_)
  );
  OAI21 _470_ (
    .A0(_045_),
    .A1(_149_),
    .B0(_210_),
    .Y(U354)
  );
  AOI22 _471_ (
    .A0(PUNTI_RETTA_REG_4_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_4_),
    .Y(_211_)
  );
  OAI21 _472_ (
    .A0(_045_),
    .A1(_163_),
    .B0(_211_),
    .Y(U355)
  );
  AOI22 _473_ (
    .A0(PUNTI_RETTA_REG_5_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_5_),
    .Y(_212_)
  );
  OAI21 _474_ (
    .A0(_045_),
    .A1(_152_),
    .B0(_212_),
    .Y(U356)
  );
  AOI22 _475_ (
    .A0(PUNTI_RETTA_REG_6_),
    .A1(_036_),
    .B0(_126_),
    .B1(CONT_REG_6_),
    .Y(_213_)
  );
  OAI21 _476_ (
    .A0(_045_),
    .A1(_166_),
    .B0(_213_),
    .Y(U357)
  );
  \$_FF_  _477_ (
    .D(U358),
    .Q(PUNTI_RETTA_REG_7_)
  );
  \$_FF_  _478_ (
    .D(U357),
    .Q(PUNTI_RETTA_REG_6_)
  );
  \$_FF_  _479_ (
    .D(U356),
    .Q(PUNTI_RETTA_REG_5_)
  );
  \$_FF_  _480_ (
    .D(U355),
    .Q(PUNTI_RETTA_REG_4_)
  );
  \$_FF_  _481_ (
    .D(U354),
    .Q(PUNTI_RETTA_REG_3_)
  );
  \$_FF_  _482_ (
    .D(U353),
    .Q(PUNTI_RETTA_REG_2_)
  );
  \$_FF_  _483_ (
    .D(U352),
    .Q(PUNTI_RETTA_REG_1_)
  );
  \$_FF_  _484_ (
    .D(U351),
    .Q(PUNTI_RETTA_REG_0_)
  );
  \$_FF_  _485_ (
    .D(U350),
    .Q(CONT_REG_7_)
  );
  \$_FF_  _486_ (
    .D(U349),
    .Q(CONT_REG_6_)
  );
  \$_FF_  _487_ (
    .D(U348),
    .Q(CONT_REG_5_)
  );
  \$_FF_  _488_ (
    .D(U347),
    .Q(CONT_REG_4_)
  );
  \$_FF_  _489_ (
    .D(U346),
    .Q(CONT_REG_3_)
  );
  \$_FF_  _490_ (
    .D(U345),
    .Q(CONT_REG_2_)
  );
  \$_FF_  _491_ (
    .D(U344),
    .Q(CONT_REG_1_)
  );
  \$_FF_  _492_ (
    .D(U343),
    .Q(CONT_REG_0_)
  );
  \$_FF_  _493_ (
    .D(U342),
    .Q(MAR_REG_7_)
  );
  \$_FF_  _494_ (
    .D(U341),
    .Q(MAR_REG_6_)
  );
  \$_FF_  _495_ (
    .D(U340),
    .Q(MAR_REG_5_)
  );
  \$_FF_  _496_ (
    .D(U339),
    .Q(MAR_REG_4_)
  );
  \$_FF_  _497_ (
    .D(U388),
    .Q(MAR_REG_3_)
  );
  \$_FF_  _498_ (
    .D(U389),
    .Q(MAR_REG_2_)
  );
  \$_FF_  _499_ (
    .D(U390),
    .Q(MAR_REG_1_)
  );
  \$_FF_  _500_ (
    .D(U391),
    .Q(MAR_REG_0_)
  );
  \$_FF_  _501_ (
    .D(U338),
    .Q(X_REG_7_)
  );
  \$_FF_  _502_ (
    .D(U337),
    .Q(X_REG_6_)
  );
  \$_FF_  _503_ (
    .D(U336),
    .Q(X_REG_5_)
  );
  \$_FF_  _504_ (
    .D(U335),
    .Q(X_REG_4_)
  );
  \$_FF_  _505_ (
    .D(U334),
    .Q(X_REG_3_)
  );
  \$_FF_  _506_ (
    .D(U333),
    .Q(X_REG_2_)
  );
  \$_FF_  _507_ (
    .D(U332),
    .Q(X_REG_1_)
  );
  \$_FF_  _508_ (
    .D(U331),
    .Q(X_REG_0_)
  );
  \$_FF_  _509_ (
    .D(U330),
    .Q(Y_REG_3_)
  );
  \$_FF_  _510_ (
    .D(U394),
    .Q(Y_REG_1_)
  );
  \$_FF_  _511_ (
    .D(U329),
    .Q(Y_REG_5_)
  );
  \$_FF_  _512_ (
    .D(U395),
    .Q(T_REG_3_)
  );
  \$_FF_  _513_ (
    .D(U396),
    .Q(T_REG_5_)
  );
  \$_FF_  _514_ (
    .D(U397),
    .Q(T_REG_1_)
  );
  \$_FF_  _515_ (
    .D(U398),
    .Q(T_REG_0_)
  );
  \$_FF_  _516_ (
    .D(U399),
    .Q(T_REG_4_)
  );
  \$_FF_  _517_ (
    .D(U400),
    .Q(T_REG_6_)
  );
  \$_FF_  _518_ (
    .D(U401),
    .Q(T_REG_2_)
  );
  \$_FF_  _519_ (
    .D(U328),
    .Q(Y_REG_4_)
  );
  \$_FF_  _520_ (
    .D(U402),
    .Q(Y_REG_0_)
  );
  \$_FF_  _521_ (
    .D(U403),
    .Q(Y_REG_2_)
  );
  \$_FF_  _522_ (
    .D(U327),
    .Q(Y_REG_6_)
  );
  \$_FF_  _523_ (
    .D(U324),
    .Q(STATO_REG_2_)
  );
  \$_FF_  _524_ (
    .D(U325),
    .Q(STATO_REG_1_)
  );
  \$_FF_  _525_ (
    .D(U326),
    .Q(STATO_REG_0_)
  );
  assign PUNTI_RETTA_0_ = PUNTI_RETTA_REG_0_;
  assign PUNTI_RETTA_1_ = PUNTI_RETTA_REG_1_;
  assign PUNTI_RETTA_2_ = PUNTI_RETTA_REG_2_;
  assign PUNTI_RETTA_3_ = PUNTI_RETTA_REG_3_;
  assign PUNTI_RETTA_4_ = PUNTI_RETTA_REG_4_;
  assign PUNTI_RETTA_5_ = PUNTI_RETTA_REG_5_;
  assign PUNTI_RETTA_6_ = PUNTI_RETTA_REG_6_;
  assign PUNTI_RETTA_7_ = PUNTI_RETTA_REG_7_;
endmodule
