/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* src = "/content/ISCAS89/s1423.v:7.1-13.10" *)
module dff(CK, Q, D);
  (* src = "/content/ISCAS89/s1423.v:8.7-8.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s1423.v:8.10-8.11" *)
  input D;
  wire D;
  (* src = "/content/ISCAS89/s1423.v:9.8-9.9" *)
  output Q;
  wire Q;
  (* src = "/content/ISCAS89/s1423.v:11.1-12.10" *)
  DFFR _0_ (
    .C(CK),
    .D(D),
    .Q(Q),
    .R(1'h0)
  );
endmodule

(* top =  1  *)
(* src = "/content/ISCAS89/s1423.v:15.1-802.10" *)
module s1423(CK, G0, G1, G10, G11, G12, G13, G14, G15, G16, G2, G3, G4, G5, G6, G7, G701BF, G702, G726, G727, G729
, G8, G9);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  (* src = "/content/ISCAS89/s1423.v:17.7-17.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s1423.v:17.10-17.12" *)
  input G0;
  wire G0;
  (* src = "/content/ISCAS89/s1423.v:17.13-17.15" *)
  input G1;
  wire G1;
  (* src = "/content/ISCAS89/s1423.v:17.40-17.43" *)
  input G10;
  wire G10;
  (* src = "/content/ISCAS89/s1423.v:29.47-29.51" *)
  wire G108;
  (* src = "/content/ISCAS89/s1423.v:20.34-20.38" *)
  wire G109;
  (* src = "/content/ISCAS89/s1423.v:17.44-17.47" *)
  input G11;
  wire G11;
  (* src = "/content/ISCAS89/s1423.v:29.62-29.66" *)
  wire G112;
  (* src = "/content/ISCAS89/s1423.v:20.43-20.47" *)
  wire G113;
  (* src = "/content/ISCAS89/s1423.v:29.67-29.71" *)
  wire G117;
  (* src = "/content/ISCAS89/s1423.v:20.52-20.56" *)
  wire G118;
  (* src = "/content/ISCAS89/s1423.v:17.48-17.51" *)
  input G12;
  wire G12;
  (* src = "/content/ISCAS89/s1423.v:29.72-29.76" *)
  wire G124;
  (* src = "/content/ISCAS89/s1423.v:20.61-20.65" *)
  wire G125;
  (* src = "/content/ISCAS89/s1423.v:30.10-30.14" *)
  wire G128;
  (* src = "/content/ISCAS89/s1423.v:20.70-20.74" *)
  wire G129;
  (* src = "/content/ISCAS89/s1423.v:17.52-17.55" *)
  input G13;
  wire G13;
  (* src = "/content/ISCAS89/s1423.v:30.15-30.19" *)
  wire G139;
  (* src = "/content/ISCAS89/s1423.v:17.56-17.59" *)
  input G14;
  wire G14;
  (* src = "/content/ISCAS89/s1423.v:21.5-21.9" *)
  wire G140;
  (* src = "/content/ISCAS89/s1423.v:30.25-30.29" *)
  wire G143;
  (* src = "/content/ISCAS89/s1423.v:21.14-21.18" *)
  wire G144;
  (* src = "/content/ISCAS89/s1423.v:30.30-30.34" *)
  wire G148;
  (* src = "/content/ISCAS89/s1423.v:21.23-21.27" *)
  wire G149;
  (* src = "/content/ISCAS89/s1423.v:17.60-17.63" *)
  input G15;
  wire G15;
  (* src = "/content/ISCAS89/s1423.v:30.35-30.39" *)
  wire G153;
  (* src = "/content/ISCAS89/s1423.v:21.32-21.36" *)
  wire G154;
  (* src = "/content/ISCAS89/s1423.v:30.40-30.44" *)
  wire G158;
  (* src = "/content/ISCAS89/s1423.v:21.41-21.45" *)
  wire G159;
  (* src = "/content/ISCAS89/s1423.v:17.64-17.67" *)
  input G16;
  wire G16;
  (* src = "/content/ISCAS89/s1423.v:30.45-30.49" *)
  wire G165;
  (* src = "/content/ISCAS89/s1423.v:21.50-21.54" *)
  wire G166;
  (* src = "/content/ISCAS89/s1423.v:30.50-30.54" *)
  wire G174;
  (* src = "/content/ISCAS89/s1423.v:21.59-21.63" *)
  wire G175;
  (* src = "/content/ISCAS89/s1423.v:30.65-30.69" *)
  wire G179;
  (* src = "/content/ISCAS89/s1423.v:30.75-30.79" *)
  wire G188;
  (* src = "/content/ISCAS89/s1423.v:21.68-21.72" *)
  wire G189;
  (* src = "/content/ISCAS89/s1423.v:31.10-31.14" *)
  wire G192;
  (* src = "/content/ISCAS89/s1423.v:22.5-22.9" *)
  wire G193;
  (* src = "/content/ISCAS89/s1423.v:31.15-31.19" *)
  wire G197;
  (* src = "/content/ISCAS89/s1423.v:22.14-22.18" *)
  wire G198;
  (* src = "/content/ISCAS89/s1423.v:17.16-17.18" *)
  input G2;
  wire G2;
  (* src = "/content/ISCAS89/s1423.v:31.25-31.29" *)
  wire G207;
  (* src = "/content/ISCAS89/s1423.v:22.23-22.27" *)
  wire G208;
  (* src = "/content/ISCAS89/s1423.v:31.35-31.39" *)
  wire G213;
  (* src = "/content/ISCAS89/s1423.v:22.32-22.36" *)
  wire G214;
  (* src = "/content/ISCAS89/s1423.v:31.45-31.49" *)
  wire G217;
  (* src = "/content/ISCAS89/s1423.v:22.41-22.45" *)
  wire G218;
  (* src = "/content/ISCAS89/s1423.v:20.8-20.11" *)
  wire G22;
  (* src = "/content/ISCAS89/s1423.v:20.19-20.22" *)
  wire G23;
  (* src = "/content/ISCAS89/s1423.v:22.50-22.54" *)
  wire G237;
  (* src = "/content/ISCAS89/s1423.v:20.30-20.33" *)
  wire G24;
  (* src = "/content/ISCAS89/s1423.v:22.59-22.63" *)
  wire G242;
  (* src = "/content/ISCAS89/s1423.v:22.68-22.72" *)
  wire G247;
  (* src = "/content/ISCAS89/s1423.v:20.39-20.42" *)
  wire G25;
  (* src = "/content/ISCAS89/s1423.v:23.5-23.9" *)
  wire G252;
  (* src = "/content/ISCAS89/s1423.v:20.48-20.51" *)
  wire G26;
  (* src = "/content/ISCAS89/s1423.v:23.14-23.18" *)
  wire G260;
  (* src = "/content/ISCAS89/s1423.v:20.57-20.60" *)
  wire G27;
  (* src = "/content/ISCAS89/s1423.v:20.66-20.69" *)
  wire G28;
  (* src = "/content/ISCAS89/s1423.v:20.75-20.78" *)
  wire G29;
  (* src = "/content/ISCAS89/s1423.v:17.19-17.21" *)
  input G3;
  wire G3;
  (* src = "/content/ISCAS89/s1423.v:21.10-21.13" *)
  wire G30;
  (* src = "/content/ISCAS89/s1423.v:32.15-32.19" *)
  wire G302;
  (* src = "/content/ISCAS89/s1423.v:23.23-23.27" *)
  wire G303;
  (* src = "/content/ISCAS89/s1423.v:32.30-32.34" *)
  wire G308;
  (* src = "/content/ISCAS89/s1423.v:23.32-23.36" *)
  wire G309;
  (* src = "/content/ISCAS89/s1423.v:21.19-21.22" *)
  wire G31;
  (* src = "/content/ISCAS89/s1423.v:32.40-32.44" *)
  wire G314;
  (* src = "/content/ISCAS89/s1423.v:23.41-23.45" *)
  wire G315;
  (* src = "/content/ISCAS89/s1423.v:21.28-21.31" *)
  wire G32;
  (* src = "/content/ISCAS89/s1423.v:32.50-32.54" *)
  wire G320;
  (* src = "/content/ISCAS89/s1423.v:23.50-23.54" *)
  wire G321;
  (* src = "/content/ISCAS89/s1423.v:29.42-29.46" *)
  wire G328;
  (* src = "/content/ISCAS89/s1423.v:20.23-20.29" *)
  wire G328BF;
  (* src = "/content/ISCAS89/s1423.v:21.37-21.40" *)
  wire G33;
  (* src = "/content/ISCAS89/s1423.v:29.32-29.36" *)
  wire G332;
  (* src = "/content/ISCAS89/s1423.v:20.12-20.18" *)
  wire G332BF;
  (* src = "/content/ISCAS89/s1423.v:21.46-21.49" *)
  wire G34;
  (* src = "/content/ISCAS89/s1423.v:32.75-32.79" *)
  wire G343;
  (* src = "/content/ISCAS89/s1423.v:33.10-33.14" *)
  wire G347;
  (* src = "/content/ISCAS89/s1423.v:21.55-21.58" *)
  wire G35;
  (* src = "/content/ISCAS89/s1423.v:33.15-33.19" *)
  wire G351;
  (* src = "/content/ISCAS89/s1423.v:21.64-21.67" *)
  wire G36;
  (* src = "/content/ISCAS89/s1423.v:23.59-23.63" *)
  wire G360;
  (* src = "/content/ISCAS89/s1423.v:23.68-23.72" *)
  wire G365;
  (* src = "/content/ISCAS89/s1423.v:21.73-21.76" *)
  wire G37;
  (* src = "/content/ISCAS89/s1423.v:24.5-24.9" *)
  wire G373;
  (* src = "/content/ISCAS89/s1423.v:24.14-24.18" *)
  wire G379;
  (* src = "/content/ISCAS89/s1423.v:22.10-22.13" *)
  wire G38;
  (* src = "/content/ISCAS89/s1423.v:24.23-24.27" *)
  wire G384;
  (* src = "/content/ISCAS89/s1423.v:22.19-22.22" *)
  wire G39;
  (* src = "/content/ISCAS89/s1423.v:24.32-24.36" *)
  wire G392;
  (* src = "/content/ISCAS89/s1423.v:24.41-24.45" *)
  wire G397;
  (* src = "/content/ISCAS89/s1423.v:17.22-17.24" *)
  input G4;
  wire G4;
  (* src = "/content/ISCAS89/s1423.v:22.28-22.31" *)
  wire G40;
  (* src = "/content/ISCAS89/s1423.v:24.50-24.54" *)
  wire G405;
  (* src = "/content/ISCAS89/s1423.v:34.10-34.14" *)
  wire G407;
  (* src = "/content/ISCAS89/s1423.v:24.59-24.63" *)
  wire G408;
  (* src = "/content/ISCAS89/s1423.v:22.37-22.40" *)
  wire G41;
  (* src = "/content/ISCAS89/s1423.v:24.68-24.72" *)
  wire G416;
  (* src = "/content/ISCAS89/s1423.v:22.46-22.49" *)
  wire G42;
  (* src = "/content/ISCAS89/s1423.v:25.5-25.9" *)
  wire G424;
  (* src = "/content/ISCAS89/s1423.v:34.30-34.34" *)
  wire G426;
  (* src = "/content/ISCAS89/s1423.v:25.14-25.18" *)
  wire G427;
  (* src = "/content/ISCAS89/s1423.v:22.55-22.58" *)
  wire G43;
  (* src = "/content/ISCAS89/s1423.v:34.35-34.39" *)
  wire G437;
  (* src = "/content/ISCAS89/s1423.v:25.23-25.27" *)
  wire G438;
  (* src = "/content/ISCAS89/s1423.v:22.64-22.67" *)
  wire G44;
  (* src = "/content/ISCAS89/s1423.v:34.40-34.44" *)
  wire G440;
  (* src = "/content/ISCAS89/s1423.v:25.32-25.36" *)
  wire G441;
  (* src = "/content/ISCAS89/s1423.v:34.50-34.54" *)
  wire G446;
  (* src = "/content/ISCAS89/s1423.v:25.41-25.45" *)
  wire G447;
  (* src = "/content/ISCAS89/s1423.v:22.73-22.76" *)
  wire G45;
  (* src = "/content/ISCAS89/s1423.v:34.60-34.64" *)
  wire G450;
  (* src = "/content/ISCAS89/s1423.v:25.50-25.54" *)
  wire G451;
  (* src = "/content/ISCAS89/s1423.v:25.59-25.63" *)
  wire G459;
  (* src = "/content/ISCAS89/s1423.v:23.10-23.13" *)
  wire G46;
  (* src = "/content/ISCAS89/s1423.v:25.68-25.72" *)
  wire G464;
  (* src = "/content/ISCAS89/s1423.v:26.5-26.9" *)
  wire G469;
  (* src = "/content/ISCAS89/s1423.v:23.19-23.22" *)
  wire G47;
  (* src = "/content/ISCAS89/s1423.v:26.14-26.18" *)
  wire G477;
  (* src = "/content/ISCAS89/s1423.v:23.28-23.31" *)
  wire G48;
  (* src = "/content/ISCAS89/s1423.v:35.25-35.29" *)
  wire G486;
  (* src = "/content/ISCAS89/s1423.v:23.37-23.40" *)
  wire G49;
  (* src = "/content/ISCAS89/s1423.v:26.23-26.27" *)
  wire G494;
  (* src = "/content/ISCAS89/s1423.v:26.32-26.36" *)
  wire G498;
  (* src = "/content/ISCAS89/s1423.v:17.25-17.27" *)
  input G5;
  wire G5;
  (* src = "/content/ISCAS89/s1423.v:23.46-23.49" *)
  wire G50;
  (* src = "/content/ISCAS89/s1423.v:26.41-26.45" *)
  wire G503;
  (* src = "/content/ISCAS89/s1423.v:35.50-35.54" *)
  wire G504;
  (* src = "/content/ISCAS89/s1423.v:35.60-35.64" *)
  wire G507;
  (* src = "/content/ISCAS89/s1423.v:23.55-23.58" *)
  wire G51;
  (* src = "/content/ISCAS89/s1423.v:35.65-35.69" *)
  wire G510;
  (* src = "/content/ISCAS89/s1423.v:23.64-23.67" *)
  wire G52;
  (* src = "/content/ISCAS89/s1423.v:26.50-26.54" *)
  wire G526;
  (* src = "/content/ISCAS89/s1423.v:23.73-23.76" *)
  wire G53;
  (* src = "/content/ISCAS89/s1423.v:26.59-26.63" *)
  wire G531;
  (* src = "/content/ISCAS89/s1423.v:26.68-26.72" *)
  wire G536;
  (* src = "/content/ISCAS89/s1423.v:24.10-24.13" *)
  wire G54;
  (* src = "/content/ISCAS89/s1423.v:27.5-27.9" *)
  wire G541;
  (* src = "/content/ISCAS89/s1423.v:27.14-27.18" *)
  wire G548;
  (* src = "/content/ISCAS89/s1423.v:24.19-24.22" *)
  wire G55;
  (* src = "/content/ISCAS89/s1423.v:24.28-24.31" *)
  wire G56;
  (* src = "/content/ISCAS89/s1423.v:27.23-27.27" *)
  wire G565;
  (* src = "/content/ISCAS89/s1423.v:27.32-27.36" *)
  wire G569;
  (* src = "/content/ISCAS89/s1423.v:24.37-24.40" *)
  wire G57;
  (* src = "/content/ISCAS89/s1423.v:27.41-27.45" *)
  wire G573;
  (* src = "/content/ISCAS89/s1423.v:27.50-27.54" *)
  wire G577;
  (* src = "/content/ISCAS89/s1423.v:24.46-24.49" *)
  wire G58;
  (* src = "/content/ISCAS89/s1423.v:24.55-24.58" *)
  wire G59;
  (* src = "/content/ISCAS89/s1423.v:27.59-27.63" *)
  wire G590;
  (* src = "/content/ISCAS89/s1423.v:17.28-17.30" *)
  input G6;
  wire G6;
  (* src = "/content/ISCAS89/s1423.v:24.64-24.67" *)
  wire G60;
  (* src = "/content/ISCAS89/s1423.v:27.68-27.72" *)
  wire G608;
  (* src = "/content/ISCAS89/s1423.v:24.73-24.76" *)
  wire G61;
  (* src = "/content/ISCAS89/s1423.v:28.5-28.9" *)
  wire G613;
  (* src = "/content/ISCAS89/s1423.v:37.35-37.39" *)
  wire G617;
  (* src = "/content/ISCAS89/s1423.v:25.10-25.13" *)
  wire G62;
  (* src = "/content/ISCAS89/s1423.v:37.40-37.44" *)
  wire G620;
  (* src = "/content/ISCAS89/s1423.v:37.45-37.49" *)
  wire G623;
  (* src = "/content/ISCAS89/s1423.v:37.50-37.54" *)
  wire G626;
  (* src = "/content/ISCAS89/s1423.v:37.55-37.59" *)
  wire G629;
  (* src = "/content/ISCAS89/s1423.v:25.19-25.22" *)
  wire G63;
  (* src = "/content/ISCAS89/s1423.v:37.60-37.64" *)
  wire G632;
  (* src = "/content/ISCAS89/s1423.v:37.65-37.69" *)
  wire G635;
  (* src = "/content/ISCAS89/s1423.v:37.70-37.74" *)
  wire G638;
  (* src = "/content/ISCAS89/s1423.v:25.28-25.31" *)
  wire G64;
  (* src = "/content/ISCAS89/s1423.v:37.75-37.79" *)
  wire G641;
  (* src = "/content/ISCAS89/s1423.v:38.5-38.9" *)
  wire G644;
  (* src = "/content/ISCAS89/s1423.v:25.37-25.40" *)
  wire G65;
  (* src = "/content/ISCAS89/s1423.v:38.10-38.14" *)
  wire G656;
  (* src = "/content/ISCAS89/s1423.v:28.14-28.18" *)
  wire G657;
  (* src = "/content/ISCAS89/s1423.v:38.20-38.24" *)
  wire G659;
  (* src = "/content/ISCAS89/s1423.v:25.46-25.49" *)
  wire G66;
  (* src = "/content/ISCAS89/s1423.v:38.37-38.41" *)
  wire G662;
  (* src = "/content/ISCAS89/s1423.v:28.23-28.27" *)
  wire G663;
  (* src = "/content/ISCAS89/s1423.v:38.52-38.56" *)
  wire G668;
  (* src = "/content/ISCAS89/s1423.v:28.32-28.36" *)
  wire G669;
  (* src = "/content/ISCAS89/s1423.v:25.55-25.58" *)
  wire G67;
  (* src = "/content/ISCAS89/s1423.v:38.62-38.66" *)
  wire G674;
  (* src = "/content/ISCAS89/s1423.v:28.41-28.45" *)
  wire G675;
  (* src = "/content/ISCAS89/s1423.v:38.47-38.51" *)
  wire G678;
  (* src = "/content/ISCAS89/s1423.v:25.64-25.67" *)
  wire G68;
  (* src = "/content/ISCAS89/s1423.v:28.50-28.54" *)
  wire G682;
  (* src = "/content/ISCAS89/s1423.v:28.59-28.63" *)
  wire G687;
  (* src = "/content/ISCAS89/s1423.v:25.73-25.76" *)
  wire G69;
  (* src = "/content/ISCAS89/s1423.v:28.68-28.72" *)
  wire G693;
  (* src = "/content/ISCAS89/s1423.v:39.10-39.14" *)
  wire G696;
  (* src = "/content/ISCAS89/s1423.v:17.31-17.33" *)
  input G7;
  wire G7;
  (* src = "/content/ISCAS89/s1423.v:26.10-26.13" *)
  wire G70;
  (* src = "/content/ISCAS89/s1423.v:39.32-39.36" *)
  wire G701;
  (* src = "/content/ISCAS89/s1423.v:18.28-18.34" *)
  output G701BF;
  wire G701BF;
  (* src = "/content/ISCAS89/s1423.v:18.18-18.22" *)
  output G702;
  wire G702;
  (* src = "/content/ISCAS89/s1423.v:39.44-39.48" *)
  wire G704;
  (* src = "/content/ISCAS89/s1423.v:29.5-29.9" *)
  wire G705;
  (* src = "/content/ISCAS89/s1423.v:39.49-39.53" *)
  wire G706;
  (* src = "/content/ISCAS89/s1423.v:29.14-29.18" *)
  wire G707;
  (* src = "/content/ISCAS89/s1423.v:26.19-26.22" *)
  wire G71;
  (* src = "/content/ISCAS89/s1423.v:39.54-39.58" *)
  wire G711;
  (* src = "/content/ISCAS89/s1423.v:29.23-29.27" *)
  wire G713;
  (* src = "/content/ISCAS89/s1423.v:39.59-39.63" *)
  wire G714;
  (* src = "/content/ISCAS89/s1423.v:39.71-39.75" *)
  wire G715;
  (* src = "/content/ISCAS89/s1423.v:40.12-40.16" *)
  wire G716;
  (* src = "/content/ISCAS89/s1423.v:40.24-40.28" *)
  wire G717;
  (* src = "/content/ISCAS89/s1423.v:40.36-40.40" *)
  wire G718;
  (* src = "/content/ISCAS89/s1423.v:40.48-40.52" *)
  wire G719;
  (* src = "/content/ISCAS89/s1423.v:26.28-26.31" *)
  wire G72;
  (* src = "/content/ISCAS89/s1423.v:40.60-40.64" *)
  wire G720;
  (* src = "/content/ISCAS89/s1423.v:40.72-40.76" *)
  wire G721;
  (* src = "/content/ISCAS89/s1423.v:41.12-41.16" *)
  wire G722;
  (* src = "/content/ISCAS89/s1423.v:41.24-41.28" *)
  wire G723;
  (* src = "/content/ISCAS89/s1423.v:41.36-41.40" *)
  wire G724;
  (* src = "/content/ISCAS89/s1423.v:41.48-41.52" *)
  wire G725;
  (* src = "/content/ISCAS89/s1423.v:18.8-18.12" *)
  output G726;
  wire G726;
  (* src = "/content/ISCAS89/s1423.v:18.23-18.27" *)
  output G727;
  wire G727;
  (* src = "/content/ISCAS89/s1423.v:41.67-41.71" *)
  wire G728;
  (* src = "/content/ISCAS89/s1423.v:18.13-18.17" *)
  output G729;
  wire G729;
  (* src = "/content/ISCAS89/s1423.v:26.37-26.40" *)
  wire G73;
  (* src = "/content/ISCAS89/s1423.v:26.46-26.49" *)
  wire G74;
  (* src = "/content/ISCAS89/s1423.v:26.55-26.58" *)
  wire G75;
  (* src = "/content/ISCAS89/s1423.v:26.64-26.67" *)
  wire G76;
  (* src = "/content/ISCAS89/s1423.v:26.73-26.76" *)
  wire G77;
  (* src = "/content/ISCAS89/s1423.v:27.10-27.13" *)
  wire G78;
  (* src = "/content/ISCAS89/s1423.v:27.19-27.22" *)
  wire G79;
  (* src = "/content/ISCAS89/s1423.v:17.34-17.36" *)
  input G8;
  wire G8;
  (* src = "/content/ISCAS89/s1423.v:27.28-27.31" *)
  wire G80;
  (* src = "/content/ISCAS89/s1423.v:27.37-27.40" *)
  wire G81;
  (* src = "/content/ISCAS89/s1423.v:27.46-27.49" *)
  wire G82;
  (* src = "/content/ISCAS89/s1423.v:27.55-27.58" *)
  wire G83;
  (* src = "/content/ISCAS89/s1423.v:27.64-27.67" *)
  wire G84;
  (* src = "/content/ISCAS89/s1423.v:27.73-27.76" *)
  wire G85;
  (* src = "/content/ISCAS89/s1423.v:28.10-28.13" *)
  wire G86;
  (* src = "/content/ISCAS89/s1423.v:28.19-28.22" *)
  wire G87;
  (* src = "/content/ISCAS89/s1423.v:28.28-28.31" *)
  wire G88;
  (* src = "/content/ISCAS89/s1423.v:28.37-28.40" *)
  wire G89;
  (* src = "/content/ISCAS89/s1423.v:17.37-17.39" *)
  input G9;
  wire G9;
  (* src = "/content/ISCAS89/s1423.v:28.46-28.49" *)
  wire G90;
  (* src = "/content/ISCAS89/s1423.v:28.55-28.58" *)
  wire G91;
  (* src = "/content/ISCAS89/s1423.v:28.64-28.67" *)
  wire G92;
  (* src = "/content/ISCAS89/s1423.v:28.73-28.76" *)
  wire G93;
  (* src = "/content/ISCAS89/s1423.v:29.10-29.13" *)
  wire G94;
  (* src = "/content/ISCAS89/s1423.v:29.19-29.22" *)
  wire G95;
  (* src = "/content/ISCAS89/s1423.v:39.37-39.43" *)
  wire II1211;
  INV _326_ (
    .A(G24),
    .Y(_000_)
  );
  INV _327_ (
    .A(G29),
    .Y(_001_)
  );
  INV _328_ (
    .A(G34),
    .Y(_002_)
  );
  INV _329_ (
    .A(G36),
    .Y(_003_)
  );
  INV _330_ (
    .A(G38),
    .Y(_004_)
  );
  INV _331_ (
    .A(G39),
    .Y(_005_)
  );
  INV _332_ (
    .A(G40),
    .Y(_006_)
  );
  INV _333_ (
    .A(G343),
    .Y(_007_)
  );
  INV _334_ (
    .A(G66),
    .Y(_008_)
  );
  INV _335_ (
    .A(G504),
    .Y(_009_)
  );
  INV _336_ (
    .A(G351),
    .Y(_010_)
  );
  INV _337_ (
    .A(G11),
    .Y(_011_)
  );
  INV _338_ (
    .A(G10),
    .Y(_012_)
  );
  INV _339_ (
    .A(G15),
    .Y(G701BF)
  );
  INV _340_ (
    .A(G14),
    .Y(_013_)
  );
  INV _341_ (
    .A(G60),
    .Y(_014_)
  );
  INV _342_ (
    .A(G70),
    .Y(_015_)
  );
  INV _343_ (
    .A(G68),
    .Y(_016_)
  );
  INV _344_ (
    .A(G69),
    .Y(_017_)
  );
  INV _345_ (
    .A(G78),
    .Y(_018_)
  );
  INV _346_ (
    .A(G74),
    .Y(_019_)
  );
  INV _347_ (
    .A(G75),
    .Y(_020_)
  );
  INV _348_ (
    .A(G76),
    .Y(_021_)
  );
  INV _349_ (
    .A(G77),
    .Y(_022_)
  );
  INV _350_ (
    .A(G87),
    .Y(_023_)
  );
  INV _351_ (
    .A(G42),
    .Y(_024_)
  );
  INV _352_ (
    .A(G44),
    .Y(_025_)
  );
  INV _353_ (
    .A(G62),
    .Y(_026_)
  );
  INV _354_ (
    .A(G59),
    .Y(_027_)
  );
  INV _355_ (
    .A(G71),
    .Y(_028_)
  );
  INV _356_ (
    .A(G72),
    .Y(_029_)
  );
  INV _357_ (
    .A(G3),
    .Y(_030_)
  );
  INV _358_ (
    .A(G4),
    .Y(_031_)
  );
  INV _359_ (
    .A(G1),
    .Y(_032_)
  );
  INV _360_ (
    .A(G2),
    .Y(_033_)
  );
  INV _361_ (
    .A(G6),
    .Y(_034_)
  );
  INV _362_ (
    .A(G7),
    .Y(_035_)
  );
  INV _363_ (
    .A(G8),
    .Y(_036_)
  );
  INV _364_ (
    .A(G82),
    .Y(_037_)
  );
  INV _365_ (
    .A(G9),
    .Y(_038_)
  );
  INV _366_ (
    .A(G85),
    .Y(_039_)
  );
  INV _367_ (
    .A(G84),
    .Y(_040_)
  );
  INV _368_ (
    .A(G22),
    .Y(_041_)
  );
  INV _369_ (
    .A(G25),
    .Y(_042_)
  );
  INV _370_ (
    .A(G26),
    .Y(_043_)
  );
  INV _371_ (
    .A(G30),
    .Y(_044_)
  );
  INV _372_ (
    .A(G31),
    .Y(_045_)
  );
  INV _373_ (
    .A(G33),
    .Y(_046_)
  );
  INV _374_ (
    .A(G37),
    .Y(_047_)
  );
  INV _375_ (
    .A(G41),
    .Y(_048_)
  );
  INV _376_ (
    .A(G51),
    .Y(_049_)
  );
  INV _377_ (
    .A(G55),
    .Y(_050_)
  );
  INV _378_ (
    .A(G57),
    .Y(_051_)
  );
  INV _379_ (
    .A(G58),
    .Y(_052_)
  );
  INV _380_ (
    .A(G86),
    .Y(_053_)
  );
  NAND2 _381_ (
    .A(G50),
    .B(G49),
    .Y(_054_)
  );
  INV _382_ (
    .A(_054_),
    .Y(_055_)
  );
  AOI21 _383_ (
    .A0(G48),
    .A1(G47),
    .B0(_055_),
    .Y(_056_)
  );
  NOR3 _384_ (
    .A(G49),
    .B(G48),
    .C(G47),
    .Y(_057_)
  );
  INV _385_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR3 _386_ (
    .A(G15),
    .B(G50),
    .C(_058_),
    .Y(_059_)
  );
  OAI22 _387_ (
    .A0(G15),
    .A1(_056_),
    .B0(_059_),
    .B1(_041_),
    .Y(G332)
  );
  NAND2 _388_ (
    .A(G701BF),
    .B(G23),
    .Y(_060_)
  );
  OAI21 _389_ (
    .A0(G701BF),
    .A1(_041_),
    .B0(_060_),
    .Y(G328)
  );
  XNOR2 _390_ (
    .A(G74),
    .B(G79),
    .Y(_061_)
  );
  XNOR2 _391_ (
    .A(G75),
    .B(G80),
    .Y(_062_)
  );
  NAND2 _392_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  XOR2 _393_ (
    .A(G76),
    .B(G81),
    .Y(_064_)
  );
  XOR2 _394_ (
    .A(G77),
    .B(G82),
    .Y(_065_)
  );
  NOR3 _395_ (
    .A(_063_),
    .B(_064_),
    .C(_065_),
    .Y(_066_)
  );
  NOR3 _396_ (
    .A(G79),
    .B(G80),
    .C(G81),
    .Y(_067_)
  );
  NAND2 _397_ (
    .A(_037_),
    .B(_067_),
    .Y(_068_)
  );
  XNOR2 _398_ (
    .A(_018_),
    .B(_068_),
    .Y(_069_)
  );
  NAND2 _399_ (
    .A(_066_),
    .B(_069_),
    .Y(_070_)
  );
  INV _400_ (
    .A(_070_),
    .Y(_071_)
  );
  NOR2 _401_ (
    .A(G83),
    .B(_070_),
    .Y(_072_)
  );
  AOI21 _402_ (
    .A0(_008_),
    .A1(G16),
    .B0(_072_),
    .Y(_073_)
  );
  NAND2 _403_ (
    .A(G351),
    .B(_073_),
    .Y(_074_)
  );
  NOR2 _404_ (
    .A(G38),
    .B(_074_),
    .Y(_075_)
  );
  NAND2 _405_ (
    .A(G34),
    .B(G179),
    .Y(_076_)
  );
  OAI21 _406_ (
    .A0(G35),
    .A1(G179),
    .B0(_076_),
    .Y(_077_)
  );
  NAND2 _407_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  INV _408_ (
    .A(_078_),
    .Y(_079_)
  );
  NOR2 _409_ (
    .A(_075_),
    .B(_079_),
    .Y(_080_)
  );
  OAI21 _410_ (
    .A0(G504),
    .A1(_080_),
    .B0(G14),
    .Y(_081_)
  );
  INV _411_ (
    .A(_081_),
    .Y(G438)
  );
  OAI21 _412_ (
    .A0(G70),
    .A1(_029_),
    .B0(G68),
    .Y(_082_)
  );
  OAI21 _413_ (
    .A0(G70),
    .A1(_028_),
    .B0(G67),
    .Y(_083_)
  );
  AOI21 _414_ (
    .A0(_015_),
    .A1(G69),
    .B0(G73),
    .Y(_084_)
  );
  OAI21 _415_ (
    .A0(G69),
    .A1(G73),
    .B0(_084_),
    .Y(_085_)
  );
  NOR3 _416_ (
    .A(G70),
    .B(G68),
    .C(G69),
    .Y(_086_)
  );
  NOR2 _417_ (
    .A(G71),
    .B(_086_),
    .Y(_087_)
  );
  NOR2 _418_ (
    .A(G67),
    .B(_087_),
    .Y(_088_)
  );
  OAI21 _419_ (
    .A0(G68),
    .A1(_029_),
    .B0(_082_),
    .Y(_089_)
  );
  NOR2 _420_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  NAND2 _421_ (
    .A(_083_),
    .B(_085_),
    .Y(_091_)
  );
  NOR3 _422_ (
    .A(_088_),
    .B(_089_),
    .C(_091_),
    .Y(_092_)
  );
  AOI21 _423_ (
    .A0(_083_),
    .A1(_085_),
    .B0(_090_),
    .Y(_093_)
  );
  NOR2 _424_ (
    .A(G64),
    .B(_092_),
    .Y(_094_)
  );
  OAI21 _425_ (
    .A0(G504),
    .A1(_093_),
    .B0(G14),
    .Y(_095_)
  );
  NOR2 _426_ (
    .A(_094_),
    .B(_095_),
    .Y(G441)
  );
  OAI21 _427_ (
    .A0(G65),
    .A1(_092_),
    .B0(G14),
    .Y(_096_)
  );
  INV _428_ (
    .A(_096_),
    .Y(G447)
  );
  NOR2 _429_ (
    .A(G66),
    .B(_092_),
    .Y(_097_)
  );
  OAI21 _430_ (
    .A0(G65),
    .A1(_093_),
    .B0(G14),
    .Y(_098_)
  );
  NOR2 _431_ (
    .A(_097_),
    .B(_098_),
    .Y(G451)
  );
  OAI21 _432_ (
    .A0(G343),
    .A1(_027_),
    .B0(G351),
    .Y(_099_)
  );
  NAND2 _433_ (
    .A(G64),
    .B(G351),
    .Y(_100_)
  );
  OAI21 _434_ (
    .A0(G351),
    .A1(G8),
    .B0(_100_),
    .Y(_101_)
  );
  NAND2 _435_ (
    .A(_039_),
    .B(_101_),
    .Y(_102_)
  );
  NAND2 _436_ (
    .A(G85),
    .B(_101_),
    .Y(_103_)
  );
  OAI21 _437_ (
    .A0(_040_),
    .A1(_101_),
    .B0(_103_),
    .Y(_104_)
  );
  OAI21 _438_ (
    .A0(G84),
    .A1(_101_),
    .B0(_102_),
    .Y(_105_)
  );
  OAI21 _439_ (
    .A0(_018_),
    .A1(_105_),
    .B0(G351),
    .Y(_106_)
  );
  OAI21 _440_ (
    .A0(G351),
    .A1(_031_),
    .B0(_106_),
    .Y(_107_)
  );
  OAI21 _441_ (
    .A0(_022_),
    .A1(_105_),
    .B0(G351),
    .Y(_108_)
  );
  OAI21 _442_ (
    .A0(G351),
    .A1(_030_),
    .B0(_108_),
    .Y(_109_)
  );
  OAI21 _443_ (
    .A0(_021_),
    .A1(_105_),
    .B0(G351),
    .Y(_110_)
  );
  OAI21 _444_ (
    .A0(G351),
    .A1(_033_),
    .B0(_110_),
    .Y(_111_)
  );
  AOI22 _445_ (
    .A0(G45),
    .A1(_109_),
    .B0(_111_),
    .B1(G44),
    .Y(_112_)
  );
  NAND2 _446_ (
    .A(G351),
    .B(G74),
    .Y(_113_)
  );
  OAI22 _447_ (
    .A0(G351),
    .A1(G0),
    .B0(_105_),
    .B1(_113_),
    .Y(_114_)
  );
  NOR2 _448_ (
    .A(_024_),
    .B(_114_),
    .Y(_115_)
  );
  NAND2 _449_ (
    .A(G351),
    .B(G75),
    .Y(_116_)
  );
  INV _450_ (
    .A(_116_),
    .Y(_117_)
  );
  AOI22 _451_ (
    .A0(_010_),
    .A1(_032_),
    .B0(_104_),
    .B1(_117_),
    .Y(_118_)
  );
  XNOR2 _452_ (
    .A(G43),
    .B(_118_),
    .Y(_119_)
  );
  NOR2 _453_ (
    .A(_115_),
    .B(_119_),
    .Y(_120_)
  );
  NOR2 _454_ (
    .A(G44),
    .B(_111_),
    .Y(_121_)
  );
  OAI22 _455_ (
    .A0(G44),
    .A1(_111_),
    .B0(_118_),
    .B1(G43),
    .Y(_122_)
  );
  OAI21 _456_ (
    .A0(_120_),
    .A1(_122_),
    .B0(_112_),
    .Y(_123_)
  );
  OAI22 _457_ (
    .A0(G46),
    .A1(_107_),
    .B0(_109_),
    .B1(G45),
    .Y(_124_)
  );
  INV _458_ (
    .A(_124_),
    .Y(_125_)
  );
  AOI22 _459_ (
    .A0(G46),
    .A1(_107_),
    .B0(_123_),
    .B1(_125_),
    .Y(_126_)
  );
  INV _460_ (
    .A(_126_),
    .Y(_127_)
  );
  NOR2 _461_ (
    .A(G24),
    .B(_127_),
    .Y(_128_)
  );
  NOR3 _462_ (
    .A(G24),
    .B(_042_),
    .C(_127_),
    .Y(_129_)
  );
  AOI21 _463_ (
    .A0(_000_),
    .A1(G25),
    .B0(_126_),
    .Y(_130_)
  );
  NAND2 _464_ (
    .A(G26),
    .B(_129_),
    .Y(_131_)
  );
  NOR3 _465_ (
    .A(G27),
    .B(_043_),
    .C(_130_),
    .Y(_132_)
  );
  NAND2 _466_ (
    .A(G28),
    .B(_132_),
    .Y(_133_)
  );
  NAND2 _467_ (
    .A(G179),
    .B(_133_),
    .Y(_134_)
  );
  INV _468_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR2 _469_ (
    .A(G29),
    .B(_135_),
    .Y(_136_)
  );
  NOR3 _470_ (
    .A(G29),
    .B(_044_),
    .C(_135_),
    .Y(_137_)
  );
  AOI21 _471_ (
    .A0(_001_),
    .A1(G30),
    .B0(_134_),
    .Y(_138_)
  );
  NOR2 _472_ (
    .A(_045_),
    .B(_138_),
    .Y(_139_)
  );
  NAND2 _473_ (
    .A(G32),
    .B(_139_),
    .Y(_140_)
  );
  AOI21 _474_ (
    .A0(G32),
    .A1(G33),
    .B0(_139_),
    .Y(_141_)
  );
  INV _475_ (
    .A(_141_),
    .Y(_142_)
  );
  OAI21 _476_ (
    .A0(G34),
    .A1(_141_),
    .B0(G179),
    .Y(_143_)
  );
  NAND2 _477_ (
    .A(_005_),
    .B(_143_),
    .Y(_144_)
  );
  AOI21 _478_ (
    .A0(_005_),
    .A1(_006_),
    .B0(_143_),
    .Y(_145_)
  );
  NOR2 _479_ (
    .A(_048_),
    .B(_145_),
    .Y(_146_)
  );
  NOR2 _480_ (
    .A(_007_),
    .B(_146_),
    .Y(_147_)
  );
  OAI21 _481_ (
    .A0(_048_),
    .A1(_145_),
    .B0(G343),
    .Y(_148_)
  );
  NOR2 _482_ (
    .A(G36),
    .B(_147_),
    .Y(_149_)
  );
  NOR3 _483_ (
    .A(G36),
    .B(_047_),
    .C(_147_),
    .Y(_150_)
  );
  AOI21 _484_ (
    .A0(_003_),
    .A1(G37),
    .B0(_148_),
    .Y(_151_)
  );
  NOR2 _485_ (
    .A(_004_),
    .B(_151_),
    .Y(_152_)
  );
  NOR3 _486_ (
    .A(_004_),
    .B(_074_),
    .C(_151_),
    .Y(_153_)
  );
  NAND2 _487_ (
    .A(_074_),
    .B(_143_),
    .Y(_154_)
  );
  INV _488_ (
    .A(_154_),
    .Y(_155_)
  );
  NOR2 _489_ (
    .A(_153_),
    .B(_155_),
    .Y(_156_)
  );
  NOR2 _490_ (
    .A(_052_),
    .B(_156_),
    .Y(_157_)
  );
  OAI21 _491_ (
    .A0(_153_),
    .A1(_155_),
    .B0(G58),
    .Y(_158_)
  );
  NOR2 _492_ (
    .A(_027_),
    .B(_158_),
    .Y(_159_)
  );
  OAI21 _493_ (
    .A0(_010_),
    .A1(_157_),
    .B0(_099_),
    .Y(_160_)
  );
  OAI21 _494_ (
    .A0(_027_),
    .A1(_158_),
    .B0(G343),
    .Y(_161_)
  );
  INV _495_ (
    .A(_161_),
    .Y(_162_)
  );
  NAND2 _496_ (
    .A(G53),
    .B(_161_),
    .Y(_163_)
  );
  INV _497_ (
    .A(_163_),
    .Y(_164_)
  );
  AOI21 _498_ (
    .A0(G61),
    .A1(G53),
    .B0(_161_),
    .Y(_165_)
  );
  NAND2 _499_ (
    .A(G343),
    .B(G62),
    .Y(_166_)
  );
  INV _500_ (
    .A(_166_),
    .Y(_167_)
  );
  NOR2 _501_ (
    .A(_026_),
    .B(_165_),
    .Y(_168_)
  );
  OAI21 _502_ (
    .A0(_165_),
    .A1(_166_),
    .B0(_160_),
    .Y(_169_)
  );
  NOR2 _503_ (
    .A(G67),
    .B(_169_),
    .Y(_170_)
  );
  NAND2 _504_ (
    .A(G67),
    .B(_169_),
    .Y(_171_)
  );
  INV _505_ (
    .A(_171_),
    .Y(_172_)
  );
  NAND2 _506_ (
    .A(G14),
    .B(_093_),
    .Y(_173_)
  );
  INV _507_ (
    .A(_173_),
    .Y(_174_)
  );
  NOR3 _508_ (
    .A(_170_),
    .B(_172_),
    .C(_173_),
    .Y(G459)
  );
  NOR2 _509_ (
    .A(_016_),
    .B(_171_),
    .Y(_175_)
  );
  OAI21 _510_ (
    .A0(G68),
    .A1(_172_),
    .B0(_174_),
    .Y(_176_)
  );
  NOR2 _511_ (
    .A(_175_),
    .B(_176_),
    .Y(G464)
  );
  NOR3 _512_ (
    .A(_016_),
    .B(_017_),
    .C(_171_),
    .Y(_177_)
  );
  OAI21 _513_ (
    .A0(G69),
    .A1(_175_),
    .B0(_174_),
    .Y(_178_)
  );
  NOR2 _514_ (
    .A(_177_),
    .B(_178_),
    .Y(G469)
  );
  XNOR2 _515_ (
    .A(G70),
    .B(_177_),
    .Y(_179_)
  );
  NOR2 _516_ (
    .A(_173_),
    .B(_179_),
    .Y(G477)
  );
  OAI21 _517_ (
    .A0(G351),
    .A1(_013_),
    .B0(_173_),
    .Y(_180_)
  );
  NAND2 _518_ (
    .A(G504),
    .B(_030_),
    .Y(_181_)
  );
  OAI21 _519_ (
    .A0(G504),
    .A1(G0),
    .B0(_181_),
    .Y(_182_)
  );
  NAND2 _520_ (
    .A(G71),
    .B(_180_),
    .Y(_183_)
  );
  OAI21 _521_ (
    .A0(_180_),
    .A1(_182_),
    .B0(_183_),
    .Y(G494)
  );
  NAND2 _522_ (
    .A(_009_),
    .B(_032_),
    .Y(_184_)
  );
  OAI21 _523_ (
    .A0(_009_),
    .A1(G4),
    .B0(_184_),
    .Y(_185_)
  );
  NAND2 _524_ (
    .A(G72),
    .B(_180_),
    .Y(_186_)
  );
  OAI21 _525_ (
    .A0(_180_),
    .A1(_185_),
    .B0(_186_),
    .Y(G498)
  );
  NAND2 _526_ (
    .A(_009_),
    .B(_033_),
    .Y(_187_)
  );
  OAI21 _527_ (
    .A0(_009_),
    .A1(G5),
    .B0(_187_),
    .Y(_188_)
  );
  NAND2 _528_ (
    .A(G73),
    .B(_180_),
    .Y(_189_)
  );
  OAI21 _529_ (
    .A0(_180_),
    .A1(_188_),
    .B0(_189_),
    .Y(G503)
  );
  NOR2 _530_ (
    .A(_002_),
    .B(_141_),
    .Y(_190_)
  );
  OAI21 _531_ (
    .A0(_002_),
    .A1(_141_),
    .B0(G179),
    .Y(_191_)
  );
  AOI22 _532_ (
    .A0(_075_),
    .A1(_150_),
    .B0(_191_),
    .B1(_074_),
    .Y(_192_)
  );
  NOR2 _533_ (
    .A(_071_),
    .B(_192_),
    .Y(_193_)
  );
  INV _534_ (
    .A(_193_),
    .Y(_194_)
  );
  NOR2 _535_ (
    .A(_019_),
    .B(_194_),
    .Y(_195_)
  );
  NOR2 _536_ (
    .A(G74),
    .B(_193_),
    .Y(_196_)
  );
  NOR2 _537_ (
    .A(_010_),
    .B(_173_),
    .Y(_197_)
  );
  NOR2 _538_ (
    .A(G351),
    .B(G9),
    .Y(_198_)
  );
  NOR2 _539_ (
    .A(_197_),
    .B(_198_),
    .Y(_199_)
  );
  NOR3 _540_ (
    .A(_195_),
    .B(_196_),
    .C(_199_),
    .Y(G526)
  );
  NOR3 _541_ (
    .A(_019_),
    .B(_020_),
    .C(_194_),
    .Y(_200_)
  );
  INV _542_ (
    .A(_200_),
    .Y(_201_)
  );
  NOR2 _543_ (
    .A(G75),
    .B(_195_),
    .Y(_202_)
  );
  NOR3 _544_ (
    .A(_199_),
    .B(_200_),
    .C(_202_),
    .Y(G531)
  );
  NOR2 _545_ (
    .A(_021_),
    .B(_201_),
    .Y(_203_)
  );
  NOR2 _546_ (
    .A(G76),
    .B(_200_),
    .Y(_204_)
  );
  NOR3 _547_ (
    .A(_199_),
    .B(_203_),
    .C(_204_),
    .Y(G536)
  );
  NOR3 _548_ (
    .A(_021_),
    .B(_022_),
    .C(_201_),
    .Y(_205_)
  );
  NOR2 _549_ (
    .A(G77),
    .B(_203_),
    .Y(_206_)
  );
  NOR3 _550_ (
    .A(_199_),
    .B(_205_),
    .C(_206_),
    .Y(G541)
  );
  XNOR2 _551_ (
    .A(G78),
    .B(_205_),
    .Y(_207_)
  );
  NOR2 _552_ (
    .A(_199_),
    .B(_207_),
    .Y(G548)
  );
  OAI21 _553_ (
    .A0(G343),
    .A1(_013_),
    .B0(_173_),
    .Y(_208_)
  );
  NAND2 _554_ (
    .A(G79),
    .B(_208_),
    .Y(_209_)
  );
  OAI21 _555_ (
    .A0(_034_),
    .A1(_208_),
    .B0(_209_),
    .Y(G565)
  );
  NAND2 _556_ (
    .A(G80),
    .B(_208_),
    .Y(_210_)
  );
  OAI21 _557_ (
    .A0(_035_),
    .A1(_208_),
    .B0(_210_),
    .Y(G569)
  );
  NAND2 _558_ (
    .A(G81),
    .B(_208_),
    .Y(_211_)
  );
  OAI21 _559_ (
    .A0(_036_),
    .A1(_208_),
    .B0(_211_),
    .Y(G573)
  );
  NAND2 _560_ (
    .A(G82),
    .B(_208_),
    .Y(_212_)
  );
  OAI21 _561_ (
    .A0(_038_),
    .A1(_208_),
    .B0(_212_),
    .Y(G577)
  );
  NOR2 _562_ (
    .A(G83),
    .B(_193_),
    .Y(_213_)
  );
  NOR2 _563_ (
    .A(_070_),
    .B(_080_),
    .Y(_214_)
  );
  NOR3 _564_ (
    .A(_199_),
    .B(_213_),
    .C(_214_),
    .Y(G590)
  );
  NAND2 _565_ (
    .A(G84),
    .B(_208_),
    .Y(_215_)
  );
  OAI21 _566_ (
    .A0(_012_),
    .A1(_208_),
    .B0(_215_),
    .Y(G608)
  );
  NAND2 _567_ (
    .A(G85),
    .B(_208_),
    .Y(_216_)
  );
  OAI21 _568_ (
    .A0(_011_),
    .A1(_208_),
    .B0(_216_),
    .Y(G613)
  );
  NAND2 _569_ (
    .A(G13),
    .B(G14),
    .Y(_217_)
  );
  INV _570_ (
    .A(_217_),
    .Y(G657)
  );
  NAND2 _571_ (
    .A(G94),
    .B(G11),
    .Y(_218_)
  );
  INV _572_ (
    .A(_218_),
    .Y(_219_)
  );
  OAI21 _573_ (
    .A0(G11),
    .A1(G87),
    .B0(G14),
    .Y(_220_)
  );
  NOR2 _574_ (
    .A(_219_),
    .B(_220_),
    .Y(G663)
  );
  NOR2 _575_ (
    .A(G11),
    .B(G88),
    .Y(_221_)
  );
  OAI21 _576_ (
    .A0(_011_),
    .A1(G87),
    .B0(G14),
    .Y(_222_)
  );
  NOR2 _577_ (
    .A(_221_),
    .B(_222_),
    .Y(G669)
  );
  NOR2 _578_ (
    .A(G11),
    .B(G89),
    .Y(_223_)
  );
  OAI21 _579_ (
    .A0(_011_),
    .A1(G88),
    .B0(G14),
    .Y(_224_)
  );
  NOR2 _580_ (
    .A(_223_),
    .B(_224_),
    .Y(G675)
  );
  NAND2 _581_ (
    .A(G89),
    .B(_168_),
    .Y(_225_)
  );
  NAND2 _582_ (
    .A(G88),
    .B(_146_),
    .Y(_226_)
  );
  NOR3 _583_ (
    .A(G34),
    .B(_023_),
    .C(_141_),
    .Y(_227_)
  );
  OAI21 _584_ (
    .A0(G94),
    .A1(_133_),
    .B0(_010_),
    .Y(_228_)
  );
  NOR2 _585_ (
    .A(_227_),
    .B(_228_),
    .Y(_229_)
  );
  AOI21 _586_ (
    .A0(_225_),
    .A1(_226_),
    .B0(_229_),
    .Y(_230_)
  );
  INV _587_ (
    .A(_230_),
    .Y(G702)
  );
  NAND2 _588_ (
    .A(_010_),
    .B(_034_),
    .Y(_231_)
  );
  NAND2 _589_ (
    .A(_010_),
    .B(G5),
    .Y(_232_)
  );
  OAI21 _590_ (
    .A0(_010_),
    .A1(_072_),
    .B0(_232_),
    .Y(_233_)
  );
  AOI22 _591_ (
    .A0(G46),
    .A1(_107_),
    .B0(_114_),
    .B1(_024_),
    .Y(_234_)
  );
  AOI21 _592_ (
    .A0(_112_),
    .A1(_120_),
    .B0(_234_),
    .Y(_235_)
  );
  NOR3 _593_ (
    .A(_121_),
    .B(_124_),
    .C(_235_),
    .Y(_236_)
  );
  OAI21 _594_ (
    .A0(_233_),
    .A1(_236_),
    .B0(_080_),
    .Y(_237_)
  );
  AOI22 _595_ (
    .A0(_074_),
    .A1(_231_),
    .B0(_237_),
    .B1(_126_),
    .Y(_238_)
  );
  OAI22 _596_ (
    .A0(G35),
    .A1(G351),
    .B0(_099_),
    .B1(_167_),
    .Y(_239_)
  );
  AOI21 _597_ (
    .A0(_074_),
    .A1(_231_),
    .B0(_239_),
    .Y(_240_)
  );
  NOR2 _598_ (
    .A(_013_),
    .B(_238_),
    .Y(_241_)
  );
  NAND2 _599_ (
    .A(_240_),
    .B(_241_),
    .Y(_242_)
  );
  INV _600_ (
    .A(_242_),
    .Y(G705)
  );
  NAND2 _601_ (
    .A(G11),
    .B(G89),
    .Y(_243_)
  );
  INV _602_ (
    .A(_243_),
    .Y(_244_)
  );
  OAI21 _603_ (
    .A0(G94),
    .A1(G11),
    .B0(G14),
    .Y(_245_)
  );
  NOR2 _604_ (
    .A(_244_),
    .B(_245_),
    .Y(G707)
  );
  AOI21 _605_ (
    .A0(G14),
    .A1(G83),
    .B0(_104_),
    .Y(_246_)
  );
  NOR3 _606_ (
    .A(_075_),
    .B(_079_),
    .C(_246_),
    .Y(G713)
  );
  NOR2 _607_ (
    .A(G351),
    .B(_174_),
    .Y(G727)
  );
  OAI21 _608_ (
    .A0(G351),
    .A1(G10),
    .B0(G86),
    .Y(_247_)
  );
  NAND2 _609_ (
    .A(G657),
    .B(_247_),
    .Y(G682)
  );
  AOI22 _610_ (
    .A0(_010_),
    .A1(G10),
    .B0(_053_),
    .B1(G13),
    .Y(_248_)
  );
  OAI21 _611_ (
    .A0(G343),
    .A1(G10),
    .B0(_248_),
    .Y(_249_)
  );
  NAND2 _612_ (
    .A(G657),
    .B(_249_),
    .Y(G687)
  );
  AOI22 _613_ (
    .A0(_007_),
    .A1(G10),
    .B0(_053_),
    .B1(G13),
    .Y(_250_)
  );
  OAI21 _614_ (
    .A0(G179),
    .A1(G10),
    .B0(_250_),
    .Y(_251_)
  );
  NAND2 _615_ (
    .A(G657),
    .B(_251_),
    .Y(G693)
  );
  NOR2 _616_ (
    .A(_000_),
    .B(_126_),
    .Y(_252_)
  );
  NOR2 _617_ (
    .A(_128_),
    .B(_252_),
    .Y(_253_)
  );
  NOR2 _618_ (
    .A(_013_),
    .B(_253_),
    .Y(G109)
  );
  OAI21 _619_ (
    .A0(G25),
    .A1(_128_),
    .B0(G14),
    .Y(_254_)
  );
  NOR2 _620_ (
    .A(_129_),
    .B(_254_),
    .Y(G113)
  );
  NOR2 _621_ (
    .A(G26),
    .B(_129_),
    .Y(_255_)
  );
  NAND2 _622_ (
    .A(G14),
    .B(_131_),
    .Y(_256_)
  );
  NOR2 _623_ (
    .A(_255_),
    .B(_256_),
    .Y(G118)
  );
  XOR2 _624_ (
    .A(G27),
    .B(_131_),
    .Y(_257_)
  );
  NOR2 _625_ (
    .A(_013_),
    .B(_257_),
    .Y(G125)
  );
  NOR2 _626_ (
    .A(G28),
    .B(_132_),
    .Y(_258_)
  );
  NAND2 _627_ (
    .A(G14),
    .B(_133_),
    .Y(_259_)
  );
  NOR2 _628_ (
    .A(_258_),
    .B(_259_),
    .Y(G129)
  );
  NOR2 _629_ (
    .A(_001_),
    .B(_134_),
    .Y(_260_)
  );
  NOR2 _630_ (
    .A(_136_),
    .B(_260_),
    .Y(_261_)
  );
  NOR2 _631_ (
    .A(_013_),
    .B(_261_),
    .Y(G140)
  );
  OAI21 _632_ (
    .A0(G30),
    .A1(_136_),
    .B0(G14),
    .Y(_262_)
  );
  NOR2 _633_ (
    .A(_137_),
    .B(_262_),
    .Y(G144)
  );
  OAI21 _634_ (
    .A0(G31),
    .A1(_137_),
    .B0(G14),
    .Y(_263_)
  );
  NOR2 _635_ (
    .A(_139_),
    .B(_263_),
    .Y(G149)
  );
  NOR2 _636_ (
    .A(G32),
    .B(_139_),
    .Y(_264_)
  );
  NAND2 _637_ (
    .A(G14),
    .B(_140_),
    .Y(_265_)
  );
  NOR2 _638_ (
    .A(_264_),
    .B(_265_),
    .Y(G154)
  );
  NAND2 _639_ (
    .A(_046_),
    .B(_140_),
    .Y(_266_)
  );
  AOI21 _640_ (
    .A0(G14),
    .A1(_141_),
    .B0(_266_),
    .Y(_267_)
  );
  INV _641_ (
    .A(_267_),
    .Y(G159)
  );
  OAI21 _642_ (
    .A0(G34),
    .A1(_142_),
    .B0(G14),
    .Y(_268_)
  );
  NOR2 _643_ (
    .A(_190_),
    .B(_268_),
    .Y(G166)
  );
  NOR2 _644_ (
    .A(G35),
    .B(_013_),
    .Y(G175)
  );
  NOR2 _645_ (
    .A(_003_),
    .B(_148_),
    .Y(_269_)
  );
  NOR2 _646_ (
    .A(_149_),
    .B(_269_),
    .Y(_270_)
  );
  NOR2 _647_ (
    .A(_013_),
    .B(_270_),
    .Y(G189)
  );
  OAI21 _648_ (
    .A0(G37),
    .A1(_149_),
    .B0(G14),
    .Y(_271_)
  );
  NOR2 _649_ (
    .A(_150_),
    .B(_271_),
    .Y(G193)
  );
  OAI21 _650_ (
    .A0(G38),
    .A1(_150_),
    .B0(G14),
    .Y(_272_)
  );
  NOR2 _651_ (
    .A(_152_),
    .B(_272_),
    .Y(G198)
  );
  XNOR2 _652_ (
    .A(G39),
    .B(_143_),
    .Y(_273_)
  );
  NOR2 _653_ (
    .A(_013_),
    .B(_273_),
    .Y(G208)
  );
  XNOR2 _654_ (
    .A(_006_),
    .B(_144_),
    .Y(_274_)
  );
  NOR2 _655_ (
    .A(_013_),
    .B(_274_),
    .Y(G214)
  );
  NAND2 _656_ (
    .A(_048_),
    .B(_145_),
    .Y(_275_)
  );
  NAND2 _657_ (
    .A(G14),
    .B(_275_),
    .Y(_276_)
  );
  NOR2 _658_ (
    .A(_146_),
    .B(_276_),
    .Y(G218)
  );
  NOR2 _659_ (
    .A(G351),
    .B(G7),
    .Y(_277_)
  );
  NOR2 _660_ (
    .A(_197_),
    .B(_277_),
    .Y(_278_)
  );
  NOR2 _661_ (
    .A(_056_),
    .B(G328),
    .Y(_279_)
  );
  NOR3 _662_ (
    .A(_024_),
    .B(_056_),
    .C(G328),
    .Y(_280_)
  );
  NOR2 _663_ (
    .A(G42),
    .B(_279_),
    .Y(_281_)
  );
  NOR3 _664_ (
    .A(_278_),
    .B(_280_),
    .C(_281_),
    .Y(G237)
  );
  NAND2 _665_ (
    .A(G43),
    .B(_280_),
    .Y(_282_)
  );
  XNOR2 _666_ (
    .A(G43),
    .B(_280_),
    .Y(_283_)
  );
  NOR2 _667_ (
    .A(_278_),
    .B(_283_),
    .Y(G242)
  );
  NOR2 _668_ (
    .A(_025_),
    .B(_282_),
    .Y(_284_)
  );
  XNOR2 _669_ (
    .A(_025_),
    .B(_282_),
    .Y(_285_)
  );
  NOR2 _670_ (
    .A(_278_),
    .B(_285_),
    .Y(G247)
  );
  NAND2 _671_ (
    .A(G45),
    .B(_284_),
    .Y(_286_)
  );
  XNOR2 _672_ (
    .A(G45),
    .B(_284_),
    .Y(_287_)
  );
  NOR2 _673_ (
    .A(_278_),
    .B(_287_),
    .Y(G252)
  );
  XOR2 _674_ (
    .A(G46),
    .B(_286_),
    .Y(_288_)
  );
  NOR2 _675_ (
    .A(_278_),
    .B(_288_),
    .Y(G260)
  );
  NAND2 _676_ (
    .A(G54),
    .B(_143_),
    .Y(_289_)
  );
  INV _677_ (
    .A(_289_),
    .Y(_290_)
  );
  NAND2 _678_ (
    .A(G56),
    .B(_290_),
    .Y(_291_)
  );
  INV _679_ (
    .A(_291_),
    .Y(_292_)
  );
  NOR2 _680_ (
    .A(_007_),
    .B(_292_),
    .Y(_293_)
  );
  NAND2 _681_ (
    .A(G343),
    .B(_291_),
    .Y(_294_)
  );
  NOR2 _682_ (
    .A(G12),
    .B(_293_),
    .Y(_295_)
  );
  OAI21 _683_ (
    .A0(G47),
    .A1(_294_),
    .B0(G14),
    .Y(_296_)
  );
  NOR2 _684_ (
    .A(_295_),
    .B(_296_),
    .Y(G303)
  );
  NOR2 _685_ (
    .A(G47),
    .B(_293_),
    .Y(_297_)
  );
  OAI21 _686_ (
    .A0(G48),
    .A1(_294_),
    .B0(G14),
    .Y(_298_)
  );
  NOR2 _687_ (
    .A(_297_),
    .B(_298_),
    .Y(G309)
  );
  NOR2 _688_ (
    .A(G48),
    .B(_293_),
    .Y(_299_)
  );
  OAI21 _689_ (
    .A0(G49),
    .A1(_294_),
    .B0(G14),
    .Y(_300_)
  );
  NOR2 _690_ (
    .A(_299_),
    .B(_300_),
    .Y(G315)
  );
  NOR2 _691_ (
    .A(G49),
    .B(_293_),
    .Y(_301_)
  );
  OAI21 _692_ (
    .A0(G50),
    .A1(_294_),
    .B0(G14),
    .Y(_302_)
  );
  NOR2 _693_ (
    .A(_301_),
    .B(_302_),
    .Y(G321)
  );
  NAND2 _694_ (
    .A(G14),
    .B(_163_),
    .Y(_303_)
  );
  NOR2 _695_ (
    .A(G51),
    .B(_161_),
    .Y(_304_)
  );
  NOR2 _696_ (
    .A(_049_),
    .B(_162_),
    .Y(_305_)
  );
  NOR3 _697_ (
    .A(_303_),
    .B(_304_),
    .C(_305_),
    .Y(G360)
  );
  NAND2 _698_ (
    .A(G52),
    .B(_305_),
    .Y(_306_)
  );
  INV _699_ (
    .A(_306_),
    .Y(_307_)
  );
  NOR2 _700_ (
    .A(G52),
    .B(_305_),
    .Y(_308_)
  );
  NOR3 _701_ (
    .A(_303_),
    .B(_307_),
    .C(_308_),
    .Y(G365)
  );
  NOR2 _702_ (
    .A(G53),
    .B(_307_),
    .Y(_309_)
  );
  NOR2 _703_ (
    .A(_303_),
    .B(_309_),
    .Y(G373)
  );
  OAI21 _704_ (
    .A0(G54),
    .A1(_143_),
    .B0(G14),
    .Y(_310_)
  );
  NOR2 _705_ (
    .A(_290_),
    .B(_310_),
    .Y(G379)
  );
  NAND2 _706_ (
    .A(G14),
    .B(_291_),
    .Y(_311_)
  );
  NOR2 _707_ (
    .A(_050_),
    .B(_289_),
    .Y(_312_)
  );
  NOR2 _708_ (
    .A(G55),
    .B(_290_),
    .Y(_313_)
  );
  NOR3 _709_ (
    .A(_311_),
    .B(_312_),
    .C(_313_),
    .Y(G384)
  );
  NOR2 _710_ (
    .A(G56),
    .B(_312_),
    .Y(_314_)
  );
  NOR2 _711_ (
    .A(_311_),
    .B(_314_),
    .Y(G392)
  );
  NAND2 _712_ (
    .A(G14),
    .B(_158_),
    .Y(_315_)
  );
  NOR2 _713_ (
    .A(_051_),
    .B(_156_),
    .Y(_316_)
  );
  NOR3 _714_ (
    .A(G57),
    .B(_153_),
    .C(_155_),
    .Y(_317_)
  );
  NOR3 _715_ (
    .A(_315_),
    .B(_316_),
    .C(_317_),
    .Y(G397)
  );
  NOR2 _716_ (
    .A(G58),
    .B(_316_),
    .Y(_318_)
  );
  NOR2 _717_ (
    .A(_315_),
    .B(_318_),
    .Y(G405)
  );
  OAI21 _718_ (
    .A0(G59),
    .A1(_157_),
    .B0(G14),
    .Y(_319_)
  );
  NOR2 _719_ (
    .A(_159_),
    .B(_319_),
    .Y(G408)
  );
  NAND2 _720_ (
    .A(G14),
    .B(_165_),
    .Y(_320_)
  );
  NOR2 _721_ (
    .A(_014_),
    .B(_163_),
    .Y(_321_)
  );
  NOR2 _722_ (
    .A(G60),
    .B(_164_),
    .Y(_322_)
  );
  NOR3 _723_ (
    .A(_320_),
    .B(_321_),
    .C(_322_),
    .Y(G416)
  );
  NOR2 _724_ (
    .A(G61),
    .B(_321_),
    .Y(_323_)
  );
  NOR2 _725_ (
    .A(_320_),
    .B(_323_),
    .Y(G424)
  );
  NAND2 _726_ (
    .A(_026_),
    .B(_165_),
    .Y(_324_)
  );
  NAND2 _727_ (
    .A(G14),
    .B(_324_),
    .Y(_325_)
  );
  NOR2 _728_ (
    .A(_168_),
    .B(_325_),
    .Y(G427)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:70.7-70.27" *)
  dff DFF_0 (
    .CK(CK),
    .D(G332),
    .Q(G22)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:71.7-71.27" *)
  dff DFF_1 (
    .CK(CK),
    .D(G328),
    .Q(G23)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:80.7-80.26" *)
  dff DFF_10 (
    .CK(CK),
    .D(G154),
    .Q(G32)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:81.7-81.26" *)
  dff DFF_11 (
    .CK(CK),
    .D(G159),
    .Q(G33)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:82.7-82.26" *)
  dff DFF_12 (
    .CK(CK),
    .D(G166),
    .Q(G34)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:83.7-83.26" *)
  dff DFF_13 (
    .CK(CK),
    .D(G175),
    .Q(G35)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:84.7-84.26" *)
  dff DFF_14 (
    .CK(CK),
    .D(G189),
    .Q(G36)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:85.7-85.26" *)
  dff DFF_15 (
    .CK(CK),
    .D(G193),
    .Q(G37)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:86.7-86.26" *)
  dff DFF_16 (
    .CK(CK),
    .D(G198),
    .Q(G38)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:87.7-87.26" *)
  dff DFF_17 (
    .CK(CK),
    .D(G208),
    .Q(G39)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:88.7-88.26" *)
  dff DFF_18 (
    .CK(CK),
    .D(G214),
    .Q(G40)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:89.7-89.26" *)
  dff DFF_19 (
    .CK(CK),
    .D(G218),
    .Q(G41)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:72.7-72.25" *)
  dff DFF_2 (
    .CK(CK),
    .D(G109),
    .Q(G24)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:90.7-90.26" *)
  dff DFF_20 (
    .CK(CK),
    .D(G237),
    .Q(G42)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:91.7-91.26" *)
  dff DFF_21 (
    .CK(CK),
    .D(G242),
    .Q(G43)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:92.7-92.26" *)
  dff DFF_22 (
    .CK(CK),
    .D(G247),
    .Q(G44)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:93.7-93.26" *)
  dff DFF_23 (
    .CK(CK),
    .D(G252),
    .Q(G45)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:94.7-94.26" *)
  dff DFF_24 (
    .CK(CK),
    .D(G260),
    .Q(G46)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:95.7-95.26" *)
  dff DFF_25 (
    .CK(CK),
    .D(G303),
    .Q(G47)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:96.7-96.26" *)
  dff DFF_26 (
    .CK(CK),
    .D(G309),
    .Q(G48)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:97.7-97.26" *)
  dff DFF_27 (
    .CK(CK),
    .D(G315),
    .Q(G49)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:98.7-98.26" *)
  dff DFF_28 (
    .CK(CK),
    .D(G321),
    .Q(G50)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:99.7-99.26" *)
  dff DFF_29 (
    .CK(CK),
    .D(G360),
    .Q(G51)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:73.7-73.25" *)
  dff DFF_3 (
    .CK(CK),
    .D(G113),
    .Q(G25)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:100.7-100.26" *)
  dff DFF_30 (
    .CK(CK),
    .D(G365),
    .Q(G52)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:101.7-101.26" *)
  dff DFF_31 (
    .CK(CK),
    .D(G373),
    .Q(G53)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:102.7-102.26" *)
  dff DFF_32 (
    .CK(CK),
    .D(G379),
    .Q(G54)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:103.7-103.26" *)
  dff DFF_33 (
    .CK(CK),
    .D(G384),
    .Q(G55)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:104.7-104.26" *)
  dff DFF_34 (
    .CK(CK),
    .D(G392),
    .Q(G56)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:105.7-105.26" *)
  dff DFF_35 (
    .CK(CK),
    .D(G397),
    .Q(G57)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:106.7-106.26" *)
  dff DFF_36 (
    .CK(CK),
    .D(G405),
    .Q(G58)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:107.7-107.26" *)
  dff DFF_37 (
    .CK(CK),
    .D(G408),
    .Q(G59)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:108.7-108.26" *)
  dff DFF_38 (
    .CK(CK),
    .D(G416),
    .Q(G60)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:109.7-109.26" *)
  dff DFF_39 (
    .CK(CK),
    .D(G424),
    .Q(G61)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:74.7-74.25" *)
  dff DFF_4 (
    .CK(CK),
    .D(G118),
    .Q(G26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:110.7-110.26" *)
  dff DFF_40 (
    .CK(CK),
    .D(G427),
    .Q(G62)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:111.7-111.26" *)
  dff DFF_41 (
    .CK(CK),
    .D(G438),
    .Q(G504)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:112.7-112.26" *)
  dff DFF_42 (
    .CK(CK),
    .D(G441),
    .Q(G64)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:113.7-113.26" *)
  dff DFF_43 (
    .CK(CK),
    .D(G447),
    .Q(G65)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:114.7-114.26" *)
  dff DFF_44 (
    .CK(CK),
    .D(G451),
    .Q(G66)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:115.7-115.26" *)
  dff DFF_45 (
    .CK(CK),
    .D(G459),
    .Q(G67)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:116.7-116.26" *)
  dff DFF_46 (
    .CK(CK),
    .D(G464),
    .Q(G68)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:117.7-117.26" *)
  dff DFF_47 (
    .CK(CK),
    .D(G469),
    .Q(G69)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:118.7-118.26" *)
  dff DFF_48 (
    .CK(CK),
    .D(G477),
    .Q(G70)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:119.7-119.26" *)
  dff DFF_49 (
    .CK(CK),
    .D(G494),
    .Q(G71)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:75.7-75.25" *)
  dff DFF_5 (
    .CK(CK),
    .D(G125),
    .Q(G27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:120.7-120.26" *)
  dff DFF_50 (
    .CK(CK),
    .D(G498),
    .Q(G72)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:121.7-121.26" *)
  dff DFF_51 (
    .CK(CK),
    .D(G503),
    .Q(G73)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:122.7-122.26" *)
  dff DFF_52 (
    .CK(CK),
    .D(G526),
    .Q(G74)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:123.7-123.26" *)
  dff DFF_53 (
    .CK(CK),
    .D(G531),
    .Q(G75)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:124.7-124.26" *)
  dff DFF_54 (
    .CK(CK),
    .D(G536),
    .Q(G76)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:125.7-125.26" *)
  dff DFF_55 (
    .CK(CK),
    .D(G541),
    .Q(G77)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:126.7-126.26" *)
  dff DFF_56 (
    .CK(CK),
    .D(G548),
    .Q(G78)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:127.7-127.26" *)
  dff DFF_57 (
    .CK(CK),
    .D(G565),
    .Q(G79)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:128.7-128.26" *)
  dff DFF_58 (
    .CK(CK),
    .D(G569),
    .Q(G80)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:129.7-129.26" *)
  dff DFF_59 (
    .CK(CK),
    .D(G573),
    .Q(G81)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:76.7-76.25" *)
  dff DFF_6 (
    .CK(CK),
    .D(G129),
    .Q(G28)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:130.7-130.26" *)
  dff DFF_60 (
    .CK(CK),
    .D(G577),
    .Q(G82)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:131.7-131.26" *)
  dff DFF_61 (
    .CK(CK),
    .D(G590),
    .Q(G83)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:132.7-132.26" *)
  dff DFF_62 (
    .CK(CK),
    .D(G608),
    .Q(G84)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:133.7-133.26" *)
  dff DFF_63 (
    .CK(CK),
    .D(G613),
    .Q(G85)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:134.7-134.26" *)
  dff DFF_64 (
    .CK(CK),
    .D(G657),
    .Q(G86)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:135.7-135.26" *)
  dff DFF_65 (
    .CK(CK),
    .D(G663),
    .Q(G87)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:136.7-136.26" *)
  dff DFF_66 (
    .CK(CK),
    .D(G669),
    .Q(G88)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:137.7-137.26" *)
  dff DFF_67 (
    .CK(CK),
    .D(G675),
    .Q(G89)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:138.7-138.26" *)
  dff DFF_68 (
    .CK(CK),
    .D(G682),
    .Q(G351)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:139.7-139.26" *)
  dff DFF_69 (
    .CK(CK),
    .D(G687),
    .Q(G343)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:77.7-77.25" *)
  dff DFF_7 (
    .CK(CK),
    .D(G140),
    .Q(G29)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:140.7-140.26" *)
  dff DFF_70 (
    .CK(CK),
    .D(G693),
    .Q(G179)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:141.7-141.26" *)
  dff DFF_71 (
    .CK(CK),
    .D(G705),
    .Q(G93)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:142.7-142.26" *)
  dff DFF_72 (
    .CK(CK),
    .D(G707),
    .Q(G94)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:143.7-143.26" *)
  dff DFF_73 (
    .CK(CK),
    .D(G713),
    .Q(G95)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:78.7-78.25" *)
  dff DFF_8 (
    .CK(CK),
    .D(G144),
    .Q(G30)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s1423.v:79.7-79.25" *)
  dff DFF_9 (
    .CK(CK),
    .D(G149),
    .Q(G31)
  );
  assign G302 = G14;
  assign G308 = G14;
  assign G314 = G14;
  assign G320 = G14;
  assign G328BF = G328;
  assign G332BF = G332;
  assign G347 = G343;
  assign G407 = G14;
  assign G426 = G14;
  assign G437 = G14;
  assign G440 = G14;
  assign G446 = G14;
  assign G450 = G14;
  assign G217 = G14;
  assign G213 = G14;
  assign G486 = G14;
  assign G507 = G504;
  assign G510 = G504;
  assign G207 = G14;
  assign G108 = G14;
  assign G112 = G14;
  assign G197 = G14;
  assign G117 = G14;
  assign G617 = G351;
  assign G620 = G351;
  assign G623 = G351;
  assign G124 = G14;
  assign G626 = G351;
  assign G629 = G351;
  assign G63 = G504;
  assign G128 = G14;
  assign G632 = G351;
  assign G635 = G351;
  assign G638 = G351;
  assign G641 = G351;
  assign G644 = G351;
  assign G139 = G14;
  assign G143 = G14;
  assign G656 = G14;
  assign G659 = G13;
  assign G148 = G14;
  assign G662 = G14;
  assign G668 = G14;
  assign G192 = G14;
  assign G153 = G14;
  assign G674 = G14;
  assign G678 = G11;
  assign G158 = G14;
  assign G165 = G14;
  assign G696 = G10;
  assign G188 = G14;
  assign G701 = G701BF;
  assign G704 = G14;
  assign G706 = G14;
  assign G174 = G14;
  assign G711 = G14;
  assign G714 = G15;
  assign G715 = G6;
  assign G716 = G7;
  assign G717 = G8;
  assign G718 = G9;
  assign G719 = G12;
  assign G720 = G0;
  assign G721 = G1;
  assign G722 = G2;
  assign G723 = G3;
  assign G724 = G4;
  assign G725 = G5;
  assign G726 = G93;
  assign G728 = G16;
  assign G729 = G95;
  assign G90 = G351;
  assign G91 = G343;
  assign G92 = G179;
  assign II1211 = G15;
endmodule
