/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* src = "/content/ISCAS89/s420.v:7.1-13.10" *)
module dff(CK, Q, D);
  (* src = "/content/ISCAS89/s420.v:8.7-8.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s420.v:8.10-8.11" *)
  input D;
  wire D;
  (* src = "/content/ISCAS89/s420.v:9.8-9.9" *)
  output Q;
  wire Q;
  (* src = "/content/ISCAS89/s420.v:11.1-12.10" *)
  DFFR _0_ (
    .C(CK),
    .D(D),
    .Q(Q),
    .R(1'h0)
  );
endmodule

(* top =  1  *)
(* src = "/content/ISCAS89/s420.v:15.1-276.10" *)
module s420(CK, C_0, C_1, C_10, C_11, C_12, C_13, C_14, C_15, C_16, C_2, C_3, C_4, C_5, C_6, C_7, C_8, C_9, P_0, Z);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "/content/ISCAS89/s420.v:17.7-17.9" *)
  input CK;
  wire CK;
  (* src = "/content/ISCAS89/s420.v:18.19-18.22" *)
  input C_0;
  wire C_0;
  (* src = "/content/ISCAS89/s420.v:18.15-18.18" *)
  input C_1;
  wire C_1;
  (* src = "/content/ISCAS89/s420.v:17.44-17.48" *)
  input C_10;
  wire C_10;
  (* src = "/content/ISCAS89/s420.v:17.39-17.43" *)
  input C_11;
  wire C_11;
  (* src = "/content/ISCAS89/s420.v:17.34-17.38" *)
  input C_12;
  wire C_12;
  (* src = "/content/ISCAS89/s420.v:17.29-17.33" *)
  input C_13;
  wire C_13;
  (* src = "/content/ISCAS89/s420.v:17.24-17.28" *)
  input C_14;
  wire C_14;
  (* src = "/content/ISCAS89/s420.v:17.19-17.23" *)
  input C_15;
  wire C_15;
  (* src = "/content/ISCAS89/s420.v:17.14-17.18" *)
  input C_16;
  wire C_16;
  (* src = "/content/ISCAS89/s420.v:18.11-18.14" *)
  input C_2;
  wire C_2;
  (* src = "/content/ISCAS89/s420.v:18.7-18.10" *)
  input C_3;
  wire C_3;
  (* src = "/content/ISCAS89/s420.v:18.3-18.6" *)
  input C_4;
  wire C_4;
  (* src = "/content/ISCAS89/s420.v:17.65-17.68" *)
  input C_5;
  wire C_5;
  (* src = "/content/ISCAS89/s420.v:17.61-17.64" *)
  input C_6;
  wire C_6;
  (* src = "/content/ISCAS89/s420.v:17.57-17.60" *)
  input C_7;
  wire C_7;
  (* src = "/content/ISCAS89/s420.v:17.53-17.56" *)
  input C_8;
  wire C_8;
  (* src = "/content/ISCAS89/s420.v:17.49-17.52" *)
  input C_9;
  wire C_9;
  (* src = "/content/ISCAS89/s420.v:21.44-21.48" *)
  wire I110;
  (* src = "/content/ISCAS89/s420.v:21.53-21.57" *)
  wire I111;
  (* src = "/content/ISCAS89/s420.v:21.62-21.66" *)
  wire I112;
  (* src = "/content/ISCAS89/s420.v:21.71-21.75" *)
  wire I113;
  (* src = "/content/ISCAS89/s420.v:21.12-21.15" *)
  wire I12;
  (* src = "/content/ISCAS89/s420.v:21.20-21.23" *)
  wire I13;
  (* src = "/content/ISCAS89/s420.v:21.28-21.31" *)
  wire I14;
  (* src = "/content/ISCAS89/s420.v:21.36-21.39" *)
  wire I15;
  (* src = "/content/ISCAS89/s420.v:22.10-22.14" *)
  wire I208;
  (* src = "/content/ISCAS89/s420.v:22.20-22.24" *)
  wire I209;
  (* src = "/content/ISCAS89/s420.v:22.30-22.34" *)
  wire I210;
  (* src = "/content/ISCAS89/s420.v:22.39-22.43" *)
  wire I211;
  (* src = "/content/ISCAS89/s420.v:22.49-22.53" *)
  wire I306;
  (* src = "/content/ISCAS89/s420.v:22.59-22.63" *)
  wire I307;
  (* src = "/content/ISCAS89/s420.v:22.69-22.73" *)
  wire I308;
  (* src = "/content/ISCAS89/s420.v:23.5-23.9" *)
  wire I309;
  (* src = "/content/ISCAS89/s420.v:17.10-17.13" *)
  input P_0;
  wire P_0;
  (* src = "/content/ISCAS89/s420.v:21.32-21.35" *)
  wire X_1;
  (* src = "/content/ISCAS89/s420.v:22.25-22.29" *)
  wire X_10;
  (* src = "/content/ISCAS89/s420.v:22.15-22.19" *)
  wire X_11;
  (* src = "/content/ISCAS89/s420.v:22.5-22.9" *)
  wire X_12;
  (* src = "/content/ISCAS89/s420.v:22.74-22.78" *)
  wire X_13;
  (* src = "/content/ISCAS89/s420.v:22.64-22.68" *)
  wire X_14;
  (* src = "/content/ISCAS89/s420.v:22.54-22.58" *)
  wire X_15;
  (* src = "/content/ISCAS89/s420.v:22.44-22.48" *)
  wire X_16;
  (* src = "/content/ISCAS89/s420.v:21.24-21.27" *)
  wire X_2;
  (* src = "/content/ISCAS89/s420.v:21.16-21.19" *)
  wire X_3;
  (* src = "/content/ISCAS89/s420.v:21.8-21.11" *)
  wire X_4;
  (* src = "/content/ISCAS89/s420.v:21.67-21.70" *)
  wire X_5;
  (* src = "/content/ISCAS89/s420.v:21.58-21.61" *)
  wire X_6;
  (* src = "/content/ISCAS89/s420.v:21.49-21.52" *)
  wire X_7;
  (* src = "/content/ISCAS89/s420.v:21.40-21.43" *)
  wire X_8;
  (* src = "/content/ISCAS89/s420.v:22.35-22.38" *)
  wire X_9;
  (* src = "/content/ISCAS89/s420.v:19.8-19.9" *)
  output Z;
  wire Z;
  INV _072_ (
    .A(X_1),
    .Y(_040_)
  );
  INV _073_ (
    .A(X_3),
    .Y(_041_)
  );
  INV _074_ (
    .A(X_4),
    .Y(_042_)
  );
  INV _075_ (
    .A(X_6),
    .Y(_043_)
  );
  INV _076_ (
    .A(X_7),
    .Y(_044_)
  );
  INV _077_ (
    .A(X_8),
    .Y(_045_)
  );
  INV _078_ (
    .A(X_9),
    .Y(_046_)
  );
  INV _079_ (
    .A(X_11),
    .Y(_047_)
  );
  INV _080_ (
    .A(P_0),
    .Y(_048_)
  );
  INV _081_ (
    .A(X_14),
    .Y(_049_)
  );
  INV _082_ (
    .A(X_15),
    .Y(_050_)
  );
  NAND2 _083_ (
    .A(X_1),
    .B(P_0),
    .Y(_051_)
  );
  AOI21 _084_ (
    .A0(X_1),
    .A1(X_2),
    .B0(P_0),
    .Y(_052_)
  );
  NOR2 _085_ (
    .A(_041_),
    .B(_052_),
    .Y(_053_)
  );
  NOR3 _086_ (
    .A(_041_),
    .B(_042_),
    .C(_052_),
    .Y(_054_)
  );
  NOR2 _087_ (
    .A(X_4),
    .B(_053_),
    .Y(_055_)
  );
  NOR2 _088_ (
    .A(_054_),
    .B(_055_),
    .Y(I12)
  );
  NAND2 _089_ (
    .A(X_5),
    .B(_054_),
    .Y(_056_)
  );
  AOI21 _090_ (
    .A0(X_5),
    .A1(X_6),
    .B0(_054_),
    .Y(_057_)
  );
  NOR2 _091_ (
    .A(_044_),
    .B(_057_),
    .Y(_058_)
  );
  NOR3 _092_ (
    .A(_044_),
    .B(_045_),
    .C(_057_),
    .Y(_059_)
  );
  NOR2 _093_ (
    .A(X_8),
    .B(_058_),
    .Y(_060_)
  );
  NOR2 _094_ (
    .A(_059_),
    .B(_060_),
    .Y(I110)
  );
  NAND2 _095_ (
    .A(X_9),
    .B(_059_),
    .Y(_061_)
  );
  AOI21 _096_ (
    .A0(X_9),
    .A1(X_10),
    .B0(_059_),
    .Y(_062_)
  );
  NOR2 _097_ (
    .A(_047_),
    .B(_062_),
    .Y(_063_)
  );
  NAND2 _098_ (
    .A(X_12),
    .B(_063_),
    .Y(_064_)
  );
  XOR2 _099_ (
    .A(X_12),
    .B(_063_),
    .Y(I208)
  );
  AOI21 _100_ (
    .A0(X_12),
    .A1(X_13),
    .B0(_063_),
    .Y(_065_)
  );
  NOR2 _101_ (
    .A(_049_),
    .B(_065_),
    .Y(_066_)
  );
  NOR3 _102_ (
    .A(_049_),
    .B(_050_),
    .C(_065_),
    .Y(_067_)
  );
  XOR2 _103_ (
    .A(X_16),
    .B(_067_),
    .Y(I306)
  );
  XNOR2 _104_ (
    .A(_050_),
    .B(_066_),
    .Y(I307)
  );
  XNOR2 _105_ (
    .A(X_2),
    .B(_051_),
    .Y(I14)
  );
  XNOR2 _106_ (
    .A(X_6),
    .B(_056_),
    .Y(I112)
  );
  XNOR2 _107_ (
    .A(X_10),
    .B(_061_),
    .Y(I210)
  );
  XNOR2 _108_ (
    .A(X_14),
    .B(_065_),
    .Y(I308)
  );
  XNOR2 _109_ (
    .A(X_3),
    .B(_052_),
    .Y(I13)
  );
  XOR2 _110_ (
    .A(X_1),
    .B(P_0),
    .Y(I15)
  );
  XNOR2 _111_ (
    .A(X_7),
    .B(_057_),
    .Y(I111)
  );
  XOR2 _112_ (
    .A(X_5),
    .B(_054_),
    .Y(I113)
  );
  XNOR2 _113_ (
    .A(X_11),
    .B(_062_),
    .Y(I209)
  );
  XNOR2 _114_ (
    .A(_046_),
    .B(_059_),
    .Y(I211)
  );
  XNOR2 _115_ (
    .A(X_13),
    .B(_064_),
    .Y(I309)
  );
  NAND2 _116_ (
    .A(X_12),
    .B(C_12),
    .Y(_068_)
  );
  NAND2 _117_ (
    .A(_047_),
    .B(_068_),
    .Y(_069_)
  );
  OAI21 _118_ (
    .A0(_047_),
    .A1(C_11),
    .B0(_069_),
    .Y(_070_)
  );
  NOR2 _119_ (
    .A(X_10),
    .B(_070_),
    .Y(_071_)
  );
  NAND2 _120_ (
    .A(X_10),
    .B(C_10),
    .Y(_000_)
  );
  INV _121_ (
    .A(_000_),
    .Y(_001_)
  );
  NOR3 _122_ (
    .A(X_9),
    .B(_071_),
    .C(_001_),
    .Y(_002_)
  );
  NAND2 _123_ (
    .A(_044_),
    .B(_045_),
    .Y(_003_)
  );
  NOR3 _124_ (
    .A(X_5),
    .B(X_6),
    .C(_003_),
    .Y(_004_)
  );
  OAI21 _125_ (
    .A0(_046_),
    .A1(C_9),
    .B0(_004_),
    .Y(_005_)
  );
  NOR2 _126_ (
    .A(_002_),
    .B(_005_),
    .Y(_006_)
  );
  AOI21 _127_ (
    .A0(_044_),
    .A1(X_8),
    .B0(C_8),
    .Y(_007_)
  );
  NAND2 _128_ (
    .A(X_7),
    .B(C_7),
    .Y(_008_)
  );
  AOI21 _129_ (
    .A0(_043_),
    .A1(_007_),
    .B0(_008_),
    .Y(_009_)
  );
  OAI21 _130_ (
    .A0(_043_),
    .A1(C_6),
    .B0(_009_),
    .Y(_010_)
  );
  NAND2 _131_ (
    .A(X_5),
    .B(C_5),
    .Y(_011_)
  );
  OAI21 _132_ (
    .A0(X_5),
    .A1(_010_),
    .B0(_011_),
    .Y(_012_)
  );
  NOR3 _133_ (
    .A(X_2),
    .B(X_3),
    .C(X_4),
    .Y(_013_)
  );
  NAND2 _134_ (
    .A(_040_),
    .B(_013_),
    .Y(_014_)
  );
  OAI21 _135_ (
    .A0(_006_),
    .A1(_012_),
    .B0(P_0),
    .Y(_015_)
  );
  NOR2 _136_ (
    .A(X_3),
    .B(_042_),
    .Y(_016_)
  );
  AOI22 _137_ (
    .A0(X_3),
    .A1(C_3),
    .B0(C_4),
    .B1(_016_),
    .Y(_017_)
  );
  NAND2 _138_ (
    .A(X_2),
    .B(C_2),
    .Y(_018_)
  );
  OAI21 _139_ (
    .A0(X_2),
    .A1(_017_),
    .B0(_018_),
    .Y(_019_)
  );
  AOI21 _140_ (
    .A0(_040_),
    .A1(P_0),
    .B0(_019_),
    .Y(_020_)
  );
  NAND2 _141_ (
    .A(X_1),
    .B(C_1),
    .Y(_021_)
  );
  INV _142_ (
    .A(_021_),
    .Y(_022_)
  );
  OAI21 _143_ (
    .A0(C_0),
    .A1(_022_),
    .B0(P_0),
    .Y(_023_)
  );
  NOR2 _144_ (
    .A(X_10),
    .B(X_11),
    .Y(_024_)
  );
  NOR2 _145_ (
    .A(X_9),
    .B(X_12),
    .Y(_025_)
  );
  AOI21 _146_ (
    .A0(_004_),
    .A1(_024_),
    .B0(_025_),
    .Y(_026_)
  );
  NOR2 _147_ (
    .A(_014_),
    .B(_026_),
    .Y(_027_)
  );
  NOR2 _148_ (
    .A(_048_),
    .B(X_13),
    .Y(_028_)
  );
  NOR3 _149_ (
    .A(_048_),
    .B(X_13),
    .C(X_14),
    .Y(_029_)
  );
  NAND2 _150_ (
    .A(_049_),
    .B(_028_),
    .Y(_030_)
  );
  AOI21 _151_ (
    .A0(X_15),
    .A1(C_15),
    .B0(_029_),
    .Y(_031_)
  );
  AOI21 _152_ (
    .A0(P_0),
    .A1(X_13),
    .B0(C_13),
    .Y(_032_)
  );
  AOI21 _153_ (
    .A0(X_14),
    .A1(C_14),
    .B0(_028_),
    .Y(_033_)
  );
  AOI21 _154_ (
    .A0(_031_),
    .A1(_032_),
    .B0(_033_),
    .Y(_034_)
  );
  AOI21 _155_ (
    .A0(_050_),
    .A1(X_16),
    .B0(C_16),
    .Y(_035_)
  );
  NOR2 _156_ (
    .A(_030_),
    .B(_035_),
    .Y(_036_)
  );
  OAI21 _157_ (
    .A0(_034_),
    .A1(_036_),
    .B0(_027_),
    .Y(_037_)
  );
  AOI21 _158_ (
    .A0(_020_),
    .A1(_023_),
    .B0(_037_),
    .Y(_038_)
  );
  INV _159_ (
    .A(_038_),
    .Y(_039_)
  );
  OAI21 _160_ (
    .A0(_014_),
    .A1(_015_),
    .B0(_039_),
    .Y(Z)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:41.7-41.24" *)
  dff DFF_0 (
    .CK(CK),
    .D(I12),
    .Q(X_4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:42.7-42.24" *)
  dff DFF_1 (
    .CK(CK),
    .D(I13),
    .Q(X_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:51.7-51.27" *)
  dff DFF_10 (
    .CK(CK),
    .D(I210),
    .Q(X_10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:52.7-52.26" *)
  dff DFF_11 (
    .CK(CK),
    .D(I211),
    .Q(X_9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:53.7-53.27" *)
  dff DFF_12 (
    .CK(CK),
    .D(I306),
    .Q(X_16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:54.7-54.27" *)
  dff DFF_13 (
    .CK(CK),
    .D(I307),
    .Q(X_15)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:55.7-55.27" *)
  dff DFF_14 (
    .CK(CK),
    .D(I308),
    .Q(X_14)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:56.7-56.27" *)
  dff DFF_15 (
    .CK(CK),
    .D(I309),
    .Q(X_13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:43.7-43.24" *)
  dff DFF_2 (
    .CK(CK),
    .D(I14),
    .Q(X_2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:44.7-44.24" *)
  dff DFF_3 (
    .CK(CK),
    .D(I15),
    .Q(X_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:45.7-45.25" *)
  dff DFF_4 (
    .CK(CK),
    .D(I110),
    .Q(X_8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:46.7-46.25" *)
  dff DFF_5 (
    .CK(CK),
    .D(I111),
    .Q(X_7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:47.7-47.25" *)
  dff DFF_6 (
    .CK(CK),
    .D(I112),
    .Q(X_6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:48.7-48.25" *)
  dff DFF_7 (
    .CK(CK),
    .D(I113),
    .Q(X_5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:49.7-49.26" *)
  dff DFF_8 (
    .CK(CK),
    .D(I208),
    .Q(X_12)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/content/ISCAS89/s420.v:50.7-50.26" *)
  dff DFF_9 (
    .CK(CK),
    .D(I209),
    .Q(X_11)
  );
endmodule
