/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/content/conda-env=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* top =  1  *)
module \b02.blif (U, LINEA);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input LINEA;
  wire LINEA;
  (* init = 1'h0 *)
  wire STATO_REG_0_;
  (* init = 1'h0 *)
  wire STATO_REG_1_;
  (* init = 1'h0 *)
  wire STATO_REG_2_;
  output U;
  wire U;
  wire U31;
  wire U32;
  wire U33;
  wire U38;
  (* init = 1'h0 *)
  wire U_REG;
  INV _14_ (
    .A(STATO_REG_1_),
    .Y(_13_)
  );
  INV _15_ (
    .A(STATO_REG_2_),
    .Y(_00_)
  );
  INV _16_ (
    .A(STATO_REG_0_),
    .Y(_01_)
  );
  INV _17_ (
    .A(LINEA),
    .Y(_02_)
  );
  NOR3 _18_ (
    .A(STATO_REG_1_),
    .B(_00_),
    .C(STATO_REG_0_),
    .Y(U31)
  );
  NAND2 _19_ (
    .A(_00_),
    .B(LINEA),
    .Y(_03_)
  );
  OAI21 _20_ (
    .A0(STATO_REG_2_),
    .A1(_02_),
    .B0(STATO_REG_0_),
    .Y(_04_)
  );
  NOR2 _21_ (
    .A(STATO_REG_2_),
    .B(LINEA),
    .Y(_05_)
  );
  INV _22_ (
    .A(_05_),
    .Y(_06_)
  );
  OAI21 _23_ (
    .A0(STATO_REG_2_),
    .A1(LINEA),
    .B0(STATO_REG_1_),
    .Y(_07_)
  );
  AOI22 _24_ (
    .A0(STATO_REG_0_),
    .A1(_03_),
    .B0(_06_),
    .B1(STATO_REG_1_),
    .Y(U32)
  );
  NOR3 _25_ (
    .A(STATO_REG_1_),
    .B(STATO_REG_2_),
    .C(LINEA),
    .Y(_08_)
  );
  NAND2 _26_ (
    .A(STATO_REG_2_),
    .B(LINEA),
    .Y(_09_)
  );
  INV _27_ (
    .A(_09_),
    .Y(_10_)
  );
  OAI22 _28_ (
    .A0(_01_),
    .A1(_08_),
    .B0(_10_),
    .B1(_07_),
    .Y(U33)
  );
  NOR2 _29_ (
    .A(_13_),
    .B(STATO_REG_2_),
    .Y(_11_)
  );
  AOI21 _30_ (
    .A0(STATO_REG_1_),
    .A1(_00_),
    .B0(_01_),
    .Y(_12_)
  );
  OAI21 _31_ (
    .A0(_04_),
    .A1(_11_),
    .B0(_12_),
    .Y(U38)
  );
  \$_FF_  _32_ (
    .D(U31),
    .Q(U_REG)
  );
  \$_FF_  _33_ (
    .D(U33),
    .Q(STATO_REG_2_)
  );
  \$_FF_  _34_ (
    .D(U38),
    .Q(STATO_REG_1_)
  );
  \$_FF_  _35_ (
    .D(U32),
    .Q(STATO_REG_0_)
  );
  assign U = U_REG;
endmodule
